### ISSUE TITLE
SP-EUC01 no power consumption data

### ISSUE THREAD

**Issue by barskykd** [Koenkk/zigbee-herdsman-converters#1050]
I have this smart socket https://www.zigbee2mqtt.io/devices/SP-EUC01.html

When connected to Aqara Hub and Aqara Home it does report energy consumption over day.

When I connect it via zigbee2mqtt I receive only "state" and "link_quality". 
I enabled debug logging and I don't see any extra data being received from socket.

I edited devices.js and copied config from other xiaomi smart sockets. As expected it didn't help.

So is there some other configuration required?

**Comment by barskykd** [comment]
After some more trial and error got some data with this config

```js
{
        zigbeeModel: ['lumi.plug.maeu01'],
        model: 'SP-EUC01',
        description: 'Aqara EU smart plug',
        supports: 'on/off, power measurement',
        vendor: 'Xiaomi',
        fromZigbee: [
            fz.on_off, fz.electrical_measurement
        ],
        toZigbee: [tz.on_off],
        meta: {configureKey: 2},
         configure: async (device, coordinatorEndpoint) => {
             const endpoint = device.getEndpoint(1);
             await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement']);
             await configureReporting.onOff(endpoint);
             await configureReporting.activePower(endpoint);
         }
    }
```

```
zigbee2mqtt:debug 2020-03-10 11:20:57: Received Zigbee message from 'socket1', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":22}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-03-10 11:20:57: MQTT publish: topic 'zigbee2mqtt/socket1', payload '{"state":"ON","linkquality":84,"power":22}'
```

**Comment by barskykd** [comment]
Tested with 40W lightbulb and got 376-408 of 'power'. So unit is 0.1W

**Comment by Koenkk** [comment]
Yesterday I did quite some refactoring regarding power readings, so please update to the latest dev branch and now test with this definition:

```js
{
    zigbeeModel: ['lumi.plug.maeu01'],
    model: 'SP-EUC01',
    description: 'Aqara EU smart plug',
    supports: 'on/off, power measurements',
    vendor: 'Xiaomi',
    fromZigbee: [fz.on_off, fz.xiaomi_plug_state, fz.electrical_measurement_power],
    toZigbee: [tz.on_off],
    meta: {configureKey: 3},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement']);
        await configureReporting.onOff(endpoint);
        await readEletricalMeasurementPowerConverterAttributes(endpoint);
        await configureReporting.rmsVoltage(endpoint);
        await configureReporting.rmsCurrent(endpoint);
        await configureReporting.activePower(endpoint);
    },
},
```

**Comment by barskykd** [comment]
Now reports proper watts. Still no voltage/current though.

```
zigbee2mqtt:info  2020-03-11 05:14:41: socket1 (0x04cf8cdf3c765725): SP-EUC01 - Xiaomi Aqara EU smart plug (Router)
zigbee2mqtt:info  2020-03-11 05:14:42: MQTT publish: topic 'zigbee2mqtt/socket1', payload '{"state":"ON","linkquality":78,"power":1.9}'
zigbee2mqtt:debug 2020-03-11 05:15:56: Received Zigbee message from 'socket1', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":0}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-03-11 05:15:56: MQTT publish: topic 'zigbee2mqtt/socket1', payload '{"state":"ON","linkquality":81,"power":0}'
zigbee2mqtt:debug 2020-03-11 05:15:59: Received Zigbee message from 'socket1', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":408}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-03-11 05:15:59: MQTT publish: topic 'zigbee2mqtt/socket1', payload '{"state":"ON","linkquality":81,"power":40.8}'
zigbee2mqtt:debug 2020-03-11 05:16:02: Received Zigbee message from 'socket1', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":376}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-03-11 05:16:02: MQTT publish: topic 'zigbee2mqtt/socket1', payload '{"state":"ON","linkquality":84,"power":37.6}'
zigbee2mqtt:debug 2020-03-11 05:16:05: Received Zigbee message from 'socket1', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":408}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-03-11 05:16:05: MQTT publish: topic 'zigbee2mqtt/socket1', payload '{"state":"ON","linkquality":76,"power":40.8}'
zigbee2mqtt:debug 2020-03-11 05:16:07: Received Zigbee message from 'socket1', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":376}' from endpoint 1 with groupID 0
```

**Comment by Koenkk** [comment]
> When connected to Aqara Hub and Aqara Home it does report energy consumption over day.

Does it report voltage in the hub?

**Comment by barskykd** [comment]
No. For some reason it doesn't even show current power consumption. Only cumulative watt-hours over day.

**Comment by Koenkk** [comment]
In that case I doubt if it stops current and voltage readings. Could you make a PR with the current changes?

**Comment by Koenkk** [comment]
merged, thanks!

**Comment by rotdrop** [comment]
Hi,

I have two of those devices and the power readings are too high by a factor of 10. I get the "activePower" reportings as indicated in the post https://github.com/Koenkk/zigbee-herdsman-converters/issues/1050#issuecomment-597449239 but the reading is then not divided by ten and reported as is. The current dev, master and release tag show just the same behaviour:

```
debug 2020-07-06 10:04:05: Received Zigbee message from '0x04cf8cdf3c79c957', type 'attributeReport', cluster 'haElectri
calMeasurement', data '{"activePower":31}' from endpoint 1 with groupID 0
info  2020-07-06 10:04:05: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c79c957', payload '{"state":"ON","linkquality":94
,"last_seen":1594022645170,"power":31,"elapsed":29878}'
info  2020-07-06 10:04:05: Configuring '0x04cf8cdf3c79c957'
debug 2020-07-06 10:04:05: Received Zigbee message from '0x04cf8cdf3c79c957', type 'readResponse', cluster 'haElectrical
Measurement', data '{}' from endpoint 1 with groupID 0
error 2020-07-06 10:04:05: Failed to configure '0x04cf8cdf3c79c957', attempt 3 (Error: Read 0x04cf8cdf3c79c957/1 haElectricalMeasurement(["acVoltageMultiplier","acVoltageDivisor","acCurrentMultiplier"], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.<anonymous> (/srv/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:192:23)
    at Generator.next (<anonymous>)
    at fulfilled (/srv/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58))
```

Just as note: as indicated in the posts above, there is no voltage, current, temperature measurement. Where to look for the scaling of the power measurement?

Kind thanks Claus

**Comment by Koenkk** [comment]
@rotdrop found a possible fix. Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by rotdrop** [comment]
Kind thanks for a reply on a closed issue (should I create a new one?)

However:  I am on the latest dev branch (fiddling with OTA). At least up to now the power reported by zigbee2mqtt has still this factor of 10. Of course, it is possible to work around (thinking of home-assistant) using a template sensor which simply divides the "raw value" by 10. Would be nice if this would not be necessary, but in principle it is a minor issue.

Many thanks for your work!

**Comment by Koenkk** [comment]
Can you share your data/database.db entry of this device?

**Comment by rotdrop** [comment]
@Koenkk 

> Can you share your data/database.db entry of this device?

Here it is. The acPowerDivisor is 10, which in principle is correct. However, the value published to the mqtt broker is still the original one.

```
{"id":32,"type":"Router","ieeeAddr":"0x04cf8cdf3c79c957","nwkAddr":10343,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.plug.maeu01","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,2,3,4,5,6,9,1794,2820],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.plug.maeu01","manufacturerName":"LUMI","powerSource":1,"zclVersion":3,"appVersion":22,"stackVersion":2,"hwVersion":1,"dateCode":"09-10-2019"}},"haElectricalMeasurement":{"attributes":{"activePower":31,"acPowerMultiplier":1,"acPowerDivisor":10}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00194a1805","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b00194a1805","endpointID":1}]},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":22,"stackVersion":2,"hwVersion":1,"dateCode":"09-10-2019","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1594171984357}
```

**Comment by Koenkk** [comment]
Can you provide the debug logging when receiving these power message? And how much load did you attach?

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by rotdrop** [comment]
Ooops. It now seems to work. I suppose the mqtt topic was published from cached values. Sorry for wasting your time.

I have just power-cycled (off-on) which then resulted in updating the power usage:

```
debug 2020-07-08 15:59:00: Received Zigbee message from '0x04cf8cdf3c79c957', type 'attributeReport', cluster 'haElectricalMeasurement', data '{"activePower":30}' from endpoint 1 with groupID 0
info  2020-07-08 15:59:00: MQTT publish: topic 'zigbee2mqtt/0x04cf8cdf3c79c957', payload '{"state":"ON","linkquality":131,"last_seen":1594216740762,"power":3,"elapsed":15273}'
```

**Comment by Koenkk** [comment]
Great!

**Comment by mrjoun** [comment]
Hi,

I have two of those devices. Failed to configure devices. The current dev, master and release tag show just the same behaviour:
```
авг 12 15:06:08 nuc npm[3909]: zigbee2mqtt:debug 2020-08-12 15:06:08: Received Zigbee message from '0x04cf8cdf3c765f93', type 'readResponse', cluster 'haElectricalMeasurement', data '{"acPowerMultiplier":1,"acPowerDivisor":10}' from endpoint 1 with groupID 0
авг 12 15:06:08 nuc npm[3909]: zigbee2mqtt:error 2020-08-12 15:06:08: Failed to configure '0x04cf8cdf3c765f93', attempt 1 (Error: ConfigureReporting 0x04cf8cdf3c765f93/1 haElectricalMeasurement([{"attribute":"activePower","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":1}], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Status 'UNREPORTABLE_ATTRIBUTE')
авг 12 15:06:08 nuc npm[3909]:     at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:140:23)
авг 12 15:06:08 nuc npm[3909]:     at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:348:26)
авг 12 15:06:08 nuc npm[3909]:     at Generator.next (<anonymous>)
авг 12 15:06:08 nuc npm[3909]:     at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58))
```
It's normal?

In database.db:
```
{"id":2,"type":"Router","ieeeAddr":"0x04cf8cdf3c765f93","nwkAddr":8275,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.plug.maeu01","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,2,3,4,5,6,9,1794,2820],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.plug.maeu01","manufacturerName":"LUMI","powerSource":1,"zclVersion":3,"appVersion":22,"stackVersion":2,"hwVersion":1,"dateCode":"09-10-2019"}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0014d92e2c","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0014d92e2c","endpointID":1}]},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":22,"stackVersion":2,"hwVersion":1,"dateCode":"09-10-2019","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1597233967934}
```

**Comment by Koenkk** [comment]
Can you try changing the entry in `devices.js` to 

```js
{
    zigbeeModel: ['lumi.plug.maeu01'],
    model: 'SP-EUC01',
    description: 'Aqara EU smart plug',
    supports: 'on/off, power measurements',
    vendor: 'Xiaomi',
    fromZigbee: [fz.on_off, fz.xiaomi_plug_state, fz.electrical_measurement_power],
    toZigbee: [tz.on_off],
    meta: {configureKey: 3},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement']);
        await configureReporting.onOff(endpoint);
        //await endpoint.read('haElectricalMeasurement', ['acPowerMultiplier', 'acPowerDivisor']);
        await configureReporting.activePower(endpoint);
        // Voltage/current doesn't seem to be supported, maybe in futurue revisions of the device (?).
        // https://github.com/Koenkk/zigbee-herdsman-converters/issues/1050
    },
},
```

See https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html how to modify that.

I expect that after this change power is reported but probably x10 or x100 the actual value.

**Comment by mrjoun** [comment]
Without changes

**Comment by Koenkk** [comment]
I'm wondering if this device actually supports instantaneous power measurements (as that also does not seem to be shown in the app, only cumulative). @barskykd do you get `power` values?

**Comment by mrjoun** [comment]
I have usb stick cc2531 with firmware Zigbee 3.0 (plug use Zigbee 3.0).
From plug I only need to turn on and off. Power measurements don’t need. In Domoticz plug was found, but don’t control.

**Comment by barskykd** [comment]
@Koenkk  Yes. I do. I’m not sure i am running latest version of code. It reports current power in watts. No voltage/current.

**Comment by Mytherios** [comment]
I cannot display the following parameters: power, energy, temperature, voltage. Everywhere I have a message that a parameter is not available. What should I do to display them?

**Comment by TheJulianJES** [comment]
IIRC all devices should support power consumption. The "mode" on the "Opple cluster" just needs to be set to 0.
See https://github.com/zigpy/zha-device-handlers/pull/1479/files and https://github.com/zigpy/zha-device-handlers/issues/1337

**Comment by sdamion** [comment]
Is this issue fixed because the only thing working is the on /off and device temprature
