### ISSUE TITLE
Adding new zigbeeModel to existing device fails

### ISSUE THREAD

**Issue by patricker** [Koenkk/zigbee-herdsman-converters#1177]
In the past you've added new versions of the Keen Smart Vents without issue by adding on additional model names.  I found that 'SV01-412-MP-1.4' was missing, so I added it and restarted my docker container.  I then received the following error:

error 2020-04-22 11:45:08: Failed to configure '0x0022a30000150478', attempt 3 (Error: ConfigureReporting 0x0022a30000150478/1 msTemperatureMeasurement([{"attribute":"measuredValue","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":25}], {"timeout":10000,"manufacturerCode":null,"disableDefaultResponse":true}) failed (Error: Status 'INVALID_VALUE')
    at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:326:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58))

**Comment by patricker** [comment]
I removed/added the device and now it's happy, manufacturerCode wasn't null on the next pairing.
