### ISSUE TITLE
OSRAM 4x EU-LIGHTIFY fails to configure

### ISSUE THREAD

**Issue by DBa2016** [Koenkk/zigbee-herdsman-converters#1332]
Added this wall switch successfully, pairing went successfully:
````
zigbee2mqtt:info  2020-06-20 01:20:30: Device '0x000d6f0011b3f3db' joined
zigbee2mqtt:info  2020-06-20 01:20:30: Starting interview of '0x000d6f0011b3f3db'
zigbee2mqtt:info  2020-06-20 01:20:30: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x000d6f0011b3f3db"}}'
zigbee2mqtt:info  2020-06-20 01:20:30: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x000d6f0011b3f3db"}}'
zigbee2mqtt:debug 2020-06-20 01:20:31: Received Zigbee message from '0x000d6f0011b3f3db', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 3 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:31: Received Zigbee message from '0x000d6f0011b3f3db', type 'commandMoveHue', cluster 'lightingColorCtrl', data '{"movemode":0,"rate":0}' from endpoint 2 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:34: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"modelId":"Switch 4x EU-LIGHTIFY"}' from endpoint 1 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:35: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"OSRAM"}' from endpoint 1 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:36: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:37: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1}' from endpoint 1 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:38: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"appVersion":1}' from endpoint 1 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:39: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 1 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:40: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"hwVersion":1}' from endpoint 1 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:41: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"dateCode":"201808081820420"}' from endpoint 1 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:42: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"e.1.0.0M"}' from endpoint 1 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:44: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 2 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:46: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 3 with groupID null
[...some "devices" listing containing the entire network information, will not post them here due to the size... ]
zigbee2mqtt:debug 2020-06-20 01:20:48: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 4 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:50: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 5 with groupID null
zigbee2mqtt:debug 2020-06-20 01:20:52: Received Zigbee message from '0x000d6f0011b3f3db', type 'readResponse', cluster 'genBasic', data '{"stackVersion":0}' from endpoint 6 with groupID null
zigbee2mqtt:info  2020-06-20 01:20:52: Successfully interviewed '0x000d6f0011b3f3db', device has successfully been paired
````

Then configuration starts:
````
zigbee2mqtt:info  2020-06-20 01:20:52: Device '0x000d6f0011b3f3db' is supported, identified as: OSRAM Smart+ switch (4058075816459)
zigbee2mqtt:info  2020-06-20 01:20:52: Configuring '0x000d6f0011b3f3db'
zigbee2mqtt:info  2020-06-20 01:20:52: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x000d6f0011b3f3db","model":"4058075816459","vendor":"OSRAM","descr
iption":"Smart+ switch","supported":true}}'
zigbee2mqtt:debug 2020-06-20 01:21:04: Received Zigbee message from '0x000d6f0011b3f3db', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 3 with groupID null
zigbee2mqtt:info  2020-06-20 01:21:04: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"action":"left_bottom_click","linkquality":21}'
zigbee2mqtt:info  2020-06-20 01:21:04: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"action":""}'
zigbee2mqtt:info  2020-06-20 01:21:04: MQTT publish: topic 'homeassistant/device_automation/0x000d6f0011b3f3db/action_left_bottom_click/config', payload '{"automation_type":"trigger","type":"action","subtype":"left_bottom_click","payload
":"left_bottom_click","topic":"zigbee2mqtt/0x000d6f0011b3f3db/action","device":{"identifiers":["zigbee2mqtt_0x000d6f0011b3f3db"],"name":"0x000d6f0011b3f3db","sw_version":"Zigbee2mqtt 1.14.0-dev","model":"Smart+ switch (4058075816459)","m
anufacturer":"OSRAM"}}'
zigbee2mqtt:info  2020-06-20 01:21:04: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"update_available":false}'
zigbee2mqtt:info  2020-06-20 01:21:04: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db/action', payload 'left_bottom_click'
zigbee2mqtt:info  2020-06-20 01:21:04: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"update_available":false}'
zigbee2mqtt:debug 2020-06-20 01:21:29: Received Zigbee message from '0x000d6f0011b3f3db', type 'commandMoveWithOnOff', cluster 'genLevelCtrl', data '{"movemode":0,"rate":38}' from endpoint 1 with groupID null
zigbee2mqtt:info  2020-06-20 01:21:29: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"update_available":false,"action":"left_top_hold"}'
zigbee2mqtt:info  2020-06-20 01:21:29: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"update_available":false,"action":""}'
zigbee2mqtt:info  2020-06-20 01:21:29: MQTT publish: topic 'homeassistant/device_automation/0x000d6f0011b3f3db/action_left_top_hold/config', payload '{"automation_type":"trigger","type":"action","subtype":"left_top_hold","payload":"left_
top_hold","topic":"zigbee2mqtt/0x000d6f0011b3f3db/action","device":{"identifiers":["zigbee2mqtt_0x000d6f0011b3f3db"],"name":"0x000d6f0011b3f3db","sw_version":"Zigbee2mqtt 1.14.0-dev","model":"Smart+ switch (4058075816459)","manufacturer"
:"OSRAM"}}'
zigbee2mqtt:info  2020-06-20 01:21:29: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db/action', payload 'left_top_hold'
zigbee2mqtt:debug 2020-06-20 01:21:30: Received Zigbee message from '0x000d6f0011b3f3db', type 'commandStop', cluster 'genLevelCtrl', data '{}' from endpoint 1 with groupID null
zigbee2mqtt:info  2020-06-20 01:21:30: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"update_available":false,"action":"left_top_release"}'
zigbee2mqtt:info  2020-06-20 01:21:30: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"update_available":false,"action":""}'
zigbee2mqtt:info  2020-06-20 01:21:30: MQTT publish: topic 'homeassistant/device_automation/0x000d6f0011b3f3db/action_left_top_release/config', payload '{"automation_type":"trigger","type":"action","subtype":"left_top_release","payload":
"left_top_release","topic":"zigbee2mqtt/0x000d6f0011b3f3db/action","device":{"identifiers":["zigbee2mqtt_0x000d6f0011b3f3db"],"name":"0x000d6f0011b3f3db","sw_version":"Zigbee2mqtt 1.14.0-dev","model":"Smart+ switch (4058075816459)","manu
facturer":"OSRAM"}}'
zigbee2mqtt:info  2020-06-20 01:21:30: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db/action', payload 'left_top_release'
zigbee2mqtt:debug 2020-06-20 01:21:35: Received Zigbee message from '0x000d6f0011b3f3db', type 'commandStepColorTemp', cluster 'lightingColorCtrl', data '{"stepmode":3,"stepsize":25,"transtime":10,"minimum":0,"maximum":0}' from endpoint
4 with groupID null
zigbee2mqtt:info  2020-06-20 01:21:35: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"update_available":false,"action":"right_bottom_click"}'
zigbee2mqtt:info  2020-06-20 01:21:35: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"update_available":false,"action":""}'
zigbee2mqtt:info  2020-06-20 01:21:35: MQTT publish: topic 'homeassistant/device_automation/0x000d6f0011b3f3db/action_right_bottom_click/config', payload '{"automation_type":"trigger","type":"action","subtype":"right_bottom_click","paylo
ad":"right_bottom_click","topic":"zigbee2mqtt/0x000d6f0011b3f3db/action","device":{"identifiers":["zigbee2mqtt_0x000d6f0011b3f3db"],"name":"0x000d6f0011b3f3db","sw_version":"Zigbee2mqtt 1.14.0-dev","model":"Smart+ switch (4058075816459)"
,"manufacturer":"OSRAM"}}'
zigbee2mqtt:info  2020-06-20 01:21:35: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db/action', payload 'right_bottom_click'
zigbee2mqtt:debug 2020-06-20 01:21:38: Received Zigbee message from '0x000d6f0011b3f3db', type 'commandStepColorTemp', cluster 'lightingColorCtrl', data '{"stepmode":1,"stepsize":25,"transtime":10,"minimum":0,"maximum":0}' from endpoint
2 with groupID null
zigbee2mqtt:info  2020-06-20 01:21:38: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"update_available":false,"action":"right_top_click"}'
zigbee2mqtt:info  2020-06-20 01:21:38: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"update_available":false,"action":""}'
zigbee2mqtt:info  2020-06-20 01:21:38: MQTT publish: topic 'homeassistant/device_automation/0x000d6f0011b3f3db/action_right_top_click/config', payload '{"automation_type":"trigger","type":"action","subtype":"right_top_click","payload":"r
ight_top_click","topic":"zigbee2mqtt/0x000d6f0011b3f3db/action","device":{"identifiers":["zigbee2mqtt_0x000d6f0011b3f3db"],"name":"0x000d6f0011b3f3db","sw_version":"Zigbee2mqtt 1.14.0-dev","model":"Smart+ switch (4058075816459)","manufacturer":"OSRAM"}}'
zigbee2mqtt:info  2020-06-20 01:21:38: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db/action', payload 'right_top_click'
zigbee2mqtt:debug 2020-06-20 01:21:43: Received Zigbee message from '0x000d6f0011b3f3db', type 'commandOff', cluster 'genOnOff', data '{}' from endpoint 3 with groupID null
zigbee2mqtt:info  2020-06-20 01:21:43: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"update_available":false,"action":"left_bottom_click"}'
zigbee2mqtt:info  2020-06-20 01:21:43: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db', payload '{"linkquality":21,"update_available":false,"action":""}'
zigbee2mqtt:info  2020-06-20 01:21:43: MQTT publish: topic 'zigbee2mqtt/0x000d6f0011b3f3db/action', payload 'left_bottom_click'
[...again a huge message about "devices"...]
zigbee2mqtt:error 2020-06-20 01:21:52: Failed to configure '0x000d6f0011b3f3db', attempt 1 (Error: Bind 0x000d6f0011b3f3db/1 genOnOff from '0x00212effff054964/1' failed (undefined)
    at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:255:23)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))

````
The configuration is attempted few times more, but with the same result.

Now the real bad thing is, that the switch now is set to broadcast: when pressing "left top" button, every bulb and every plug connected to the same gateway is turned on (good thing is: my bedroom is on a separate gateway, otherwise I'd be dead by now, my wife is sleeping already... :)). When pressing "left bottom", similarly, every bulb and every plug is turned off (good thing: I did notice this and therefore was able to turn on my fridge again before anything bad happened).

Not sure whether this is a crappy device or whether we have anb issue here...

I am running "latest-dev" docker image and the converters are in a separate directory and up to date with "master" branch, so don't think I am suffering from old code...

Any suggestions?

**Comment by Koenkk** [comment]
Something is wrong indeed, can you post the herdsman debug logging when configure starts?

To enable herdsman debug logging, see https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging
