### ISSUE TITLE
Reporting of a two-channel device (Ubisys S2)

### ISSUE THREAD

**Issue by theFork** [Koenkk/zigbee-herdsman-converters#1334]
I'm using a bunch of Ubisys S2 in-wall switches for my lighting. They have two channels, and a few months ago I was happy that both of them reported their state to Z2M. Then I found, as the devicecount on my network inreased, that some of them only report On/Off-Changes of their first channel. Now I'm reproducing with a minimal setup and a much more powerful coordinator:

# Setup
* Z2M `1.14.0`
    * Running as add-on in homeassistant
    * MQTT discovery deactivated, no devices manually added
* Coordinator ZZH (TI CC2652R)
    * Firmware  `CC26X2R1_20200417`
* Zigbee-Network
    * Only coordinator and two Ubisys S2 joined

# When happens
This is how it looks in the log, when switching off the lamp connected fo channel 2. The `power` field goes from 21 to 0, but the field `state_l2` is always `OFF`:

```
zigbee2mqtt:info  2020-06-19 21:30:38: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":21,"linkquality":12,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:31:07: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":0,"linkquality":9,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
```

The entire pairing process and some switching tests looked like this:

```
zigbee2mqtt:info  2020-06-19 21:26:22: Device '0x001fee0000001815' joined
zigbee2mqtt:info  2020-06-19 21:26:22: Starting interview of '0x001fee0000001815'
zigbee2mqtt:info  2020-06-19 21:26:22: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x001fee0000001815"}}'
zigbee2mqtt:info  2020-06-19 21:26:22: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x001fee0000001815"}}'
zigbee2mqtt:info  2020-06-19 21:26:23: Successfully setup reporting for '0x001fee0000001815' - 1 - genOnOff
zigbee2mqtt:info  2020-06-19 21:26:23: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x001fee0000001815"}}'
zigbee2mqtt:info  2020-06-19 21:26:24: Successfully interviewed '0x001fee0000001815', device has successfully been paired
zigbee2mqtt:info  2020-06-19 21:26:24: Device '0x001fee0000001815' is supported, identified as: Ubisys Power switch S2 (S2)
zigbee2mqtt:info  2020-06-19 21:26:24: Configuring '0x001fee0000001815'
zigbee2mqtt:info  2020-06-19 21:26:24: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x001fee0000001815","model":"S2","vendor":"Ubisys","description":"Power switch S2","supported":true}}'
zigbee2mqtt:info  2020-06-19 21:26:25: Successfully configured '0x001fee0000001815'
zigbee2mqtt:info  2020-06-19 21:26:25: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":0,"linkquality":15,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:26:26: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":0,"linkquality":12,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:26:58: MQTT publish: topic 'zigbee2mqtt/0x001fee00000030b7', payload '{"power":0,"linkquality":78,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
zigbee2mqtt:error 2020-06-19 21:27:01: Failed to call 'OTAUpdate' 'onZigbeeEvent' (AssertionError [ERR_ASSERTION]: No image available for imageType '0x7b03' with hardware version 5
    at getImageMeta (/zigbee2mqtt-1.14.0/node_modules/zigbee-herdsman-converters/ota/ubisys.js:22:5)
        at runMicrotasks (<anonymous>)
            at processTicksAndRejections (internal/process/task_queues.js:94:5)
                at async isNewImageAvailable (/zigbee2mqtt-1.14.0/node_modules/zigbee-herdsman-converters/ota/ubisys.js:49:18)
                    at async Object.isUpdateAvailable (/zigbee2mqtt-1.14.0/node_modules/zigbee-herdsman-converters/ota/common.js:168:23)
                        at async OTAUpdate.onZigbeeEvent (/zigbee2mqtt-1.14.0/lib/extension/otaUpdate.js:37:31)
                            at async Controller.callExtensionMethod (/zigbee2mqtt-1.14.0/lib/controller.js:352:21))
zigbee2mqtt:info  2020-06-19 21:28:59: Starting network scan (includeRoutes 'false')
zigbee2mqtt:info  2020-06-19 21:28:59: Network scan finished
zigbee2mqtt:info  2020-06-19 21:28:59: MQTT publish: topic 'zigbee2mqtt/bridge/networkmap/raw', payload '{"nodes":[{"ieeeAddr":"0x00124b001e17f0bd","friendlyName":"Coordinator","type":"Coordinator","networkAddress":0,"failed":[],"lastSeen":null},{"ieeeAddr":"0x001fee00000030b7","friendlyName":"0x001fee00000030b7","type":"Router","networkAddress":58457,"manufacturerName":"ubisys","modelID":"S2 (5502)","failed":[],"lastSeen":1592594818485},{"ieeeAddr":"0x001fee0000001815","friendlyName":"0x001fee0000001815","type":"Router","networkAddress":415,"manufacturerName":"ubisys","modelID":"S2 (5502)","failed":[],"lastSeen":1592594821245}],"links":[{"source":{"ieeeAddr":"0x001fee00000030b7","networkAddress":58457},"target":{"ieeeAddr":"0x00124b001e17f0bd","networkAddress":0},"linkquality":77,"depth":1,"routes":[],"sourceIeeeAddr":"0x001fee00000030b7","targetIeeeAddr":"0x00124b001e17f0bd","sourceNwkAddr":58457,"lqi":77,"relationship":1},{"source":{"ieeeAddr":"0x001fee0000001815","networkAddress":415},"target":{"ieeeAddr":"0x00124b001e17f0bd","networkAddress":0},"linkquality":13,"depth":1,"routes":[],"sourceIeeeAddr":"0x001fee0000001815","targetIeeeAddr":"0x00124b001e17f0bd","sourceNwkAddr":415,"lqi":13,"relationship":1},{"source":{"ieeeAddr":"0x00124b001e17f0bd","networkAddress":0},"target":{"ieeeAddr":"0x001fee00000030b7","networkAddress":58457},"linkquality":232,"depth":255,"routes":[],"sourceIeeeAddr":"0x00124b001e17f0bd","targetIeeeAddr":"0x001fee00000030b7","sourceNwkAddr":0,"lqi":232,"relationship":2},{"source":{"ieeeAddr":"0x001fee0000001815","networkAddress":415},"target":{"ieeeAddr":"0x001fee00000030b7","networkAddress":58457},"linkquality":135,"depth":255,"routes":[],"sourceIeeeAddr":"0x001fee0000001815","targetIeeeAddr":"0x001fee00000030b7","sourceNwkAddr":415,"lqi":135,"relationship":2},{"source":{"ieeeAddr":"0x00124b001e17f0bd","networkAddress":0},"target":{"ieeeAddr":"0x001fee0000001815","networkAddress":415},"linkquality":141,"depth":255,"routes":[],"sourceIeeeAddr":"0x00124b001e17f0bd","targetIeeeAddr":"0x001fee0000001815","sourceNwkAddr":0,"lqi":141,"relationship":2},{"source":{"ieeeAddr":"0x001fee00000030b7","networkAddress":58457},"target":{"ieeeAddr":"0x001fee0000001815","networkAddress":415},"linkquality":131,"depth":255,"routes":[],"sourceIeeeAddr":"0x001fee00000030b7","targetIeeeAddr":"0x001fee0000001815","sourceNwkAddr":58457,"lqi":131,"relationship":2}]}'
zigbee2mqtt:info  2020-06-19 21:29:25: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":21,"linkquality":0,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:29:27: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":0,"linkquality":0,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:29:37: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":15,"linkquality":78,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:29:38: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":21,"linkquality":78,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:29:45: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":0,"linkquality":78,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:30:06: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":0,"linkquality":15,"state_l1":"ON","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:30:06: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":79,"linkquality":15,"state_l1":"ON","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:30:07: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":73,"linkquality":18,"state_l1":"ON","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:30:08: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":73,"linkquality":21,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:30:08: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":0,"linkquality":18,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:30:22: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":0,"linkquality":21,"state_l1":"ON","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:30:22: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":73,"linkquality":18,"state_l1":"ON","state_l2":"OFF","update_available":false}'
zigbee2mqtt:info  2020-06-19 21:30:31: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"power":73,"linkquality":24,"state_l1":"OFF","state_l2":"OFF","update_available":false}'
```

database.db:

```
{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b001e17f0bd","nwkAddr":0,"manufId":0,"epList":[242,47,13,12,110,11,8,6,5,4,3,2,1],"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"8":{"profId":260,"epId":8,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[],"outClusterList":[1280,1282],"clusters":{},"binds":[]},"12":{"profId":49246,"epId":12,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"13":{"profId":260,"epId":13,"devId":5,"inClusterList":[25],"outClusterList":[],"clusters":{},"binds":[]},"47":{"profId":260,"epId":47,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"110":{"profId":260,"epId":110,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"242":{"profId":41440,"epId":242,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]}},"interviewCompleted":true,"meta":{},"lastSeen":null}
{"id":2,"type":"Router","ieeeAddr":"0x001fee00000030b7","nwkAddr":58457,"manufId":4338,"manufName":"ubisys","powerSource":"Mains (single phase)","modelId":"S2 (5502)","epList":[1,2,200,232,242,3,4,5],"endpoints":{"1":{"profId":260,"epId":1,"devId":266,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"S2 (5502)","manufacturerName":"ubisys","powerSource":1,"zclVersion":2,"appVersion":1,"stackVersion":1,"hwVersion":5,"dateCode":"20180517-DE-FB0","swBuildId":""}},"genOnOff":{"attributes":{"onOff":0}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b001e17f0bd","endpointID":1}]},"2":{"profId":260,"epId":2,"devId":266,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"swBuildId":""}}},"binds":[]},"3":{"profId":260,"epId":3,"devId":1,"inClusterList":[0,3],"outClusterList":[5,6,8],"clusters":{"genBasic":{"attributes":{}}},"binds":[]},"4":{"profId":260,"epId":4,"devId":1,"inClusterList":[0,3],"outClusterList":[5,6,8],"clusters":{"genBasic":{"attributes":{}}},"binds":[]},"5":{"profId":260,"epId":5,"devId":1281,"inClusterList":[0,1794,2820],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}},"seMetering":{"attributes":{"multiplier":1,"divisor":1000,"instantaneousDemand":0}}},"binds":[{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b001e17f0bd","endpointID":1}]},"200":{"profId":49155,"epId":200,"devId":0,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"232":{"profId":260,"epId":232,"devId":1287,"inClusterList":[0,21,64512],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{}}},"binds":[]},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":1,"stackVersion":1,"hwVersion":5,"dateCode":"20180517-DE-FB0","zclVersion":2,"interviewCompleted":true,"meta":{"reporting":1,"configured":3},"lastSeen":1592594480440}
{"id":3,"type":"Router","ieeeAddr":"0x001fee0000001815","nwkAddr":415,"manufId":4338,"manufName":"ubisys","powerSource":"Mains (single phase)","modelId":"S2 (5502)","epList":[1,2,200,232,242,3,4,5],"endpoints":{"1":{"profId":260,"epId":1,"devId":2,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"S2 (5502)","manufacturerName":"ubisys","powerSource":1,"zclVersion":2,"appVersion":1,"stackVersion":1,"hwVersion":5,"dateCode":"20170718-DE-FB0"}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b001e17f0bd","endpointID":1}]},"2":{"profId":260,"epId":2,"devId":2,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}}},"binds":[]},"3":{"profId":260,"epId":3,"devId":1,"inClusterList":[0,3],"outClusterList":[5,6,8],"clusters":{"genBasic":{"attributes":{}}},"binds":[]},"4":{"profId":260,"epId":4,"devId":1,"inClusterList":[0,3],"outClusterList":[5,6,8],"clusters":{"genBasic":{"attributes":{}}},"binds":[]},"5":{"profId":260,"epId":5,"devId":1281,"inClusterList":[0,1794,2820],"outClusterList":[],"clusters":{"genBasic":{"attributes":{}},"seMetering":{"attributes":{"multiplier":1,"divisor":1000}}},"binds":[{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b001e17f0bd","endpointID":1}]},"200":{"profId":49155,"epId":200,"devId":0,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"232":{"profId":260,"epId":232,"devId":1287,"inClusterList":[0,21,64512],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{}}},"binds":[]},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":1,"stackVersion":1,"hwVersion":5,"dateCode":"20170718-DE-FB0","zclVersion":2,"interviewCompleted":true,"meta":{"reporting":1,"configured":3},"lastSeen":1592594785001}
{"id":12,"ieeeAddr":"0x001fee000000181e","nwkAddr":64139,"manufName":"ubisys","powerSource":"Mains (single phase)","modelId":"S2 (5502)","epList":[1,2,200,232,242,3,4,5],"endpoints":{"1":{"profId":260,"epId":1,"devId":2,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"S2 (5502)","manufacturerName":"ubisys","powerSource":1,"zclVersion":2,"appVersion":1,"stackVersion":1,"hwVersion":5,"dateCode":"20170717-DE-FB0"}}},"binds":[]},"2":{"profId":260,"epId":2,"devId":2,"inClusterList":[0,3,4,5,6],"outClusterList":[],"clusters":{},"binds":[]},"3":{"profId":260,"epId":3,"devId":1,"inClusterList":[0,3],"outClusterList":[5,6,8],"clusters":{},"binds":[]},"4":{"profId":260,"epId":4,"devId":1,"inClusterList":[0,3],"outClusterList":[5,6,8],"clusters":{},"binds":[]},"5":{"profId":260,"epId":5,"devId":1281,"inClusterList":[0,1794,2820],"outClusterList":[],"clusters":{"seMetering":{"attributes":{"multiplier":1,"divisor":1000}}},"binds":[{"cluster":1794,"type":"endpoint","deviceIeeeAddress":"0x00124b001938aa2d","endpointID":1}]},"200":{"profId":49155,"epId":200,"devId":0,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"232":{"profId":260,"epId":232,"devId":1287,"inClusterList":[0,21,64512],"outClusterList":[3,25],"clusters":{},"binds":[]},"242":{"profId":41440,"epId":242,"devId":102,"inClusterList":[33],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":1,"stackVersion":1,"hwVersion":5,"dateCode":"20170717-DE-FB0","zclVersion":2,"interviewCompleted":true,"meta":{"configured":3},"lastSeen":1581108383531}#
```

For more details, I removed the device and paired it with debugging log level:
```
zigbee2mqtt:info  2020-06-21 16:50:47: Device '0x001fee0000001815' joined
zigbee2mqtt:info  2020-06-21 16:50:47: Starting interview of '0x001fee0000001815'
zigbee2mqtt:info  2020-06-21 16:50:47: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x001fee0000001815"}}'
zigbee2mqtt:info  2020-06-21 16:50:47: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x001fee0000001815"}}'
zigbee2mqtt:debug 2020-06-21 16:50:48: Device '0x001fee0000001815' announced itself
zigbee2mqtt:info  2020-06-21 16:50:48: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_announced","message":"announce","meta":{"friendly_name":"0x001fee0000001815"}}'
zigbee2mqtt:debug 2020-06-21 16:51:00: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{"modelId":"S2 (5502)"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:00: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{"modelId":"S2 (5502)"}'
zigbee2mqtt:debug 2020-06-21 16:51:00: Setup reporting for '0x001fee0000001815' - 1 - genOnOff
zigbee2mqtt:debug 2020-06-21 16:51:00: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"ubisys"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:00: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{"manufacturerName":"ubisys"}'
zigbee2mqtt:info  2020-06-21 16:51:00: Successfully setup reporting for '0x001fee0000001815' - 1 - genOnOff
zigbee2mqtt:debug 2020-06-21 16:51:00: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{"powerSource":1}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:00: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{"powerSource":1}'
zigbee2mqtt:debug 2020-06-21 16:51:00: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{"zclVersion":2}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:00: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{"zclVersion":2}'
zigbee2mqtt:debug 2020-06-21 16:51:00: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{"appVersion":1}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:00: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{"appVersion":1}'
zigbee2mqtt:debug 2020-06-21 16:51:00: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{"stackVersion":1}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:00: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{"stackVersion":1}'
zigbee2mqtt:debug 2020-06-21 16:51:00: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{"hwVersion":5}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:00: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{"hwVersion":5}'
zigbee2mqtt:debug 2020-06-21 16:51:00: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20170718-DE-FB0"}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:00: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{"dateCode":"20170718-DE-FB0"}'
zigbee2mqtt:debug 2020-06-21 16:51:00: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:00: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{}'
zigbee2mqtt:debug 2020-06-21 16:51:00: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:00: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{}'
zigbee2mqtt:debug 2020-06-21 16:51:01: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 232 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:01: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{}'
zigbee2mqtt:debug 2020-06-21 16:51:01: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 3 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:01: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{}'
zigbee2mqtt:debug 2020-06-21 16:51:01: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 4 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:01: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{}'
zigbee2mqtt:debug 2020-06-21 16:51:01: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'genBasic', data '{}' from endpoint 5 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:01: No converter available for 'S2' with cluster 'genBasic' and type 'readResponse' and data '{}'
zigbee2mqtt:info  2020-06-21 16:51:01: Successfully interviewed '0x001fee0000001815', device has successfully been paired
zigbee2mqtt:info  2020-06-21 16:51:01: Device '0x001fee0000001815' is supported, identified as: Ubisys Power switch S2 (S2)
zigbee2mqtt:info  2020-06-21 16:51:01: Configuring '0x001fee0000001815'
zigbee2mqtt:info  2020-06-21 16:51:01: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x001fee0000001815","model":"S2","vendor":"Ubisys","description":"Power switch S2","supported":true}}'
zigbee2mqtt:debug 2020-06-21 16:51:01: Received Zigbee message from '0x001fee0000001815', type 'readResponse', cluster 'seMetering', data '{"multiplier":1,"divisor":1000}' from endpoint 5 with groupID 0
zigbee2mqtt:info  2020-06-21 16:51:01: Successfully configured '0x001fee0000001815'
zigbee2mqtt:debug 2020-06-21 16:51:02: Received Zigbee message from '0x001fee0000001815', type 'attributeReport', cluster 'genOnOff', data '{"onOff":0}' from endpoint 1 with groupID 0
zigbee2mqtt:info  2020-06-21 16:51:02: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"state_l1":"OFF","linkquality":15,"power":0}'
zigbee2mqtt:debug 2020-06-21 16:51:03: Received Zigbee message from '0x001fee0000001815', type 'attributeReport', cluster 'seMetering', data '{"instantaneousDemand":0}' from endpoint 5 with groupID 0
zigbee2mqtt:info  2020-06-21 16:51:03: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"state_l1":"OFF","linkquality":15,"power":0}'
zigbee2mqtt:debug 2020-06-21 16:51:03: Saving state to file /share/zigbee2mqtt/state.json
zigbee2mqtt:debug 2020-06-21 16:51:28: Received Zigbee message from '0x001fee0000001815', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":1,"manufacturerCode":4338,"imageType":31491,"fileVersion":17564001}' from endpoint 232 with groupID 0
zigbee2mqtt:debug 2020-06-21 16:51:28: Check if update available for '0x001fee0000001815' (S2 (5502))
zigbee2mqtt:error 2020-06-21 16:51:28: Failed to call 'OTAUpdate' 'onZigbeeEvent' (AssertionError [ERR_ASSERTION]: No image available for imageType '0x7b03' with hardware version 5
    at getImageMeta (/zigbee2mqtt-1.14.0/node_modules/zigbee-herdsman-converters/ota/ubisys.js:22:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async isNewImageAvailable (/zigbee2mqtt-1.14.0/node_modules/zigbee-herdsman-converters/ota/ubisys.js:49:18)
    at async Object.isUpdateAvailable (/zigbee2mqtt-1.14.0/node_modules/zigbee-herdsman-converters/ota/common.js:168:23)
    at async OTAUpdate.onZigbeeEvent (/zigbee2mqtt-1.14.0/lib/extension/otaUpdate.js:37:31)
    at async Controller.callExtensionMethod (/zigbee2mqtt-1.14.0/lib/controller.js:352:21))
zigbee2mqtt:debug 2020-06-21 16:52:48: Received MQTT message on 'zigbee2mqtt/bridge/config/permit_join' with data 'false'
zigbee2mqtt:info  2020-06-21 16:52:48: Zigbee: disabling joining new devices.
```

# It has worked before
From the past I know for sure, that reporting the second channel of at least one of the devices (`0x001fee00000001815`) has worked correctly, since I used the reporting to turn off the music when turning off the my bathroom light using the S2.

**Comment by felixstorm** [comment]
@theFork Thanks to your shipment (which arrived well yesterday), I was able to debug this. And I think I found the issue and filed a [PR](https://github.com/Koenkk/zigbee2mqtt/pull/3824) to fix it.

What you should be able to do manually in the meantime to get reporting fixed for your ubisys S2 devices:
* Stop zigbee2mqtt
* Make a backup of `data/database.db` (just in case)
* Find the last line in `data/database.db` that matches your device (search by ZigBee address, i.e. `0x001fee0000001815`) and change `"reporting":1` to `"reporting":0` (can also safely be done with multiple or all lines)
* Save `data/database.db`
* Restart zigbee2mqtt

This will make zigbee2mqtt restart the reporting setup. Since the issue that I found only affects reporting setup during device pairing, both endpoints should be successfully setup for reporting when done again later.

**Comment by theFork** [comment]
Thanks for the quick help! I can confirm, that the procedure you proposed solves the problem for already paired devices:

```
zigbee2mqtt:info  2020-06-28 16:29:13: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"state_l1":"ON","linkquality":3,"power":74,"update_available":false,"state_l2":"OFF"}'
zigbee2mqtt:info  2020-06-28 16:29:14: MQTT publish: topic 'zigbee2mqtt/0x001fee0000001815', payload '{"state_l1":"ON","linkquality":0,"power":96,"update_available":false,"state_l2":"ON"}'
```

**Comment by theFork** [comment]
The PR created by Felix works for my S2 devices. Thanks one more time!
