### ISSUE TITLE
Wiser TRV fails to configure when pairing

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#1335]
When pairing a Wiser TRV (Eberle rebrand) it throws an UNSUPPORTED_ATTRIBUTE error on the wiserDeviceInfo cluster.

```
zigbee2mqtt:error 2020-06-21 11:24:28: Failed to configure '0x086bd7fffe7ecd67', attempt 2 (Error: ConfigureReporting 0x086bd7fffe7ecd67/1 wiserDeviceInfo([{"attribute":"deviceInfo","minimumReportInterval":60,"maximumReportInterval":3600,"reportableChange":1}], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Error: Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:341:23)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:5:58))
2020-06-21T11:24:55.927Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- ZDO - srcRtgInd - {"dstaddr":21312,"relaycount":1,"relaylist":[46726]}
2020-06-21T11:24:55.980Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":25,"srcaddr":21312,"srcendpoint":1,"dstendpoint":13,"wasbroadcast":0,"linkquality":52,"securityuse":0,"timestamp":12214139,"transseqnumber":0,"len":12,"data":{"type":"Buffer","data":[1,96,1,0,102,17,25,1,48,98,135,16]}}
```

Configure request
![confreq](https://imgur.com/DGN638E.png)

Configure reponse (from device)
![confres](https://i.imgur.com/45vAYo6.png)

Capture file available if needed.

**Comment by Koenkk** [comment]
Can you try removing the following line from the `configure()`:

```js
await endpoint.configureReporting('wiserDeviceInfo', [
                {
                    attribute: 'deviceInfo',
                    minimumReportInterval: repInterval.MINUTE,
                    maximumReportInterval: repInterval.HOUR,
                    reportableChange: 1,
                },
            ]);
```

I'm not sure why this was added here in the first place, does something break when removing?

**Comment by sjorge** [comment]
Yeah it works fine with this removed. And it spams deviceInfo rather often anyway.

**Comment by Koenkk** [comment]
Good, can you make a pr?

**Comment by sjorge** [comment]
Sure, I can create one tomorrow.
