### ISSUE TITLE
OTA for OSRAM Smart+ motion throwing exceptions

### ISSUE THREAD

**Issue by Kosta-Github** [Koenkk/zigbee-herdsman-converters#1374]
I am seeing this regularly (~100 times per hour for my 20 sensors) in the logs of `z2m`:

```
zigbee2mqtt:debug 2020-07-03 23:43:51: Received Zigbee message from 'motion_floor_1', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"manufacturerCode":4174,"imageType":48,"fileVersion":503337744}' from endpoint 1 with groupID 0
zigbee2mqtt:debug 2020-07-03 23:43:51: Check if update available for '0x000d6f000fbd86a6' (Motion Sensor-A)
zigbee2mqtt:error 2020-07-03 23:43:51: Failed to call 'OTAUpdate' 'onZigbeeEvent' (AssertionError [ERR_ASSERTION]: No image available for manufacturerCode '4174' imageType '48'
    at getImageMeta (/app/node_modules/zigbee-herdsman-converters/ota/ledvance.js:15:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async isNewImageAvailable (/app/node_modules/zigbee-herdsman-converters/ota/ledvance.js:48:18)
    at async Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/ota/common.js:168:23)
    at async OTAUpdate.onZigbeeEvent (/app/lib/extension/otaUpdate.js:37:31)
    at async Controller.callExtensionMethod (/app/lib/controller.js:352:21))
```

I think https://github.com/Koenkk/zigbee-herdsman-converters/pull/1028 should have taken care of this, but it looks like not having solved it for me.

I am running `z2m` `1.14.0` and re-paired all my sensors a couple of days ago.

**Comment by Koenkk** [comment]
Removed OTA support for this device.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
