### ISSUE TITLE
Failed to configure devices SP-EUC01

### ISSUE THREAD

**Issue by mrjoun** [Koenkk/zigbee-herdsman-converters#1470]
Hi,
I have two of those devices. Failed to configure devices. The current dev, master and release tag show just the same behaviour:

```
авг 12 15:06:08 nuc npm[3909]: zigbee2mqtt:debug 2020-08-12 15:06:08: Received Zigbee message from '0x04cf8cdf3c765f93', type 'readResponse', cluster 'haElectricalMeasurement', data '{"acPowerMultiplier":1,"acPowerDivisor":10}' from endpoint 1 with groupID 0
авг 12 15:06:08 nuc npm[3909]: zigbee2mqtt:error 2020-08-12 15:06:08: Failed to configure '0x04cf8cdf3c765f93', attempt 1 (Error: ConfigureReporting 0x04cf8cdf3c765f93/1 haElectricalMeasurement([{"attribute":"activePower","minimumReportInterval":5,"maximumReportInterval":3600,"reportableChange":1}], {"timeout":10000,"disableResponse":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Status 'UNREPORTABLE_ATTRIBUTE')
авг 12 15:06:08 nuc npm[3909]:     at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:140:23)
авг 12 15:06:08 nuc npm[3909]:     at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:348:26)
авг 12 15:06:08 nuc npm[3909]:     at Generator.next (<anonymous>)
авг 12 15:06:08 nuc npm[3909]:     at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58))
```

I have usb stick cc2531 with firmware Zigbee 3.0 (plug use Zigbee 3.0).
From plug I only need to turn on and off. Power measurements don’t need. In Domoticz plug was found, but don’t control. I understand so as in the database not found "genOff"

database.db:
```
{"id":2,"type":"Router","ieeeAddr":"0x04cf8cdf3c765f93","nwkAddr":8275,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.plug.maeu01","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,2,3,4,5,6,9,1794,2820],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.plug.maeu01","manufacturerName":"LUMI","powerSource":1,"zclVersion":3,"appVersion":22,"stackVersion":2,"hwVersion":1,"dateCode":"09-10-2019"}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0014d92e2c","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0014d92e2c","endpointID":1}]},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":22,"stackVersion":2,"hwVersion":1,"dateCode":"09-10-2019","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1597233967934}
```

**Comment by Koenkk** [comment]
Should be fixed now.

Changes will be available in the latest dev branch in a few hours (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by mrjoun** [comment]
5

**Comment by mrjoun** [comment]
I tested the changes, configuration was successful. In database.db was append "haElectricalMeasurement", but "genOnOff" not found.

My file database.db
```
{"id":7,"type":"Router","ieeeAddr":"0x04cf8cdf3c765f93","nwkAddr":29150,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.plug.maeu01","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,2,3,4,5,6,9,1794,2820],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.plug.maeu01","manufacturerName":"LUMI","powerSource":1,"zclVersion":3,"appVersion":22,"stackVersion":2,"hwVersion":1,"dateCode":"09-10-2019"}},"haElectricalMeasurement":{"attributes":{"acPowerMultiplier":1,"acPowerDivisor":10}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0014d92e2c","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b0014d92e2c","endpointID":1}]},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":22,"stackVersion":2,"hwVersion":1,"dateCode":"09-10-2019","zclVersion":3,"interviewCompleted":true,"meta":{"configured":3},"lastSeen":1597347602837}
```

File from #1050 
```
{"id":32,"type":"Router","ieeeAddr":"0x04cf8cdf3c79c957","nwkAddr":10343,"manufId":4447,"manufName":"LUMI","powerSource":"Mains (single phase)","modelId":"lumi.plug.maeu01","epList":[1,242],"endpoints":{"1":{"profId":260,"epId":1,"devId":81,"inClusterList":[0,2,3,4,5,6,9,1794,2820],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"lumi.plug.maeu01","manufacturerName":"LUMI","powerSource":1,"zclVersion":3,"appVersion":22,"stackVersion":2,"hwVersion":1,"dateCode":"09-10-2019"}},"haElectricalMeasurement":{"attributes":{"activePower":31,"acPowerMultiplier":1,"acPowerDivisor":10}},"genOnOff":{"attributes":{"onOff":1}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b00194a1805","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00124b00194a1805","endpointID":1}]},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":22,"stackVersion":2,"hwVersion":1,"dateCode":"09-10-2019","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1594171984357}
```
Comparing the files, you can see that I do not have:
 

1. "haElectricalMeasurement":{"attributes":{"activePower":31"
2.  " ,"genOnOff":{"attributes":{"onOff":1}}}"

**Comment by Koenkk** [comment]
You will get this attribute once you toggle the switch from the switch itself with the button on it.
