### ISSUE TITLE
Add Support For SMARTCODE_DEADBOLT_5

### ISSUE THREAD

**Issue by zombielinux** [Koenkk/zigbee-herdsman-converters#1483]
I have this device nearly functional.
```
    {
        zigbeeModel: ['SMARTCODE_DEADBOLT_5'],
        model: '99100-045',
        vendor: 'Kwikset',
        description: '910 SmartCode traditional electronic deadbolt',
        supports: 'lock/unlock, battery, temperature, ignore_poll_ctrl, pin code programming',
        fromZigbee: [fz.lock, fz.lock_operation_event, fz.battery, fz.lock_programming_event, fz.lock_pin_code_rep],
        toZigbee: [tz.generic_lock, , tz.pincode_lock],
        meta: {configureKey: 4, pinCodeCount: 30, options: {disableDefaultResponse: true}},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint = device.getEndpoint(2);
            console.log(endpoint.clusters);
            await bind(endpoint, coordinatorEndpoint, ['closuresDoorLock', 'genPowerCfg']);
            await configureReporting.lockState(endpoint);
            await configureReporting.batteryPercentageRemaining(endpoint);
        },
    },
```

database.db entry
```
{"id":2,"type":"EndDevice","ieeeAddr":"0x002446fffd0070eb","nwkAddr":28674,"manufId":4242,"manufName":"Kwikset","powerSource":"Battery","modelId":"SMARTCODE_DEADBOLT_5","epList":[2],"endpoints":{"2":{"profId":260,"epId":2,"devId":10,"inClusterList":[0,1,3,4,5,9,32,257,1026,2821,64957],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"SMARTCODE_DEADBOLT_5","manufacturerName":"Kwikset","powerSource":3,"zclVersion":1,"appVersion":28,"stackVersion":2,"hwVersion":3}}},"binds":[]}},"appVersion":28,"stackVersion":2,"hwVersion":3,"zclVersion":1,"interviewCompleted":true,"meta":{},"lastSeen":1597683096551}
```

Comes through with the error, and doesn't complete pairing. Any assistance would be awesome. 

```
zigbee2mqtt             | Zigbee2MQTT:error 2020-08-18 11:25:02: Failed to configure '0x002446fffd0070eb', attempt 1 (TypeError: Cannot read property 'message' of undefined
zigbee2mqtt             |     at Endpoint.<anonymous> (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:266:57)
zigbee2mqtt             |     at Generator.throw (<anonymous>)
zigbee2mqtt             |     at rejected (/app/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:25:65))
```

**Comment by Koenkk** [comment]
Try to figure out why the configure fails be adding lines of `configure()` one by one. 

So start with:
```js
const endpoint = device.getEndpoint(2);
```

next

```
            const endpoint = device.getEndpoint(2);
            console.log(endpoint.clusters);
            await bind(endpoint, coordinatorEndpoint, ['closuresDoorLock', 'genPowerCfg']);
```

etc.

You can force a configure through https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html#zigbee2mqttbridgeconfigure
