### ISSUE TITLE
Adding newly developed device to Z2M?

### ISSUE THREAD

**Issue by qvntra** [Koenkk/zigbee-herdsman-converters#1617]
Hello;

Big supporter (sponsor @Koenkk) and endorser of the Z2M project.

We have developed a new type of sensor, ballistocardiography, that leverages ZigBee to transmit payloads via Meter Identification cluster in ZCL. We are very close to having our sensor communicate with Z2M coordinator but experience the following error:

**log.txt**
```
> zigbee2mqtt@1.14.4 start /opt/zigbee2mqtt
> node index.js

Zigbee2MQTT:info  2020-10-01 00:45:15: Logging to console and directory: '/opt/zigbee2mqtt/data/log/2020-10-01.00-45-14' filename: log.txt
Zigbee2MQTT:debug 2020-10-01 00:45:15: Removing old log directory '/opt/zigbee2mqtt/data/log/2020-10-01.00-04-44'
Zigbee2MQTT:debug 2020-10-01 00:45:15: Loaded state from file /opt/zigbee2mqtt/data/state.json
Zigbee2MQTT:info  2020-10-01 00:45:15: Starting Zigbee2MQTT version 1.14.4 (commit #0cd4607)
Zigbee2MQTT:info  2020-10-01 00:45:15: Starting zigbee-herdsman...
Zigbee2MQTT:debug 2020-10-01 00:45:15: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null},"backupPath":"/opt/zigbee2mqtt/data/coordinator_backup.json","databaseBackupPath":"/opt/zigbee2mqtt/data/database.db.backup","databasePath":"/opt/zigbee2mqtt/data/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyACM0"}}'
Zigbee2MQTT:info  2020-10-01 00:45:20: zigbee-herdsman started
Zigbee2MQTT:info  2020-10-01 00:45:20: Coordinator firmware version: '{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20200417,"transportrev":2},"type":"zStack3x0"}'
Zigbee2MQTT:debug 2020-10-01 00:45:20: Zigbee network parameters: {"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754}
Zigbee2MQTT:info  2020-10-01 00:45:20: Currently 2 devices are joined:
Zigbee2MQTT:info  2020-10-01 00:45:20: 0x0080e1250007f32f (0x0080e1250007f32f): STM32WB- - simplixio undefined (Router)
Zigbee2MQTT:info  2020-10-01 00:45:20: 0x0015bc001a018b30 (0x0015bc001a018b30): Not supported (EndDevice)
Zigbee2MQTT:warn  2020-10-01 00:45:20: `permit_join` set to  `true` in configuration.yaml.
Zigbee2MQTT:warn  2020-10-01 00:45:20: Allowing new devices to join.
Zigbee2MQTT:warn  2020-10-01 00:45:20: Set `permit_join` to `false` once you joined all devices.
Zigbee2MQTT:info  2020-10-01 00:45:20: Zigbee: allowing new devices to join.
Zigbee2MQTT:info  2020-10-01 00:45:20: Configuring '0x0080e1250007f32f'
####
endpoint start... Endpoint {
  ID: 17,
  profileID: 260,
  deviceID: 1288,
  inputClusters: [ 0, 2817 ],
  outputClusters: [],
  deviceNetworkAddress: 27525,
  deviceIeeeAddress: '0x0080e1250007f32f',
  clusters: { genBasic: { attributes: [Object] } },
  _binds:
   [ { cluster: 2817,
       type: 'endpoint',
       deviceIeeeAddress: '0x00124b001caaab86',
       endpointID: 1 } ] } 
  
  CoordinateEndpoint {
  ID: 1,
  profileID: 260,
  deviceID: 5,
  inputClusters: [],
  outputClusters: [],
  deviceNetworkAddress: 0,
  deviceIeeeAddress: '0x00124b001caaab86',
  clusters: {},
  _binds: [] }
Zigbee2MQTT:info  2020-10-01 00:45:20: Connecting to MQTT server at mqtt://localhost
Zigbee2MQTT:info  2020-10-01 00:45:21: Connected to MQTT server
Zigbee2MQTT:info  2020-10-01 00:45:21: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
Zigbee2MQTT:info  2020-10-01 00:45:21: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"commit":"0cd4607","coordinator":{"meta":{"maintrel":1,"majorrel":2,"minorrel":7,"product":1,"revision":20200417,"transportrev":2},"type":"zStack3x0"},"log_level":"debug","network":{"channel":11,"extendedPanID":"0xdddddddddddddddd","panID":6754},"permit_join":true,"version":"1.14.4"}'
Zigbee2MQTT:debug 2020-10-01 00:45:22: Device '0x0080e1250007f32f' announced itself
Zigbee2MQTT:info  2020-10-01 00:45:22: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"message":"announce","meta":{"friendly_name":"0x0080e1250007f32f"},"type":"device_announced"}'
Zigbee2MQTT:error 2020-10-01 00:45:30: Failed to configure '0x0080e1250007f32f', attempt 1 (Error: Bind 0x0080e1250007f32f/17 haMeterIdentification from '0x00124b001caaab86/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout.waiter.timer.setTimeout [as _onTimeout] (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10))
```

### Error context:
**database.db**
`{"id":2,"type":"Router","ieeeAddr":"0x0080e1250007f32f","nwkAddr":27525,"manufId":4311,"manufName":"STMicroelectronics","powerSource":"DC Source","modelId":"STM32WB","epList":[17,242],"endpoints":{"17":{"profId":260,"epId":17,"devId":1288,"inClusterList":[0,2817],"outClusterList":[],"clusters":{"genBasic":{"attributes":{"modelId":"STM32WB","manufacturerName":"STMicroelectronics","powerSource":4,"zclVersion":2,"appVersion":160,"stackVersion":160,"hwVersion":21,"dateCode":"20200526","swBuildId":"V1.8"}}},"binds":[{"cluster":2817,"type":"endpoint","deviceIeeeAddress":"0x00124b001caaab86","endpointID":1}]},"242":{"profId":41440,"epId":242,"devId":97,"inClusterList":[],"outClusterList":[33],"clusters":{},"binds":[]}},"appVersion":160,"stackVersion":160,"hwVersion":21,"dateCode":"20200526","swBuildId":"V1.8","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1601505922242}`

**devices.js**
```
// ST Interface
   {
   	zigbeeModel: ['STM32WB'],
   	model: 'STM32WB-',
   	vendor: 'simplixio',
   	descreiption: 'ST interface',
    	supports: 'BSG forwarding',
    	fromZigbee: [fz.identify, fz.st_interface],
    	toZigbee: [],
   	meta: {configureKey: 1},
    	configure: async (device, coordinatorEndpoint) => {
    		console.log('####')
    		const endpoint = device.getEndpoint(17);
    		console.log('endpoint start...', endpoint,coordinatorEndpoint)
    		
    		await bind(endpoint, coordinatorEndpoint, ['haMeterIdentification']);
    		console.log('####')
//    		await configureReporting.st_interface(endpoint);
    		await configureReporting.powerThreshold(endpoint);
    		console.log('endpoint endpoint', endpoint)
     	},
    
    },
```

**fromZigbee.js**
```
    st_interface: {
    	cluster: 'haMeterIdentification',
    	type: ['attributeReport','readResponse'],
    	convert: (model, msg, publish, options, meta) => {
    	
    		const result = {};
    		
    		console.log('ST Interface MSG RX:', msg.data.toString())
    		
    		if (msg.data.hasOwnProperty('availablePower')) {
    			result.availablePower = msg.data['availablePower'];
    		}
    		
    		if (msg.data.hasOwnProperty('powerThreshold')) {
    			result.powerThreshold = msg.data['powerThreshold'];
    		}
    		
    		return result;
    		
    	},
    },
   
};
```

Can anyone offer a bit of feedback here? Perhaps I've been staring at a screen for too long but I am unable to figure out the issue at this time.

Thank you for any consideration!

Thyge

**Comment by Koenkk** [comment]
It seems your device does not respond to the bind request done at `await bind(endpoint, coordinatorEndpoint, ['haMeterIdentification']);`. I recommend sniffing the traffic to debug this further (https://www.zigbee2mqtt.io/how_tos/how_to_sniff_zigbee_traffic.html)

**Comment by qvntra** [comment]
[sniff_data.pcapng.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/5431118/sniff_data.pcapng.txt)
@Koenkk

We are continuing our debugging progress.
Does the attached "sniff_data.pcapng" file reflect your expectations of a normal ZigBee communication sequence between coordinator and device?
Thank you for any consideration. Will tip significantly via PayPal if we are able to properly pair device with Z2M Coordinator.

**Comment by qvntra** [comment]
Working with @kirovilya who has explained to us that we may not even need to use "bind". Working through new fromZigbee.js + devices.js configurations and will report back.
