### ISSUE TITLE
Develco SPLZB-132 power plug support (probably with metering)

### ISSUE THREAD

**Issue by NameLessJedi** [Koenkk/zigbee-herdsman-converters#1681]
Hi,
I’ve got this Develco power plug with on/off button. I’ve went the way described in https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html and added it to devices.js:
```javascript
    {
                zigbeeModel: ['SPLZB-132'],
                model: 'SPLZB-132',
                vendor: 'Develco',
                description: 'Power plug',
                fromZigbee: [fz.on_off],
                toZigbee: [tz.on_off],
    },
```
In zigbee2mqtt logs I can see when the button is pressed:
```
    Oct 10 23:34:39 rhenvar npm[1137549]: Zigbee2MQTT:debug 2020-10-10 23:34:39: Received Zigbee message from ‘0x0015bc002f00306b’, type ‘attributeReport’, cluster ‘genOnOff’, data ‘{“onOff”:0}’ from endpoint 2 with groupID 0
    Oct 10 23:34:48 rhenvar npm[1137549]: Zigbee2MQTT:debug 2020-10-10 23:34:48: Received Zigbee message from ‘0x0015bc002f00306b’, type ‘attributeReport’, cluster ‘genOnOff’, data ‘{“onOff”:1}’ from endpoint 2 with groupID 0
    Oct 10 23:35:16 rhenvar npm[1137549]: Zigbee2MQTT:debug 2020-10-10 23:35:16: Received Zigbee message from ‘0x0015bc002f00306b’, type ‘attributeReport’, cluster ‘genOnOff’, data ‘{“onOff”:0}’ from endpoint 2 with groupID 0
    Oct 10 23:35:19 rhenvar npm[1137549]: Zigbee2MQTT:debug 2020-10-10 23:35:19: Received Zigbee message from ‘0x0015bc002f00306b’, type ‘attributeReport’, cluster ‘genOnOff’, data ‘{“onOff”:1}’ from endpoint 2 with groupID 0
```
But when I try to change state using built-in frontend of Z2M I see this:
```
    Oct 10 23:35:46 rhenvar npm[1137549]: Zigbee2MQTT:error 2020-10-10 23:35:46: Publish ‘set’ ‘state’ to ‘0x0015bc002f00306b’ failed: ‘Error: Command 0x0015bc002f00306b/1 genOnOff.off({}, {“timeout”:10000,“disableResponse”:false,“disableRecovery”:false,“disableDefaultResponse”:false,“direction”:0,“srcEndpoint”:null,“reservedBits”:0,“manufacturerCode”:null,“transactionSequenceNumber”:null}) failed (Timeout - 23378 - 1 - 3 - 6 - 11 after 10000ms)’
    Oct 10 23:35:46 rhenvar npm[1137549]: Zigbee2MQTT:debug 2020-10-10 23:35:46: Error: Command 0x0015bc002f00306b/1 genOnOff.off({}, {“timeout”:10000,“disableResponse”:false,“disableRecovery”:false,“disableDefaultResponse”:false,“direction”:0,“srcEndpoint”:null,“reservedBits”:0,“manufacturerCode”:null,“transactionSequenceNumber”:null}) failed (Timeout - 23378 - 1 - 3 - 6 - 11 after 10000ms)
    Oct 10 23:35:46 rhenvar npm[1137549]: at Timeout._onTimeout (/home/hassio/zigbee2mqtt/node_modules/zigbee-herdsman/dist/utils/waitress.js:46:35)
    Oct 10 23:35:46 rhenvar npm[1137549]: at listOnTimeout (internal/timers.js:554:17)
    Oct 10 23:35:46 rhenvar npm[1137549]: at processTimers (internal/timers.js:497:7)
    Oct 10 23:35:46 rhenvar npm[1137549]: Zigbee2MQTT:info 2020-10-10 23:35:46: MQTT publish: topic ‘z2m/bridge/log’, payload ‘{“message”:“Publish ‘set’ ‘state’ to ‘0x0015bc002f00306b’ failed: ‘Error: Command 0x0015bc002f00306b/1 genOnOff.off({}, {“timeout”:10000,“disableResponse”:false,“disableRecovery”:false,“disableDefaultResponse”:false,“direction”:0,“srcEndpoint”:null,“reservedBits”:0,“manufacturerCode”:null,“transactionSequenceNumber”:null}) failed (Timeout - 23378 - 1 - 3 - 6 - 11 after 10000ms)’”,“meta”:{“friendly_name”:“0x0015bc002f00306b”},“type”:“zigbee_publish_error”}’
```
I’ve tried to change devices.js entry to:
```javascript
    {
    zigbeeModel: [‘SPLZB-132’],
    model: ‘SPLZB-132’,
    vendor: ‘Develco’,
    description: ‘Power plug’,
    fromZigbee: [fz.on_off],
    toZigbee: [tz.on_off],
    meta: {configureKey: 1},
    configure: async (device, coordinatorEndpoint) => {
    const endpoint = device.getEndpoint(2);
    await bind(endpoint, coordinatorEndpoint, [‘genOnOff’]);
    await configureReporting.onOff(endpoint);
    },
```
But the result is still the same
[Here is how the about page of that plug](https://aws1.discourse-cdn.com/free1/uploads/zigbee2mqtt/original/1X/d81284ccb8484017b83e686112684a52f9e5f547.png)

Can anyone help me with this?
TIA,

**Comment by Koenkk** [comment]
Can you share the `data/database.db` entry of this device?

**Comment by NameLessJedi** [comment]
```javascript
{
    "id": 8,
    "type": "Router",
    "ieeeAddr": "0x0015bc002f00306b",
    "nwkAddr": 7988,
    "manufId": 4117,
    "manufName": "Develco Products A/S",
    "powerSource": "Mains (single phase)",
    "modelId": "SPLZB-132",
    "epList": [
        1,
        2
    ],
    "endpoints": {
        "1": {
            "profId": 49353,
            "epId": 1,
            "devId": 1,
            "inClusterList": [
                5,
                6
            ],
            "outClusterList": [],
            "clusters": {},
            "binds": [
                {
                    "cluster": 6,
                    "type": "endpoint",
                    "deviceIeeeAddress": "0x00124b0014d47beb",
                    "endpointID": 1
                }
            ],
            "meta": {}
        },
        "2": {
            "profId": 260,
            "epId": 2,
            "devId": 81,
            "inClusterList": [
                0,
                1794,
                3,
                9,
                2820,
                6,
                4,
                5,
                2
            ],
            "outClusterList": [
                0,
                25,
                10,
                3,
                1030
            ],
            "clusters": {
                "genBasic": {
                    "attributes": {
                        "modelId": "SPLZB-132",
                        "manufacturerName": "Develco Products A/S",
                        "powerSource": 1,
                        "zclVersion": 1,
                        "dateCode": "2017-03-28 01:22"
                    }
                }
            },
            "binds": [],
            "meta": {}
        }
    },
    "dateCode": "2017-03-28 01:22",
    "zclVersion": 1,
    "interviewCompleted": true,
    "meta": {
        "configured": 1
    },
    "lastSeen": 1603056221837
}
```
One thing tho I originally posted above on support forum couple of days ago. OP contains info from release version 1.15. Since then I switched over to dev branch so database.db entry was created by dev branch (probably I just didn't check this). Also I've added this:
```javascript
{
        zigbeeModel: ['SPLZB-132'],
        model: 'SPLZB-132',
        vendor: 'Develco',
        description: 'Power plug',
        fromZigbee: [fz.on_off],
        toZigbee: [tz.on_off],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint) => {
            const endpoint1 = device.getEndpoint(1)
            const endpoint2 = device.getEndpoint(2);
            await bind(endpoint1, coordinatorEndpoint, ['genOnOff']);
            await configureReporting.onOff(endpoint2);
        },
        exposes: [exposes.switch()],
}
```
Just tell me how to start from scratch and I'll gladly obey :smile:

**Comment by Koenkk** [comment]
Should work with (including power measurements)

```js
{
    zigbeeModel: ['SPLZB-132'],
    model: 'SPLZB-132',
    vendor: 'Develco',
    description: 'Power plug',
    fromZigbee: [fz.on_off, fz.electrical_measurement_power, fz.metering_power],
    toZigbee: [tz.on_off],
    // exposes: [e.switch(), e.power(), e.current(), e.voltage(), e.energy()],
    meta: {configureKey: 2},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(2);
        await bind(endpoint, coordinatorEndpoint, ['genOnOff', 'haElectricalMeasurement', 'seMetering']);
        await configureReporting.onOff(endpoint);
        await readEletricalMeasurementPowerConverterAttributes(endpoint);
        await configureReporting.activePower(endpoint);
        await configureReporting.rmsCurrent(endpoint);
        await configureReporting.rmsVoltage(endpoint);
        await readMeteringPowerConverterAttributes(endpoint);
        await configureReporting.currentSummDelivered(endpoint);
    },
    endpoint: (device) => {
        return {default: 2};
    },
},
```

**Comment by NameLessJedi** [comment]
Yes! Works perfectly including power measurements!
Thx
