### ISSUE TITLE
Support for Tuya led controller

### ISSUE THREAD

**Issue by barrymossel** [Koenkk/zigbee-herdsman-converters#2158]
Paired a Tuya led strip controller (the single color one from https://nl.aliexpress.com/item/1005001865233095.html). ModelID: TS0501B and ManufacturerName: _TZ3000_4whigl8i. I tried adding zigbee_shepherd_devices: true in the HA add-on (and putting latest devices.js in data folder). Getting the following errors:

```
[services.d] done.
./run.sh: line 17: [Info] Configuration backup found in /share/zigbee2mqtt/.configuration.yaml.bk. Skipping config backup.: No such file or directory
[Info] Searching for custom devices file in zigbee2mqtt data path...
[Info] Socat is DISABLED and not started
2021-01-26T15:45:10: PM2 log: Launching in no daemon mode
2021-01-26T15:45:10: PM2 log: App [npm:0] starting in -fork mode-
2021-01-26T15:45:10: PM2 log: App [npm:0] online
> zigbee2mqtt@1.17.0 start /zigbee2mqtt-1.17.0
> node index.js
internal/modules/cjs/loader.js:968
  throw err;
  ^
Error: Cannot find module './lib/light'
Require stack:
- /zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman-converters/devices.js
- /zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman-converters/index.js
- /zigbee2mqtt-1.17.0/lib/zigbee.js
- /zigbee2mqtt-1.17.0/lib/controller.js
- /zigbee2mqtt-1.17.0/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman-converters/devices.js:44:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman-converters/devices.js',
    '/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman-converters/index.js',
    '/zigbee2mqtt-1.17.0/lib/zigbee.js',
    '/zigbee2mqtt-1.17.0/lib/controller.js',
    '/zigbee2mqtt-1.17.0/index.js'
  ]
}
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR!
 zigbee2mqtt@1.17.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-26T14_45_17_257Z-debug.log
2021-01-26T15:45:20: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2021-01-26T15:45:20: PM2 log: App [npm:0] starting in -fork mode-
2021-01-26T15:45:20: PM2 log: App [npm:0] online
> zigbee2mqtt@1.17.0 start /zigbee2mqtt-1.17.0
> node index.js
internal/modules/cjs/loader.js:968
  throw err;
  ^
Error: Cannot find module './lib/light'
Require stack:
- /zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman-converters/devices.js
- /zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman-converters/index.js
- /zigbee2mqtt-1.17.0/lib/zigbee.js
- /zigbee2mqtt-1.17.0/lib/controller.js
- /zigbee2mqtt-1.17.0/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman-converters/devices.js:44:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman-converters/devices.js',
    '/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman-converters/index.js',
    '/zigbee2mqtt-1.17.0/lib/zigbee.js',
    '/zigbee2mqtt-1.17.0/lib/controller.js',
    '/zigbee2mqtt-1.17.0/index.js'
  ]
}
npm
 ERR! code ELIFECYCLE
npm ERR! errno 1
npm 
ERR! zigbee2mqtt@1.17.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm
 ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-26T14_45_26_962Z-debug.log
2021-01-26T15:45:27: PM2 log: App [npm:0] exited with code [1] via signal [SIGINT]
2021-01-26T15:45:27: PM2 log: App [npm:0] starting in -fork mode-
2021-01-26T15:45:27: PM2 log: App [npm:0] online
> zigbee2mqtt@1.17.0 start /zigbee2mqtt-1.17.0
> node index.js

```

Don't know how to proceed to add this device now.

**Comment by barrymossel** [comment]
BTW, looks exactly the same as: https://www.zigbee2mqtt.io/devices/YSR-MINI-01_dimmer.html

**Comment by barrymossel** [comment]
A mixed up v14.0.30 and v14.0.3.
