### ISSUE TITLE
Siterwell GS361A-H04, system_mode and Home Assistant

### ISSUE THREAD

**Issue by creckord** [Koenkk/zigbee-herdsman-converters#2170]
Hi there,

I'm having some trouble with the support for the Siterwell GS361A-H04 when it comes to its `system_mode`, both in zigbee2mqtt itself, and when used through Home Assistant. 

I tried to grok the mappings for the device, but since I'm fairly new to both zigbee2mqtt and HA, and there have been a bunch of changes and generalizations from the initial GS361 support to Tuya thermostats, it's a bit hard for me to judge how things are supposed to work with those device mappings in the first place. So I'll just list my observations and maybe we can split off separate issues from there:

### 1. Available `system_modes`

The initial contribution for the device had just three system modes, corresponding to what the device exposes through its display and buttons: `off`, `auto` and `manual`. Since then, the list has shifted from GS361 modes to more general Tuya modes and gained four additional modes: `comfort`, `eco`, `boost`, `complex`.

I'm not sure if those additional modes are supposed to be supported by the GS361, but they don't really work with mine (which are white-labeled re!volt models, so maybe they did something to it):
* `comfort`: crashes the device and puts it into F1-1 setup state
* `eco`, `boost`, `complex`: Those all behave identically - they are accepted and acknowledged when set and start off with whatever `current_heating_setpoint` was set before switching into this mode. On the devices display they present with the mode indicators all off. When changing the `current_heating_setpoint`, it is retained until the mode is switched to something else, but when switching back again, the value is lost.

The mode-specific configurations (`eco_temperature`, `comfort_temperature`, `boost_time`) don't seem to have any effect.

### 2. `system_mode`, `preset` and state attributes

I noticed that while I can set both `system_mode` and `preset`, only the `preset` attribute shows up in the device state. This is particularly bothersome because the HA discovery template uses the `system_mode` to read the current state. So I guess either the `system_mode` is missing from the state, or the template should refer to the `preset` instead.

The full json for my devices looks like this:
```
{
  "away_mode": "OFF",
  "battery": 77,
  "child_lock": "UNLOCKED",
  "current_heating_setpoint": 19,
  "linkquality": 30,
  "local_temperature": 19.2,
  "preset": "manual",
  "valve_detection": "ON",
  "window_detection": "ON"
}
```

### 3. `manual` mode and Home Assistant

One last issue with setting the `system_mode` through Home Assistant is that in the device config (`tuya.thermostatSystemModes`) the manual heating mode is called `manual`, while HA insists on it being `heat`.

This leads to `Error: TRV system mode heat is not recognized.` in zigbee2mqtt.

As far as I can see, it would be possible to map the name in the zigbee2mqtt->HA direction using the `mode_state_template`, but not the other way round. Since `tuya.thermostatSystemModes` is the only one of the bunch that uses `manual` instead of `heat` and the GS361 is the only device referring to `tuya.thermostatSystemModes`, maybe it should be renamed to `heat` as well?

Interestingly enough, in the `devices` list, the device description for `system_mode` lists `off`, `auto`, `heat` as supported values. This is hardcoded in the `exposes` config instead of using the `tuya.thermostatSystemModes` list.

As I said, my devices are all white-labeled Revolt thermostats, so I'm not which parts of this come back to them having messed with the firmware, and which are general problems with the GS361 definition. 

I'm happy to dig into the setup further and provide merge requests, but would need to know first which way to go with any potential fixes.

**Comment by Koenkk** [comment]
1. The supported available modes are: 'off', 'auto', 'heat' (see point 3 off https://www.zigbee2mqtt.io/devices/GS361A-H04.html#climate). There may be other modes in thermostatSystemModes, but these are not listed as supported.
2. This is indeed problematic. Can you provide the debug log when setting the auto and heat system mode?
3. Home Assistant doesn't allow manual to be a mode, so therefore presets are used. Can you add to the expose in `devices.js` `.withPreset(['manual'])`

To enable debug logging set in `configuration.yaml`:
```yaml
advanced:
  log_level: debug
```

**Comment by creckord** [comment]
1./3. I'm still a bit confused about the `system_mode` vs `preset` thing. The 'heat' system_mode is listed as supported in the doc you linked to, but doesn't work, because it is missing from thermostatSystemModes. There's a 'manual' mode there in its place. Trying to set the 'heat' mode via e.g. 'zigbee2mqtt/thermostat-buero-links/set/system_mode' results in
```
Error: TRV system mode heat is not recognized.
    at Object.convertSet (/zigbee2mqtt-1.17.0/node_modules/zigbee-herdsman-converters/converters/toZigbee.js:3038:23)
    at EntityPublish.onMQTTMessage (/zigbee2mqtt-1.17.0/lib/extension/publish.js:224:52)
    at Controller.callExtensionMethod (/zigbee2mqtt-1.17.0/lib/controller.js:381:44)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
The Home Assistant discovery configures the 'system_mode' endpoint as well, so I get this error when I try to activate the 'heat' mode in HA as well: `"mode_command_topic": "zigbee2mqtt/thermostat-wohnzimmer/set/system_mode"`. 

It looks to me like 'manual' in thermostatSystemModes should be changed to 'heat' (as far as I can see the GS361 is the only one using that list anyway)?

The presets aren't currently exposed at all. So if I add them, shouldn't I add all three ('away', 'manual', 'schedule')?

**Comment by creckord** [comment]
2. Here are the logs:

```
# system_mode off to manual (off at 5°C, manual at 19°C)
Zigbee2MQTT:debug 2021-01-28 20:30:21: Received MQTT message on 'zigbee2mqtt/thermostat-buero-links/set/system_mode' with data 'manual'
Zigbee2MQTT:debug 2021-01-28 20:30:21: Publishing 'set' 'system_mode' to 'thermostat-buero-links'
Zigbee2MQTT:debug 2021-01-28 20:30:24: Received Zigbee message from 'thermostat-buero-links', type 'commandSetDataResponse', cluster
'manuSpecificTuya', data '{"data":{"data":[2],"type":"Buffer"},"datatype":4,"dp":4,"fn":0,"status":0,"transid":59}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-01-28 20:30:24: MQTT publish: topic 'zigbee2mqtt/thermostat-buero-links', payload '{"away_mode":"OFF","battery":75,"child_lock":"UNLOCKED","current_heating_setpoint":5,"linkquality":30,"local_temperature":19.8,"preset":"manual","valve_detection":"ON","window_detection":"ON"}'
Zigbee2MQTT:debug 2021-01-28 20:30:24: Received Zigbee message from 'thermostat-buero-links', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[2],"type":"Buffer"},"datatype":4,"dp":4,"fn":0,"status":1,"transid":15}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-01-28 20:30:24: MQTT publish: topic 'zigbee2mqtt/thermostat-buero-links', payload '{"away_mode":"OFF","battery":75,"child_lock":"UNLOCKED","current_heating_setpoint":5,"linkquality":27,"local_temperature":19.8,"preset":"manual","valve_detection":"ON","window_detection":"ON"}'
Zigbee2MQTT:debug 2021-01-28 20:30:25: Received Zigbee message from 'thermostat-buero-links', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,190],"type":"Buffer"},"datatype":2,"dp":2,"fn":0,"status":1,"transid":16}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-01-28 20:30:25: MQTT publish: topic 'zigbee2mqtt/thermostat-buero-links', payload '{"away_mode":"OFF","battery":75,"child_lock":"UNLOCKED","current_heating_setpoint":19,"linkquality":30,"local_temperature":19.8,"preset":"manual","valve_detection":"ON","window_detection":"ON"}'

# system mode manual to auto (auto at 22°C)
Zigbee2MQTT:debug 2021-01-28 20:34:18: Received MQTT message on 'zigbee2mqtt/thermostat-buero-links/set/system_mode' with data 'auto'
Zigbee2MQTT:debug 2021-01-28 20:34:18: Publishing 'set' 'system_mode' to 'thermostat-buero-links'
Zigbee2MQTT:debug 2021-01-28 20:34:21: Received Zigbee message from 'thermostat-buero-links', type 'commandSetDataResponse', cluster
'manuSpecificTuya', data '{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":4,"fn":0,"status":0,"transid":62}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-01-28 20:34:21: MQTT publish: topic 'zigbee2mqtt/thermostat-buero-links', payload '{"away_mode":"OFF","battery":75,"child_lock":"UNLOCKED","current_heating_setpoint":19,"linkquality":27,"local_temperature":19.8,"preset":"schedule","valve_detection":"ON","window_detection":"ON"}'
Zigbee2MQTT:debug 2021-01-28 20:34:22: Received Zigbee message from 'thermostat-buero-links', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":4,"fn":0,"status":1,"transid":21}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-01-28 20:34:22: MQTT publish: topic 'zigbee2mqtt/thermostat-buero-links', payload '{"away_mode":"OFF","battery":75,"child_lock":"UNLOCKED","current_heating_setpoint":19,"linkquality":27,"local_temperature":19.8,"preset":"schedule","valve_detection":"ON","window_detection":"ON"}'
Zigbee2MQTT:debug 2021-01-28 20:34:22: Received Zigbee message from 'thermostat-buero-links', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,220],"type":"Buffer"},"datatype":2,"dp":2,"fn":0,"status":1,"transid":22}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-01-28 20:34:22: MQTT publish: topic 'zigbee2mqtt/thermostat-buero-links', payload '{"away_mode":"OFF","battery":75,"child_lock":"UNLOCKED","current_heating_setpoint":22,"linkquality":30,"local_temperature":19.8,"preset":"schedule","valve_detection":"ON","window_detection":"ON"}'

# system mode off to auto (auto at 22°C)
Zigbee2MQTT:debug 2021-01-28 20:36:59: Received MQTT message on 'zigbee2mqtt/thermostat-buero-links/set/system_mode' with data 'auto'
Zigbee2MQTT:debug 2021-01-28 20:36:59: Publishing 'set' 'system_mode' to 'thermostat-buero-links'
Zigbee2MQTT:debug 2021-01-28 20:37:04: Received Zigbee message from 'thermostat-buero-links', type 'commandSetDataResponse', cluster
'manuSpecificTuya', data '{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":4,"fn":0,"status":0,"transid":64}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-01-28 20:37:04: MQTT publish: topic 'zigbee2mqtt/thermostat-buero-links', payload '{"away_mode":"OFF","battery":75,"child_lock":"UNLOCKED","current_heating_setpoint":5,"linkquality":27,"local_temperature":19.8,"preset":"schedule","valve_detection":"ON","window_detection":"ON"}'
Zigbee2MQTT:debug 2021-01-28 20:37:04: Received Zigbee message from 'thermostat-buero-links', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[1],"type":"Buffer"},"datatype":4,"dp":4,"fn":0,"status":1,"transid":25}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-01-28 20:37:04: MQTT publish: topic 'zigbee2mqtt/thermostat-buero-links', payload '{"away_mode":"OFF","battery":75,"child_lock":"UNLOCKED","current_heating_setpoint":5,"linkquality":27,"local_temperature":19.8,"preset":"schedule","valve_detection":"ON","window_detection":"ON"}'
Zigbee2MQTT:debug 2021-01-28 20:37:05: Received Zigbee message from 'thermostat-buero-links', type 'commandGetData', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,220],"type":"Buffer"},"datatype":2,"dp":2,"fn":0,"status":1,"transid":26}' from endpoint 1 with groupID 0
Zigbee2MQTT:info  2021-01-28 20:37:05: MQTT publish: topic 'zigbee2mqtt/thermostat-buero-links', payload '{"away_mode":"OFF","battery":75,"child_lock":"UNLOCKED","current_heating_setpoint":22,"linkquality":30,"local_temperature":19.8,"preset":"schedule","valve_detection":"ON","window_detection":"ON"}'
```

**Comment by creckord** [comment]
1. One more thing: Since only those three modes should be supported, wouldn't it make sense to restrict the available modes in the device meta to just those? Currently, it's the whole thermostatSystemModes list, with the aforementioned effects when trying to set the unsupported modes.

**Comment by creckord** [comment]
> When sending manual, what mode is the actual thermostat in, heat or manual?
The device only has three modes, referred to in the manual as "Automatic mode, Manual mode and Anti-freezing mode" - so I guess that would make it 'manual' then.

**Comment by Koenkk** [comment]
@drzony since you did some TuYa thermostat refactorings in the past, could you maybe help with this?

**Comment by drzony** [comment]
There was a discussion in the great TuYa thread about this (starting about here https://github.com/Koenkk/zigbee2mqtt/issues/3821#issuecomment-756757074).
To sum up HA approach is not very friendly for TRVs. 
So one option is what I did in Saswell - `heat == what preset says (none or away)`, `auto == schedule` (since Saswell has no presets other that `away` which is special for HA)
The second option is - `heat == (preset = manual)`, `auto == what preset says`
HA docs are here https://developers.home-assistant.io/docs/core/entity/climate/#hvac-modes
For me the icon for `auto` in HA looks like schedule, so I implemented it that way.
Usually in product manuals "Automatic mode" is schedule, and "Manual mode" is "maintain temperature set on valve", "anti-freezing" is the same as `away` preset in HA.
