### ISSUE TITLE
Support Signify/Philips Hue wall switch module (RDM001)

### ISSUE THREAD

**Issue by RubenN** [Koenkk/zigbee-herdsman-converters#2393]
Erik Baauw already added support for this module for deconz:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/4566

- I have one available, connected to a double push button 
- Only the left-button reacts
- I have no idea how to initialize it properly 
- Tried to combine several examples, but obviously missing some things

```
    // Signify
    {
        zigbeeModel: ['RDM001'],
        model: '929003017101',
        vendor: 'Signify Netherlands B.V.',
        description: 'Hue wall switch module',
        extend: preset.switch(),
        endpoint: (device) => {
           return {left: 1, right: 2};
        },
        fromZigbee: [fz.command_toggle, fz.battery],
        exposes: [e.battery(), e.action().withEndpoint('left'), e.action().withEndpoint('right'), e.action(['toggle_left', 'release_left', 'hold_left', 'toggle_right', 'release_right', 'hold_right'])],

        meta: {multiEndpoint: true},
        configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
        },
        ota: ota.zigbeeOTA,
    },
```

Results after pushing left button (right button = no result):
```
Debug Received Zigbee message from '0x001788010b00010d', type 'commandToggle', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 24420
Info MQTT publish: topic 'zigbee2mqtt/0x001788010b00010d', payload '{"action":"toggle_left","action_group":24420,"last_seen":"2021-03-19T10:37:47+01:00","linkquality":54,"state_left":"OFF","update":{"state":"idle"}}'
Info Configuring '0x001788010b00010d'
Info MQTT publish: topic 'zigbee2mqtt/0x001788010b00010d/action', payload 'toggle_left'
Debug Received Zigbee message from '0x001788010b00010d', type 'commandToggle', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 24420
Info MQTT publish: topic 'zigbee2mqtt/0x001788010b00010d', payload '{"action":"toggle_left","action_group":24420,"last_seen":"2021-03-19T10:37:48+01:00","linkquality":54,"state_left":"OFF","update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/0x001788010b00010d/action', payload 'toggle_left'
Error Failed to configure '0x001788010b00010d', attempt 2 (TypeError: Cannot read property 'bind' of undefined at Object.bind (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:24) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices.js:2857:29) at async Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.js:131:13))
```

**Comment by Koenkk** [comment]
Can you provide the data/database.db entry of this device?

**Comment by RubenN** [comment]
Sure:

```
{"id":9,"type":"EndDevice","ieeeAddr":"0x001788010b00010d","nwkAddr":59153,"manufId":4107,"manufName":"Signify Netherlands B.V.","powerSource":"Battery","modelId":"RDM001","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":2080,"inClusterList":[0,1,3,64512],"outClusterList":[3,4,6,8,25],"clusters":{"genBasic":{"attributes":{"modelId":"RDM001","manufacturerName":"Signify Netherlands B.V.","powerSource":3,"zclVersion":2,"appVersion":9,"stackVersion":2,"hwVersion":3,"dateCode":"20210115","swBuildId":"1.0.3"}},"genOnOff":{"attributes":{}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":160}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00124b0021b77b37","endpointID":1},{"cluster":0,"type":"endpoint","deviceIeeeAddress":"0x00124b0021b77b37","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b0021b77b37","endpointID":1},{"cluster":64512,"type":"endpoint","deviceIeeeAddress":"0x00124b0021b77b37","endpointID":1}],"configuredReportings":[],"meta":{}}},"appVersion":9,"stackVersion":2,"hwVersion":3,"dateCode":"20210115","swBuildId":"1.0.3","zclVersion":2,"interviewCompleted":true,"meta":{},"lastSeen":1616171105659}
```

**Comment by Koenkk** [comment]
Try applying the changes from https://github.com/Koenkk/zigbee-herdsman-converters/pull/2396/files

After this:
- Battery should work
- You should be able to configure the device_mode via the frontend (click on device -> exposes tab)
- For each device_mode please provide the debug logging when clicking the buttons

See https://www.zigbee2mqtt.io/information/debug.html on how to enable debug logging.

**Comment by RubenN** [comment]
**dual_push_button** (left):
```
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":2,"type":2,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":1,"time":2,"type":2,"unknown1":3145728,"unknown2":0}'
```

**dual_push_button** (right):
```
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":2,"time":0,"type":0,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":2,"time":0,"type":0,"unknown1":3145728,"unknown2":0}'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":2,"time":2,"type":2,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":2,"time":2,"type":2,"unknown1":3145728,"unknown2":0}'
```

**dual_rocker** (left):
```
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":1,"type":2,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":1,"time":1,"type":2,"unknown1":3145728,"unknown2":0}'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}'
Debug Received Zigbee message from 'eetkamer2', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":16784128,"imageType":274,"manufacturerCode":4107}' from endpoint 11 with groupID 0
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":1,"type":2,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":1,"time":1,"type":2,"unknown1":3145728,"unknown2":0}'
```

**dual_rocker** (right):
```
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":2,"time":0,"type":0,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":2,"time":0,"type":0,"unknown1":3145728,"unknown2":0}'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":2,"time":1,"type":2,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":2,"time":1,"type":2,"unknown1":3145728,"unknown2":0}'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":2,"time":0,"type":0,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":2,"time":0,"type":0,"unknown1":3145728,"unknown2":0}'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":2,"time":1,"type":2,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":2,"time":1,"type":2,"unknown1":3145728,"unknown2":0}'
```

**single_push_button** (left)
```
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":2,"type":2,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":1,"time":2,"type":2,"unknown1":3145728,"unknown2":0}'
```

**single_rocker** (left)
```
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":1,"type":2,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":1,"time":1,"type":2,"unknown1":3145728,"unknown2":0}'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":1,"time":0,"type":0,"unknown1":3145728,"unknown2":0}'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":1,"type":2,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Debug No converter available for '929003017102' with cluster 'manuSpecificPhilips' and type 'commandHueNotification' and data '{"button":1,"time":1,"type":2,"unknown1":3145728,"unknown2":0}'
```

**Comment by Koenkk** [comment]
Looks good, updated and should expose an action now.

**Comment by RubenN** [comment]
Yes, works ok! Thanks for the quick responses!

Seems that a longpress is also supported, that gives the following:

```
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":16,"type":1,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/switch1', payload '{"action":"left_undefined","battery":80,"last_seen":"2021-03-20T08:36:26+01:00","linkquality":48,"state_left":"OFF","update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/switch1/action', payload 'left_undefined'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":1,"time":20,"type":3,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/switch1', payload '{"action":"left_undefined","battery":80,"last_seen":"2021-03-20T08:36:27+01:00","linkquality":51,"state_left":"OFF","update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/switch1/action', payload 'left_undefined'
```

and

```
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":2,"time":8,"type":1,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/switch1', payload '{"action":"right_undefined","battery":80,"last_seen":"2021-03-20T08:38:48+01:00","linkquality":36,"state_left":"OFF","update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/switch1/action', payload 'right_undefined'
Debug Received Zigbee message from 'switch1', type 'commandHueNotification', cluster 'manuSpecificPhilips', data '{"button":2,"time":16,"type":1,"unknown1":3145728,"unknown2":0}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/switch1', payload '{"action":"right_undefined","battery":80,"last_seen":"2021-03-20T08:38:49+01:00","linkquality":36,"state_left":"OFF","update":{"state":"idle"}}'
Info MQTT publish: topic 'zigbee2mqtt/switch1/action', payload 'right_undefined'
```

**Comment by Koenkk** [comment]
added, can you check if it works?

**Comment by RubenN** [comment]
Yes, perfect!
Many thanks, gives a lot of insight in the workings of zigbee2mqtt :-)

**Comment by Koenkk** [comment]
The manufacturer is indeed Signify, however they still use this Philips brand (https://www.philips-hue.com/en-gb/p/hue-philips-hue-wall-switch-module/8719514318045).

Regarding the second one, did it configure correctly? You can force it by going to the frontend, click on the device and click the "gears" icon

**Comment by RubenN** [comment]
Tried the reconfigure:

```
Info Successfully configured '0x001788010b000106'
Info MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"0x001788010b000106"},"status":"ok","transaction":"mgklu-1"}'
```

but no joy:

```
Debug Received Zigbee message from '0x001788010b000106', type 'commandToggle', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 15055
Debug No converter available for '929003017102' with cluster 'genOnOff' and type 'commandToggle' and data '{}'
```

**Comment by RubenN** [comment]
Tried to delete device and rejoin again:
```
Info Device '0x001788010b000106' joined
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010b000106","ieee_address":"0x001788010b000106"},"type":"device_joined"}'
Info Starting interview of '0x001788010b000106'
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010b000106","ieee_address":"0x001788010b000106","status":"started"},"type":"device_interview"}'
Debug Device '0x001788010b000106' announced itself
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"friendly_name":"0x001788010b000106","ieee_address":"0x001788010b000106"},"type":"device_announce"}'
Debug Received Zigbee message from '0x001788010b000106', type 'readResponse', cluster 'genBasic', data '{"modelId":"RDM001"}' from endpoint 1 with groupID 0
Debug Received Zigbee message from '0x001788010b000106', type 'readResponse', cluster 'genBasic', data '{"manufacturerName":"Signify Netherlands B.V."}' from endpoint 1 with groupID 0
Debug Received Zigbee message from '0x001788010b000106', type 'readResponse', cluster 'genBasic', data '{"powerSource":3}' from endpoint 1 with groupID 0
Debug Received Zigbee message from '0x001788010b000106', type 'readResponse', cluster 'genBasic', data '{"zclVersion":2}' from endpoint 1 with groupID 0
Debug Received Zigbee message from '0x001788010b000106', type 'readResponse', cluster 'genBasic', data '{"appVersion":9}' from endpoint 1 with groupID 0
Debug Received Zigbee message from '0x001788010b000106', type 'readResponse', cluster 'genBasic', data '{"stackVersion":2}' from endpoint 1 with groupID 0
Debug Received Zigbee message from '0x001788010b000106', type 'readResponse', cluster 'genBasic', data '{"hwVersion":3}' from endpoint 1 with groupID 0
Debug Received Zigbee message from '0x001788010b000106', type 'readResponse', cluster 'genBasic', data '{"dateCode":"20210115"}' from endpoint 1 with groupID 0
Debug Received Zigbee message from '0x001788010b000106', type 'readResponse', cluster 'genBasic', data '{"swBuildId":"1.0.3"}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'homeassistant/sensor/0x001788010b000106/battery/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x001788010b000106"],"manufacturer":"Philips","model":"Hue wall switch module (929003017102)","name":"0x001788010b000106","sw_version":"Zigbee2MQTT 1.18.1"},"device_class":"battery","json_attributes_topic":"zigbee2mqtt/0x001788010b000106","name":"0x001788010b000106 battery","state_topic":"zigbee2mqtt/0x001788010b000106","unique_id":"0x001788010b000106_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
Info MQTT publish: topic 'homeassistant/sensor/0x001788010b000106/device_mode/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x001788010b000106"],"manufacturer":"Philips","model":"Hue wall switch module (929003017102)","name":"0x001788010b000106","sw_version":"Zigbee2MQTT 1.18.1"},"json_attributes_topic":"zigbee2mqtt/0x001788010b000106","name":"0x001788010b000106 device mode","state_topic":"zigbee2mqtt/0x001788010b000106","unique_id":"0x001788010b000106_device_mode_zigbee2mqtt","value_template":"{{ value_json.device_mode }}"}'
Info MQTT publish: topic 'homeassistant/sensor/0x001788010b000106/linkquality/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x001788010b000106"],"manufacturer":"Philips","model":"Hue wall switch module (929003017102)","name":"0x001788010b000106","sw_version":"Zigbee2MQTT 1.18.1"},"icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x001788010b000106","name":"0x001788010b000106 linkquality","state_topic":"zigbee2mqtt/0x001788010b000106","unique_id":"0x001788010b000106_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Info MQTT publish: topic 'homeassistant/sensor/0x001788010b000106/update_state/config', payload '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x001788010b000106"],"manufacturer":"Philips","model":"Hue wall switch module (929003017102)","name":"0x001788010b000106","sw_version":"Zigbee2MQTT 1.18.1"},"icon":"mdi:update","json_attributes_topic":"zigbee2mqtt/0x001788010b000106","name":"0x001788010b000106 update state","state_topic":"zigbee2mqtt/0x001788010b000106","unique_id":"0x001788010b000106_update_state_zigbee2mqtt","value_template":"{{ value_json['update']['state'] }}"}'
Info Successfully interviewed '0x001788010b000106', device has successfully been paired
Info Device '0x001788010b000106' is supported, identified as: Philips Hue wall switch module (929003017102)
Info MQTT publish: topic 'zigbee2mqtt/bridge/event', payload '{"data":{"definition":{"description":"Hue wall switch module","exposes":[{"access":1,"description":"Remaining battery in %","name":"battery","property":"battery","type":"numeric","unit":"%","value_max":100,"value_min":0},{"access":1,"description":"Triggered action (e.g. a button click)","name":"action","property":"action","type":"enum","values":["left_press","left_press_release","right_press","right_press_release"]},{"access":7,"name":"device_mode","property":"device_mode","type":"enum","values":["single_rocker","single_push_button","dual_rocker","dual_push_button"]},{"access":1,"description":"Link quality (signal strength)","name":"linkquality","property":"linkquality","type":"numeric","unit":"lqi","value_max":255,"value_min":0}],"model":"929003017102","supports_ota":true,"vendor":"Philips"},"friendly_name":"0x001788010b000106","ieee_address":"0x001788010b000106","status":"successful","supported":true},"type":"device_interview"}'
Info Configuring '0x001788010b000106'
Debug Received MQTT message on 'homeassistant/sensor/0x001788010b000106/battery/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x001788010b000106"],"manufacturer":"Philips","model":"Hue wall switch module (929003017102)","name":"0x001788010b000106","sw_version":"Zigbee2MQTT 1.18.1"},"device_class":"battery","json_attributes_topic":"zigbee2mqtt/0x001788010b000106","name":"0x001788010b000106 battery","state_topic":"zigbee2mqtt/0x001788010b000106","unique_id":"0x001788010b000106_battery_zigbee2mqtt","unit_of_measurement":"%","value_template":"{{ value_json.battery }}"}'
Debug Received MQTT message on 'homeassistant/sensor/0x001788010b000106/device_mode/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x001788010b000106"],"manufacturer":"Philips","model":"Hue wall switch module (929003017102)","name":"0x001788010b000106","sw_version":"Zigbee2MQTT 1.18.1"},"json_attributes_topic":"zigbee2mqtt/0x001788010b000106","name":"0x001788010b000106 device mode","state_topic":"zigbee2mqtt/0x001788010b000106","unique_id":"0x001788010b000106_device_mode_zigbee2mqtt","value_template":"{{ value_json.device_mode }}"}'
Debug Received MQTT message on 'homeassistant/sensor/0x001788010b000106/linkquality/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x001788010b000106"],"manufacturer":"Philips","model":"Hue wall switch module (929003017102)","name":"0x001788010b000106","sw_version":"Zigbee2MQTT 1.18.1"},"icon":"mdi:signal","json_attributes_topic":"zigbee2mqtt/0x001788010b000106","name":"0x001788010b000106 linkquality","state_topic":"zigbee2mqtt/0x001788010b000106","unique_id":"0x001788010b000106_linkquality_zigbee2mqtt","unit_of_measurement":"lqi","value_template":"{{ value_json.linkquality }}"}'
Debug Received MQTT message on 'homeassistant/sensor/0x001788010b000106/update_state/config' with data '{"availability":[{"topic":"zigbee2mqtt/bridge/state"}],"device":{"identifiers":["zigbee2mqtt_0x001788010b000106"],"manufacturer":"Philips","model":"Hue wall switch module (929003017102)","name":"0x001788010b000106","sw_version":"Zigbee2MQTT 1.18.1"},"icon":"mdi:update","json_attributes_topic":"zigbee2mqtt/0x001788010b000106","name":"0x001788010b000106 update state","state_topic":"zigbee2mqtt/0x001788010b000106","unique_id":"0x001788010b000106_update_state_zigbee2mqtt","value_template":"{{ value_json['update']['state'] }}"}'
Debug Received Zigbee message from '0x001788010b000106', type 'readResponse', cluster 'genPowerCfg', data '{"batteryPercentageRemaining":200}' from endpoint 1 with groupID 0
Info MQTT publish: topic 'zigbee2mqtt/0x001788010b000106', payload '{"battery":100,"last_seen":"2021-03-21T15:47:08+01:00","linkquality":150}'
Debug Mocking 'update' value for Home Assistant
Info MQTT publish: topic 'zigbee2mqtt/0x001788010b000106', payload '{"battery":100,"last_seen":"2021-03-21T15:47:08+01:00","linkquality":150,"update":{"state":"idle"}}'
Info Successfully configured '0x001788010b000106'
Debug Received Zigbee message from '0x001788010b000106', type 'commandToggle', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 20706
Debug No converter available for '929003017102' with cluster 'genOnOff' and type 'commandToggle' and data '{}'
Debug Received Zigbee message from '0x001788010b000106', type 'commandToggle', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 20706
Debug No converter available for '929003017102' with cluster 'genOnOff' and type 'commandToggle' and data '{}'
Debug Received MQTT message on 'zigbee2mqtt/0x001788010b000106/set' with data '{"device_mode":"dual_push_button"}'
Debug Publishing 'set' 'device_mode' to '0x001788010b000106'
Debug Received Zigbee message from '0x001788010b000106', type 'commandToggle', cluster 'genOnOff', data '{}' from endpoint 1 with groupID 20706
Debug No converter available for '929003017102' with cluster 'genOnOff' and type 'commandToggle' and data '{}'
```

**Comment by RubenN** [comment]
Bind page shows other info then the first device.
![image](https://user-images.githubusercontent.com/854450/111909343-332b4f00-8a5d-11eb-8c99-81bd8101cf5a.png)

**Comment by Koenkk** [comment]
Maybe the device_mode needs to be set first?

**Comment by RubenN** [comment]
Tried that and that didn't help.
Anything else that I can try?

**Comment by RubenN** [comment]
Added genOnOff and manuSpecificPhilips to the reporting.bind and now all is well. Don't know if both are necessary, but it works.

```
    {
        zigbeeModel: ['RDM001'],
        model: '929003017102',
        vendor: 'Philips',
        description: 'Hue wall switch module',
        fromZigbee: [fz.battery, fz.hue_wall_switch_device_mode, fz.hue_wall_switch],
        exposes: [e.battery(), e.action(['left_press', 'left_press_release', 'right_press', 'right_press_release']),
            exposes.enum('device_mode', ea.ALL, ['single_rocker', 'single_push_button', 'dual_rocker', 'dual_push_button'])],
        toZigbee: [tz.hue_wall_switch_device_mode],
        meta: {configureKey: 1},
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint = device.getEndpoint(1);
            await reporting.bind(endpoint, coordinatorEndpoint, ['genPowerCfg','genOnOff','manuSpecificPhilips']);
            await reporting.batteryPercentageRemaining(endpoint);
            const options = {manufacturerCode: 0x100B, disableDefaultResponse: true};
            await endpoint.write('genBasic', {0x0034: {value: 0, type: 48}}, options);
        },
        ota: ota.zigbeeOTA,
    },

```

**Comment by Koenkk** [comment]
Makes sense, added the config.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
