### ISSUE TITLE
Livolo TI0001-switch-2gang not working

### ISSUE THREAD

**Issue by jeugen1** [Koenkk/zigbee-herdsman-converters#2512]
After pairing it is possible to get status of the switch, but if you try to control it, you receive error message:
```
Zigbee2MQTT:error 2021-04-03 09:57:28: Failed to call 'EntityPublish' 'onMQTTMessage' (AssertionError [ERR_ASSERTION]: Endpoint name 'left' is given but no endpoints defined
    at Zigbee.resolveEntity (/app/lib/zigbee.js:233:25)
    at EntityPublish.onMQTTMessage (/app/lib/extension/publish.js:52:44)
    at Controller.callExtensionMethod (/app/lib/controller.js:382:44)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5))
Zigbee2MQTT:error 2021-04-03 09:57:32: Failed to call 'EntityPublish' 'onMQTTMessage' (AssertionError [ERR_ASSERTION]: Endpoint name 'right' is given but no endpoints defined
    at Zigbee.resolveEntity (/app/lib/zigbee.js:233:25)
    at EntityPublish.onMQTTMessage (/app/lib/extension/publish.js:52:44)
    at Controller.callExtensionMethod (/app/lib/controller.js:382:44)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5))
```
it could be fixed by adding:
```
    endpoint: (device) => {
            return {'left': 6, 'right': 6};
        },
```
to the the TI0001-switch-2gang area in **devices.js** .
More info in Piscator74's [message](https://github.com/Koenkk/zigbee2mqtt.io/pull/607#issuecomment-812860097).

**Comment by Koenkk** [comment]
Added.
