### ISSUE TITLE
WS-EUK02 Aqara switch endpoint 2 errors when pairing

### ISSUE THREAD

**Issue by blakadder** [Koenkk/zigbee-herdsman-converters#2654]
I get errors when trying to pair Aqara WS-EUK02 using this config:
```
    {
        zigbeeModel: ['lumi.switch.l2aeu1'],
        model: 'WS-EUK02',
        vendor: 'Aqara',
        description: 'Smart Wall Switch H1 EU (No Neutral, Double Rocker)',
        extend: extend.switch(),
        exposes: [e.switch().withEndpoint('left'), e.switch().withEndpoint('right')],
        toZigbee: [tz.on_off],
        fromZigbee: [fz.on_off],
        meta: {multiEndpoint: true},
        endpoint: (device) => {
            return {'left': 1, 'right': 2};
        },
        configure: async (device, coordinatorEndpoint, logger) => {
            const endpoint1 = device.getEndpoint(1);
            await reporting.bind(endpoint1, coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(endpoint1);
            const endpoint2 = device.getEndpoint(2);
            await reporting.bind(endpoint2, coordinatorEndpoint, ['genOnOff']);
            await reporting.onOff(endpoint2);
        },
    };
```

```
Zigbee2MQTT:error 2021-06-04 21:53:04: Failed to configure '0x54ef4410000d047b', attempt 1 (Error: ConfigureReporting 0x54ef4410000d047b/2 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'SOFTWARE_FAILURE')
    at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:221:23)
    at Endpoint.<anonymous> (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:488:26)
    at Generator.next (<anonymous>)
    at fulfilled (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:24:58))
```

There's a firmware issue that physically pressing right rocker is not reporting back state changes. State changes are reported when sending commands or trying to read cluster status.

I have the same behaviour in ZHA and Tasmota. In Tasmota I resorted to polling endpoint 2 cluster 6 every few seconds.

**Comment by Koenkk** [comment]
Lets continue in https://github.com/Koenkk/zigbee2mqtt/issues/6524
