### ISSUE TITLE
Unsupported Device: ClickSmart+ CMA30035

### ISSUE THREAD

**Issue by uvjim** [Koenkk/zigbee-herdsman-converters#2778]
I have recently purchased one of these.  Paired fine, but reported as unknown.  The following can be seen in the logs...

```
Zigbee2MQTT:warn  2021-07-09 19:41:45: Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TYZB01_mtunwanm'
Zigbee2MQTT:warn  2021-07-09 19:41:45: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
```

This is a single UK in wall socket.  The URL for the device is: https://click-smart.com/products/1-gang-smart-socket

I'm pretty sure it should match this as a white label: `TS011F_wall_outlet`

However, I'm running zigbee2mqtt as an add-on and can't work out how to test with external convertors.

Is there any chance it can be added?

**Comment by Koenkk** [comment]
Added, 
Changes will be available in the dev branch tomorrow. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)

**Comment by uvjim** [comment]
This could easily by my issue as I've never used the edge add-on in HA.
I stopped the production version.  Installed the edge version.  Copied the config from the production version to the edge version and started it.  It shows errors about connecting to MQTT but still seems to be able to control devices.

The CMA30035 device though still shows as unsupported.  The db entry for the device is here: -

```
{
    "id": 17,
    "type": "Router",
    "ieeeAddr": "0x60a423fffeae3467",
    "nwkAddr": 37899,
    "manufId": 4098,
    "manufName": "_TYZB01_mtunwanm",
    "powerSource": "Mains (single phase)",
    "modelId": "TS011F",
    "epList": [
        1
    ],
    "endpoints": {
        "1": {
            "profId": 260,
            "epId": 1,
            "devId": 9,
            "inClusterList": [
                0,
                10,
                4,
                5,
                6
            ],
            "outClusterList": [
                25
            ],
            "clusters": {
                "genBasic": {
                    "attributes": {
                        "65503": "�_(\u0012",
                        "65506": 22,
                        "modelId": "TS011F",
                        "manufacturerName": "_TYZB01_mtunwanm",
                        "powerSource": 1,
                        "zclVersion": 3,
                        "appVersion": 64,
                        "stackVersion": 0,
                        "hwVersion": 1,
                        "dateCode": ""
                    }
                },
                "genOnOff": {
                    "attributes": {
                        "32768": 0,
                        "onOff": 1,
                        "onTime": 0,
                        "offWaitTime": 0
                    }
                }
            },
            "binds": [],
            "configuredReportings": [],
            "meta": {}
        }
    },
    "appVersion": 64,
    "stackVersion": 0,
    "hwVersion": 1,
    "dateCode": "",
    "zclVersion": 3,
    "interviewCompleted": true,
    "meta": {},
    "lastSeen": 1626117675224
}
```
If I've worked out the attribute `65503` properly it should be `"\uFFFD\u005F\u007F\u0028\u0012"`

Did I need to do anything else for it to recognise?  I did put the device into pair mode again and permit all on zigbee2mqtt.

Thanks for any help - my first time at doing this.

**Comment by Koenkk** [comment]
Make sure to use the correct repo. If for the non-edge version you see 1.18.1 you are using the wrong repo (check first point of https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0)

**Comment by uvjim** [comment]
I'm see 1.20.0-1 for non-edge.
The following is in the log when I start the Edge version, after stopping the non-edge version.
Even though I have the messages re: not connecting to the MQTT server the switches that are recognised do still work from HA.
I don't see these messages on the non-edge version.
In both versions the CMA30035 shows as unsupported, as per the logs.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[18:39:46] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[18:39:47] INFO: MQTT available, fetching server detail ...
[18:39:47] INFO: Previous config file found, checking backup
[18:39:47] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[18:39:47] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:39:49] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.20.0-dev start /app
> node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:warn  2021-07-13 18:39:55: Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TYZB01_mtunwanm'
Zigbee2MQTT:warn  2021-07-13 18:39:55: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Zigbee2MQTT:error 2021-07-13 18:39:55: Not connected to MQTT server!
Zigbee2MQTT:error 2021-07-13 18:39:55: Cannot send message: topic: 'zigbee2mqtt/Lounge - Single Socket', payload: '{"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Lounge - Single Socket","hardwareVersion":1,"ieeeAddr":"0x60a423fffeae3467","manufacturerID":4098,"manufacturerName":"_TYZB01_mtunwanm","model":"unknown","networkAddress":37899,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"last_seen":"2021-07-13T17:39:55.065Z","linkquality":255}
Zigbee2MQTT:error 2021-07-13 18:39:55: Not connected to MQTT server!
Zigbee2MQTT:error 2021-07-13 18:39:55: Cannot send message: topic: 'zigbee2mqtt/Office - Light', payload: '{"action":null,"device":{"applicationVersion":1,"dateCode":"08-2-2019","friendlyName":"Office - Light","hardwareVersion":54,"ieeeAddr":"0x00158d000579ab27","manufacturerID":4151,"manufacturerName":"LUMI","model":"QBKG22LM","networkAddress":47127,"powerSource":"DC Source","stackVersion":2,"type":"EndDevice","zclVersion":0},"last_seen":"2021-07-13T17:39:55.104Z","linkquality":255,"operation_mode_left":null,"operation_mode_right":null,"state_left":"OFF","state_right":"OFF"}
Zigbee2MQTT:error 2021-07-13 18:39:55: Not connected to MQTT server!
Zigbee2MQTT:error 2021-07-13 18:39:55: Cannot send message: topic: 'zigbee2mqtt/Spare Bedroom Window', payload: '{"battery":100,"contact":true,"device":{"applicationVersion":3,"dateCode":"20161128","friendlyName":"Spare Bedroom Window","ieeeAddr":"0x00158d0003c7f930","manufacturerID":4151,"manufacturerName":"LUMI","model":"MCCGQ11LM","networkAddress":35942,"softwareBuildID":"3000-0001","stackVersion":2,"type":"EndDevice","zclVersion":1},"last_seen":"2021-07-13T17:39:55.167Z","linkquality":239,"temperature":24,"voltage":3005}
Zigbee2MQTT:error 2021-07-13 18:40:09: Not connected to MQTT server!
Zigbee2MQTT:error 2021-07-13 18:40:09: Cannot send message: topic: 'zigbee2mqtt/Office - Light', payload: '{"action":null,"device":{"applicationVersion":1,"dateCode":"08-2-2019","friendlyName":"Office - Light","hardwareVersion":54,"ieeeAddr":"0x00158d000579ab27","manufacturerID":4151,"manufacturerName":"LUMI","model":"QBKG22LM","networkAddress":47127,"powerSource":"DC Source","stackVersion":2,"type":"EndDevice","zclVersion":0},"last_seen":"2021-07-13T17:40:09.608Z","linkquality":255,"operation_mode_left":null,"operation_mode_right":null,"state_left":"OFF","state_right":"OFF"}
Zigbee2MQTT:error 2021-07-13 18:40:38: Not connected to MQTT server!
Zigbee2MQTT:error 2021-07-13 18:40:38: Cannot send message: topic: 'zigbee2mqtt/Garage - Socket', payload: '{"device":{"applicationVersion":64,"dateCode":"","friendlyName":"Garage - Socket","hardwareVersion":1,"ieeeAddr":"0x60a423fffe9d9977","manufacturerID":4098,"manufacturerName":"_TYZB01_hlla45kx","model":"TS011F_2_gang_wall","networkAddress":917,"powerSource":"Mains (single phase)","stackVersion":0,"type":"Router","zclVersion":3},"last_seen":"2021-07-13T17:40:38.928Z","linkquality":255,"state_l1":"OFF","state_l2":"ON"}
Zigbee2MQTT:error 2021-07-13 18:40:41: Not connected to MQTT server!
Zigbee2MQTT:error 2021-07-13 18:40:41: Cannot send message: topic: 'zigbee2mqtt/Office - Light', payload: '{"action":null,"device":{"applicationVersion":1,"dateCode":"08-2-2019","friendlyName":"Office - Light","hardwareVersion":54,"ieeeAddr":"0x00158d000579ab27","manufacturerID":4151,"manufacturerName":"LUMI","model":"QBKG22LM","networkAddress":47127,"powerSource":"DC Source","stackVersion":2,"type":"EndDevice","zclVersion":0},"last_seen":"2021-07-13T17:40:41.771Z","linkquality":255,"operation_mode_left":null,"operation_mode_right":null,"state_left":"OFF","state_right":"OFF"}
Zigbee2MQTT:error 2021-07-13 18:40:49: Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'multiEndpoint' of undefined
    at Object.convert (/app/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:4533:29)
    at /app/lib/extension/receive.js:159:41
    at Array.forEach (<anonymous>)
    at Receive.onZigbeeEvent (/app/lib/extension/receive.js:158:20)
    at Controller.callExtensionMethod (/app/lib/controller.js:408:81)
    at async Controller.onZigbeeEvent (/app/lib/controller.js:280:24))
Zigbee2MQTT:error 2021-07-13 18:40:49: Not connected to MQTT server!
Zigbee2MQTT:error 2021-07-13 18:40:49: Cannot send message: topic: 'zigbee2mqtt/Utility - Light', payload: '{"action":null,"device":{"applicationVersion":1,"dateCode":"03-20-2019","friendlyName":"Utility - Light","hardwareVersion":54,"ieeeAddr":"0x00158d0005c16feb","manufacturerID":4151,"manufacturerName":"LUMI","model":"QBKG21LM","networkAddress":8156,"powerSource":"DC Source","stackVersion":2,"type":"EndDevice","zclVersion":0},"last_seen":"2021-07-13T17:40:49.529Z","linkquality":255,"operation_mode":null,"state":"OFF"}
Zigbee2MQTT:error 2021-07-13 18:40:54: Not connected to MQTT server!
Zigbee2MQTT:error 2021-07-13 18:40:54: Cannot send message: topic: 'zigbee2mqtt/Utility - Light', payload: '{"action":null,"device":{"applicationVersion":1,"dateCode":"03-20-2019","friendlyName":"Utility - Light","hardwareVersion":54,"ieeeAddr":"0x00158d0005c16feb","manufacturerID":4151,"manufacturerName":"LUMI","model":"QBKG21LM","networkAddress":8156,"powerSource":"DC Source","stackVersion":2,"type":"EndDevice","zclVersion":0},"last_seen":"2021-07-13T17:40:54.690Z","linkquality":255,"operation_mode":null,"state":"OFF"}
Zigbee2MQTT:error 2021-07-13 18:40:55: Failed to set permit join to false
```

**Comment by Koenkk** [comment]
Can you try uninstalling the edge version and install it again (to be sure it runs the latest version). 

When starting the edge version, make sure the normal version is not running

**Comment by uvjim** [comment]
Getting better...

1. Uninstalled edge.
2. Stopped normal.
3. Reloaded the add-ons from the Supervisor. 
4. Installed edge.
5. Copy config from normal to edge.
6. Start edge.
7. Errors about not connecting to MQTT.
8. Restart edge.
9. Errors about MQTT disappeared.
10. CMA30035 still showed as unsupported.
11. Force delete CMA30035.
12. Permit joining and put CMA30035 into joining mode.

However, it still shows as unsupported.  I'm not really sure where to go from here so any help is appreciated.

**Comment by Koenkk** [comment]
And you still see `Zigbee2MQTT:warn  2021-07-13 18:39:55: Received message from unsupported device with Zigbee model 'TS011F' and manufacturer name '_TYZB01_mtunwanm'` in the log? If yes I'm running out of ideas why it doesn't work, maybe wait for the next release on 1 August instead since it will be available there.

**Comment by uvjim** [comment]
I'll wait then I think.  I just tested again - you never know I might get lucky... I turned on info logging in the UI just in case. Results are below (in case they shed any light on the situation). I've removed anything not related to that device (there was a few messages from other devices in the log as well).

```
Info Zigbee: allowing new devices to join.
Info MQTT publish: topic ‘zigbee2mqtt/bridge/response/permit_join’, payload ‘{“data”:{“time”:254,”value”:true},”status”:”ok”,”transaction”:”h9515-3”}’
Info Device ‘0x60a423fffeae3467’ joined
Info MQTT publish: topic ‘zigbee2mqtt/bridge/event’, payload ‘{“data”:{“friendly_name”:”0x60a423fffeae3467”,”ieee_address”:”0x60a423fffeae3467”},”type”:”device_joined”}’
Info Starting interview of ‘0x60a423fffeae3467’
Info MQTT publish: topic ‘zigbee2mqtt/bridge/event’, payload ‘{“data”:{“friendly_name”:”0x60a423fffeae3467”,”ieee_address”:”0x60a423fffeae3467”,”status”:”started”},”type”:”device_interview”}’
Info MQTT publish: topic ‘zigbee2mqtt/bridge/log’, payload ‘{“message”:{“friendly_name”:”0x60a423fffeae3467”},”type”:”device_connected”}’
Info MQTT publish: topic ‘zigbee2mqtt/bridge/log’, payload ‘{“message”:”interview_started”,”meta”:{“friendly_name”:”0x60a423fffeae3467”},”type”:”pairing”}’
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“friendlyName”:”0x60a423fffeae3467”,”ieeeAddr”:”0x60a423fffeae3467”,”model”:”unknown”,”networkAddress”:890,”type”:”Unknown”},”last_seen”:”2021-07-16T17:53:23.018Z”}’
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“friendlyName”:”0x60a423fffeae3467”,”ieeeAddr”:”0x60a423fffeae3467”,”model”:”unknown”,”networkAddress”:890,”type”:”Unknown”},”last_seen”:”2021-07-16T17:53:23.018Z”}’
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“friendlyName”:”0x60a423fffeae3467”,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”model”:”unknown”,”networkAddress”:890,”type”:”Router”},”last_seen”:”2021-07-16T17:53:23.495Z”,”linkquality”:255}’
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“friendlyName”:”0x60a423fffeae3467”,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”type”:”Router”},”last_seen”:”2021-07-16T17:53:23.622Z”,”linkquality”:255}’
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“friendlyName”:”0x60a423fffeae3467”,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”type”:”Router”},”last_seen”:”2021-07-16T17:53:23.748Z”,”linkquality”:255}’
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“friendlyName”:”0x60a423fffeae3467”,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:23.874Z”,”linkquality”:255}’
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”friendlyName”:”0x60a423fffeae3467”,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:23.999Z”,”linkquality”:255}’
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”friendlyName”:”0x60a423fffeae3467”,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”stackVersion”:0,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:24.112Z”,”linkquality”:255}’
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”friendlyName”:”0x60a423fffeae3467”,”hardwareVersion”:1,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”stackVersion”:0,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:24.231Z”,”linkquality”:255}’
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”dateCode”:””,”friendlyName”:”0x60a423fffeae3467”,”hardwareVersion”:1,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”stackVersion”:0,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:24.347Z”,”linkquality”:255}’
Info Successfully interviewed ‘0x60a423fffeae3467’, device has successfully been paired
Warning Device ‘0x60a423fffeae3467’ with Zigbee model ‘TS011F’ and manufacturer name ‘_TYZB01_mtunwanm’ is NOT supported, please follow https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
Info MQTT publish: topic ‘zigbee2mqtt/bridge/event’, payload ‘{“data”:{“definition”:null,”friendly_name”:”0x60a423fffeae3467”,”ieee_address”:”0x60a423fffeae3467”,”status”:”successful”,”supported”:false},”type”:”device_interview”}’
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”dateCode”:””,”friendlyName”:”0x60a423fffeae3467”,”hardwareVersion”:1,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”stackVersion”:0,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:24.465Z”,”linkquality”:255}’
Info MQTT publish: topic ‘zigbee2mqtt/bridge/log’, payload ‘{“message”:”interview_successful”,”meta”:{“friendly_name”:”0x60a423fffeae3467”,”supported”:false},”type”:”pairing”}’
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”dateCode”:””,”friendlyName”:”0x60a423fffeae3467”,”hardwareVersion”:1,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”stackVersion”:0,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:24.465Z”,”linkquality”:255}’
Warning Received message from unsupported device with Zigbee model ‘TS011F’ and manufacturer name ‘_TYZB01_mtunwanm’
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”dateCode”:””,”friendlyName”:”0x60a423fffeae3467”,”hardwareVersion”:1,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”stackVersion”:0,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:24.927Z”,”linkquality”:255}’
Warning Received message from unsupported device with Zigbee model ‘TS011F’ and manufacturer name ‘_TYZB01_mtunwanm’
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”dateCode”:””,”friendlyName”:”0x60a423fffeae3467”,”hardwareVersion”:1,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”stackVersion”:0,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:25.058Z”,”linkquality”:255}’
Warning Received message from unsupported device with Zigbee model ‘TS011F’ and manufacturer name ‘_TYZB01_mtunwanm’
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”dateCode”:””,”friendlyName”:”0x60a423fffeae3467”,”hardwareVersion”:1,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”stackVersion”:0,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:25.183Z”,”linkquality”:255}’
Warning Received message from unsupported device with Zigbee model ‘TS011F’ and manufacturer name ‘_TYZB01_mtunwanm’
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”dateCode”:””,”friendlyName”:”0x60a423fffeae3467”,”hardwareVersion”:1,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”stackVersion”:0,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:25.315Z”,”linkquality”:255}’
Warning Received message from unsupported device with Zigbee model ‘TS011F’ and manufacturer name ‘_TYZB01_mtunwanm’
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”dateCode”:””,”friendlyName”:”0x60a423fffeae3467”,”hardwareVersion”:1,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”stackVersion”:0,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:29.435Z”,”linkquality”:255}’
Warning Received message from unsupported device with Zigbee model ‘TS011F’ and manufacturer name ‘_TYZB01_mtunwanm’
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”dateCode”:””,”friendlyName”:”0x60a423fffeae3467”,”hardwareVersion”:1,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”stackVersion”:0,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:34.248Z”,”linkquality”:255}’
Warning Received message from unsupported device with Zigbee model ‘TS011F’ and manufacturer name ‘_TYZB01_mtunwanm’
Warning Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html.
Info MQTT publish: topic ‘zigbee2mqtt/0x60a423fffeae3467’, payload ‘{“device”:{“applicationVersion”:64,”dateCode”:””,”friendlyName”:”0x60a423fffeae3467”,”hardwareVersion”:1,”ieeeAddr”:”0x60a423fffeae3467”,”manufacturerID”:4098,”manufacturerName”:”_TYZB01_mtunwanm”,”model”:”unknown”,”networkAddress”:890,”powerSource”:”Mains (single phase)”,”stackVersion”:0,”type”:”Router”,”zclVersion”:3},”last_seen”:”2021-07-16T17:53:34.458Z”,”linkquality”:255}’
Info Zigbee: disabling joining new devices.
Info MQTT publish: topic ‘zigbee2mqtt/bridge/response/permit_join’, payload ‘{“data”:{“time”:254,”value”:false},”status”:”ok”,”transaction”:”h9515-4”}’
Zigbee: disabling joining new devices.
```

**Comment by uvjim** [comment]
Just upgraded and can confirm this is now working as expected.
Thank you for your support.
