### ISSUE TITLE
Error get 'setpoint_raise_lower' from eCozy device

### ISSUE THREAD

**Issue by snoopyCode** [Koenkk/zigbee-herdsman-converters#306]
When I want to get the value `{"setpoint_raise_lower":""}` from an eCozy device, zigbee2mqtt crashes with the following:

```
                    zclData: [{attrId: zclId.attr(cid, attrId).value}],
                                                              ^

TypeError: Cannot read property 'value' of undefined
    at Object.convert (/app/node_modules/zigbee-shepherd-converters/converters/toZigbee.js:572:63)
    at keys.forEach (/app/lib/extension/devicePublish.js:147:41)
    at Array.forEach (<anonymous>)
    at DevicePublish.onMQTTMessage (/app/lib/extension/devicePublish.js:139:14)
    at results.extensions.filter.map (/app/lib/controller.js:134:27)
    at Array.map (<anonymous>)
    at Controller.onMQTTMessage (/app/lib/controller.js:134:14)
    at MQTT.onMessage (/app/lib/mqtt.js:81:18)
    at emitThree (events.js:136:13)
    at MqttClient.emit (events.js:217:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.1.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.1.1 start script.
```

**Comment by Koenkk** [comment]
@Chrischi- do you know more about this?

**Comment by Chrischi-** [comment]
@Koenkk @snoopyCode 
As far as I know `setpoint_raise_lower` is just client-to-server and I think the `get` implementation is wrong.

**Comment by allofmex** [comment]
Yes, `get` in [toZigbee.js#L607](https://github.com/Koenkk/zigbee-shepherd-converters/blob/a0bb7059617f023952437b42ea276a44ef60cbbf/converters/toZigbee.js#L607) is wrong and should be removed. You should use `thermostat_occupied_heating_setpoint` or `thermostat_unoccupied_heating_setpoint` to read the value you changed with `setpoint_raise_lower`.

**Comment by Chrischi-** [comment]
did a PR #308
