### ISSUE TITLE
Sunricher SR-ZG9001K12-DIM-Z4 button 2,3,4,S1,S2 not recognized

### ISSUE THREAD

**Issue by herveja** [Koenkk/zigbee-herdsman-converters#3086]
Hi guys,
Error when pairing Sunricher SR-ZG9001K12-DIM-Z4 (Sunricher SR-ZG9001K12-DIM-Z4 control via MQTT | zigbee2mqtt.io)
Quite a newbie in zigbee2mqtt but I've tried several approaches for weeks and I'm stuck.
I run zigbee2mqtt v1.21.1 on homeAssistant (raspberi with  zigate USB+ core version 2021.9.7 / supervisor 2021.09.0)
I receive error when I try to add the device in zigbee2mqtt (see below) 
**But the biggest issue is that only on/off button 1 is triggering event. Button 2,3,4 + S1, S2 don’t trigger anything and are not present in homeAssistant (I can only see 1_on, 1_off click event in MQTT devices)**

Error : 
`Failed to configure '0xbc33acfffe7d1e33', attempt 1 (Error: ConfigureReporting 0xbc33acfffe7d1e33/1 genOnOff([{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}], {"sendWhenActive":false,"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:293:23) at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:627:22) at Object.onOff (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:68:9) at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices/sunricher.js:43:13) at Configure.configure (/app/lib/extension/configure.js:137:13))
`

The device description in database.db is 
`{"id":4,"type":"EndDevice","ieeeAddr":"0xbc33acfffe7d1e33","nwkAddr":13131,"manufId":4644,"manufName":"Sunricher","powerSource":"Battery","modelId":"ZGRC-KEY-013","epList":[1,2,3,4],"endpoints":{"1":{"profId":260,"epId":1,"devId":1,"inClusterList":[0,1,3,2821],"outClusterList":[3,4,5,6,8,25,768,4096],"clusters":{"genPowerCfg":{"attributes":{"batteryPercentageRemaining":75}},"genBasic":{"attributes":{"modelId":"ZGRC-KEY-013","manufacturerName":"Sunricher","powerSource":3,"zclVersion":3,"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"NULL","swBuildId":"2.5.3_r20"}}},"binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00158d0005be7a7f","endpointID":1}],"configuredReportings":[],"meta":{}},"2":{"profId":260,"epId":2,"devId":1,"inClusterList":[0,1,3,2821],"outClusterList":[3,4,5,6,8,25,768,4096],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"hwVersion":0}},"genPowerCfg":{"attributes":{"batteryPercentageRemaining":87}}},"binds":[],"configuredReportings":[],"meta":{}},"3":{"profId":260,"epId":3,"devId":1,"inClusterList":[0,1,3,2821],"outClusterList":[3,4,5,6,8,25,768,4096],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}},"4":{"profId":260,"epId":4,"devId":1,"inClusterList":[0,1,3,2821],"outClusterList":[3,4,5,6,8,25,768,4096],"clusters":{"genBasic":{"attributes":{"appVersion":0,"stackVersion":0,"hwVersion":0}}},"binds":[],"configuredReportings":[],"meta":{}}},"appVersion":0,"stackVersion":0,"hwVersion":0,"dateCode":"NULL","swBuildId":"2.5.3_r20","zclVersion":3,"interviewCompleted":true,"meta":{},"lastSeen":1632419063521}`

Thank you for any clue you could provide.
Hervé (FR)

**Comment by herveja** [comment]
I don't know if it's relevant or not but with the following converter, my last enrolment of the device is now fully functional. 

```
	{
        zigbeeModel: ['ZGRC-KEY-013'],
        model: 'SR-ZG9001K12-DIM-Z4',
        vendor: 'Sunricher',
        description: '4 zone remote and 2 scenes',
        fromZigbee: [fz.battery, fz.command_move, fz.legacy.ZGRC013_brightness_onoff,
            fz.legacy.ZGRC013_brightness, fz.command_stop, fz.legacy.ZGRC013_brightness_stop, fz.command_on,
            fz.legacy.ZGRC013_cmdOn, fz.command_off, fz.legacy.ZGRC013_cmdOff, fz.command_recall],
        exposes: [e.battery(), e.action(['brightness_move_up', 'brightness_move_down', 'brightness_stop', 'on', 'off', 'recall_*'])],
        toZigbee: [],
        whiteLabel: [{vendor: 'RGB Genie', model: 'ZGRC-KEY-013'}],
        meta: {multiEndpoint: true, battery: {dontDividePercentage: true}},
        configure: async (device, coordinatorEndpoint, logger) => {
            await reporting.bind(device.getEndpoint(1), coordinatorEndpoint, ['genOnOff', 'genScenes']);
            await reporting.bind(device.getEndpoint(2), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(3), coordinatorEndpoint, ['genOnOff']);
            await reporting.bind(device.getEndpoint(4), coordinatorEndpoint, ['genOnOff']);
        },
```

**Comment by Koenkk** [comment]
@herveja thanks, updated the code.

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/how_tos/how-to-switch-to-dev-branch.html)
