### ISSUE TITLE
Gledopto GL-SD-001 brightness timeout

### ISSUE THREAD

**Issue by wurststulle** [Koenkk/zigbee-herdsman-converters#3210]
hello, i bought a [Gledopto GL-SD-001](https://www.zigbee2mqtt.io/devices/GL-SD-001.html) the on/off works fine, but setting brightness does not.

```
zigbee2mqtt/0xcc86ecfffebfb2c1/set {"brightness": 250}
zigbee2mqtt/bridge/logging {"level":"debug","message":"Received MQTT message on 'zigbee2mqtt/0xcc86ecfffebfb2c1/set' with data '{\"brightness\": 250}'"}
zigbee2mqtt/bridge/logging {"level":"debug","message":"Publishing 'set' 'brightness' to '0xcc86ecfffebfb2c1'"}
zigbee2mqtt/bridge/logging {"level":"error","message":"Publish 'set' 'state' to '0xcc86ecfffebfb2c1' failed: 'Error: Command 0xcc86ecfffebfb2c1/1 genLevelCtrl.moveToLevelWithOnOff({\"level\":203,\"transtime\":0}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 4138 - 1 - 129 - 8 - 11 after 10000ms)'"}
zigbee2mqtt/bridge/logging {"level":"debug","message":"Error: Command 0xcc86ecfffebfb2c1/1 genLevelCtrl.moveToLevelWithOnOff({\"level\":203,\"transtime\":0}, {\"sendWhenActive\":false,\"timeout\":10000,\"disableResponse\":false,\"disableRecovery\":false,\"disableDefaultResponse\":false,\"direction\":0,\"srcEndpoint\":null,\"reservedBits\":0,\"manufacturerCode\":null,\"transactionSequenceNumber\":null,\"writeUndiv\":false}) failed (Timeout - 4138 - 1 - 129 - 8 - 11 after 10000ms)\n    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)\n    at listOnTimeout (internal/timers.js:557:17)\n    at processTimers (internal/timers.js:500:7)"}
```
i am using  1.21.2. what can i do to debug this?

**Comment by wurststulle** [comment]
fixed by https://github.com/Koenkk/zigbee2mqtt/issues/8349
