### ISSUE TITLE
AssertionError for IKEA Knycklan OTA update

### ISSUE THREAD

**Issue by streambag** [Koenkk/zigbee-herdsman-converters#3253]
First of all: Thank you for all your work! I have been using zigbee2mqtt for quite a while with no problems.

Recently, I ran into a small problem, though. I have a [Knycklan](https://www.ikea.com/se/sv/p/knycklan-elektronisk-diskmaskinsavstaengning-20425724/) dishwasher valve from IKEA that seems to cause problems for zigbee-herdsman. When it is checking for OTA firmware updates, I get the following error:

```
/usr/home/z2m/zigbee2mqtt-1.21.2/node_modules/zigbee-herdsman-converters/lib/ota/tradfri.js:17
    assert(image !== undefined, `No image available for imageType '${imageType}'`);
    ^
AssertionError [ERR_ASSERTION]: No image available for imageType '4355'
    at getImageMeta (/usr/home/z2m/zigbee2mqtt-1.21.2/node_modules/zigbee-herdsman-converters/lib/ota/tradfri.js:17:5)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at isNewImageAvailable (/usr/home/z2m/zigbee2mqtt-1.21.2/node_modules/zigbee-herdsman-converters/lib/ota/common.js:265:18)
    at Object.isUpdateAvailable (/usr/home/z2m/zigbee2mqtt-1.21.2/node_modules/zigbee-herdsman-converters/lib/ota/common.js:256:23)
    at OTAUpdate.onZigbeeEvent (/usr/home/z2m/zigbee2mqtt-1.21.2/lib/extension/otaUpdate.ts:61:31)
```

This causes zigbee2mqtt to crash for me.

It turns out that this device does not have a firmware published on http://fw.ota.homesmart.ikea.net/feed/version_info.json. My guess is that it is not listed there since the original firmware version is still the latest one. For these cases, I think it might be a better approach to consider the current version up to date, rather than asserting.

**Comment by MattWestb** [comment]
Both the valve and remote remote have not getting OTA what i knowing.
I have only getting the image type if they is showing up in the future.
