### ISSUE TITLE
Cannot read property 'bind' of undefined at Object.bind

### ISSUE THREAD

**Issue by hcastanho** [Koenkk/zigbee-herdsman-converters#3290]
Hi

I have this error using the (Lidl) Silvercrest 3 gang switch.  The device is joined but doesn't enable control of the power sockets individually.

I'm using HA OS, and z2m 1.22  EZSP v8

`Failed to configure 'MQTT Extensao Extra', attempt 2 (TypeError: Cannot read property 'bind' of undefined at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:33:24) at Object.configure (/app/dist/util/externally-loaded.js:98:33) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5) at Configure.configure (/app/lib/extension/configure.ts:115:13))`

Thanks

**Comment by hcastanho** [comment]
Changed the path to "zigbee-herdsman-converters/" and I can start zigbee2mqtt. 

![image](https://user-images.githubusercontent.com/426826/140509170-9cf12b09-c8ed-45a2-bc39-6db8a444e88c.png)

Now getting the following error in the log:

![image](https://user-images.githubusercontent.com/426826/140509386-82fa0e87-ef8b-4c32-9022-b4597fef2671.png)
