### ISSUE TITLE
Received an error when joining a smoke detector SMSZB-120

### ISSUE THREAD

**Issue by rotodt** [Koenkk/zigbee-herdsman-converters#3623]
Hi,
received an error message when joining a supoortet smoke detector SMSZB-120. 
Zigbee adapter stay stable since V 1.6.11
See also case [https://github.com/ioBroker/ioBroker.zigbee/issues/1317]
"There seems to be an error in the converter when parsing the responses from the device. The fix @arteck introduced ensures that the zigbee adapter does not crash due to this error, but the error itself remains."

```
2022-01-03 08:28:57.099  - info: zigbee.0 (3160) Configuring 0x0015bc003100bab0 SMSZB-120
2022-01-03 08:28:57.525  - warn: zigbee.0 (3160) Device '0x0015bc003100bab0' announced itself
2022-01-03 08:29:04.688  - error:  zigbee.0 (3160) Error collectOptions for 0015bc003100bab0. Error:  TypeError: Cannot set property 'softwareBuildID' of undefined
at Object.convert (/opt/iobroker/node_modules/zigbee-herdsman-converters/converters/fromZigbee.js:7303:53)
at /opt/iobroker/node_modules/iobroker.zigbee/main.js:463:43
at StatesController.collectOptions (/opt/iobroker/node_modules/iobroker.zigbee/lib/statescontroller.js:146:23)
2022-01-03 08:29:08.979  - info: zigbee.0 (3160) DeviceConfigure successful 0x0015bc003100bab0 
```
![SMSZB-120](https://user-images.githubusercontent.com/96916716/148245142-e391b0df-5cac-4fb9-9215-074e7a415076.jpg)

**Comment by rotodt** [comment]
renew...

**Comment by rotodt** [comment]
renew...

**Comment by Subito** [comment]
I keep finding unfixed issues regarding this smoke sensor, is there something I can help with? I have multiple of those and they still show this behaviour.
