### ISSUE TITLE
Problem implementing batteryVoltage on custom device

### ISSUE THREAD

**Issue by lienbacher** [Koenkk/zigbee-herdsman-converters#3942]
I am working on a battery powered humidity sensor and I am stuck getting batteryVoltage reported via the power cfg cluster. I can get battery percent with no problem, but as soon as I add `await reporting.batteryVoltage(firstEndpoint, overides);` to my converter, device configuration fails with this error:
```
Failed to configure '0x00124b00259c36cb', attempt 2 (Error: ConfigureReporting 0x00124b00259c36cb/8 genPowerCfg([{"attribute":"batteryVoltage","minimumReportInterval":0,"maximumReportInterval":21600,"reportableChange":0}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'INVALID_VALUE')
    at Endpoint.checkStatus (/Users/username/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28)
    at Endpoint.configureReporting (/Users/username/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:649:22)
    at Object.batteryVoltage (/Users/username/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/reporting.js:59:9)
    at Object.configure (/Users/username/zigbee2mqtt/dist/util/externally-loaded.js:20:9)
    at Configure.configure (/Users/username/zigbee2mqtt/lib/extension/configure.ts:115:13))
```

Here is the full converter
```
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const tz = require('zigbee-herdsman-converters/converters/toZigbee');
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const extend = require('zigbee-herdsman-converters/lib/extend');
const e = exposes.presets;
const ea = exposes.access;

const definition = {
    zigbeeModel: ['Moisture Sensor'], // The model ID from: Device with modelID 'lumi.sens' is not supported.
    model: 'MS1', // Vendor model number, look on the device for a model number
    vendor: '0xD', // Vendor of the device (only used for documentation and startup logging)
    description: 'A simple battery powered sensor', // Description of the device, copy from vendor site. (only used for documentation and startup logging)
    fromZigbee: [fz.temperature, fz.humidity, fz.battery], // We will add this later
    toZigbee: [], // Should be empty, unless device can be controlled (e.g. lights, switches).
    configure: async (device, coordinatorEndpoint, logger) => {
        const firstEndpoint = device.getEndpoint(8);
        await reporting.bind(firstEndpoint, coordinatorEndpoint, ['genPowerCfg', 'msTemperatureMeasurement', 'msRelativeHumidity']);
        const overides = {min: 0, max: 21600, change: 0};
        await reporting.batteryVoltage(firstEndpoint, overides);
        await reporting.batteryPercentageRemaining(firstEndpoint, overides);
        await reporting.temperature(firstEndpoint, overides);
        await reporting.humidity(firstEndpoint, overides);
    },
    exposes: [e.battery(), e.temperature(), e.humidity()], // Defines what this device exposes, used for e.g. Home Assistant discovery and in the frontend
};

module.exports = definition;
``` 

The device is based on CC2652RB and Z-Stack 5.40. I noticed the batteryVoltage is not reportable by ZCL standard, and that the code in lib/reporting.js is actually not binding a report, but just reads the cluster. This leads me to think everything is configured correctly, but it at the same time leaves me clueless of why configuration fails. Humidity, Temperature and Battery percent are working just fine. 

Any input is very welcome.

**Comment by lienbacher** [comment]
I fixed it by editing  <sdk directory>\source\ti\zstack\ZCL.js in the Z-Stack SDK. I changed the _reportable filed of ATTRID_POWER_CONFIGURATION_BATTERY_VOLTAGE to true and rebuilt the project inside CCS.
