### ISSUE TITLE
Niko 170-33505 (Connected socket outlet) fails to configure

### ISSUE THREAD

**Issue by sjorge** [Koenkk/zigbee-herdsman-converters#4028]
I just got myself a Niko 170-33505 (Connected socket outlet) for testing and it fails to configure.

```
Failed to configure '0x086bd7fffeedf850', attempt 1 (Error: Read 0x086bd7fffeedf850/1 haElectricalMeasurement(["acFrequencyDivisor","acFrequencyMultiplier"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') at Endpoint.checkStatus (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28) at Endpoint.read (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:480:22) at runMicrotasks (<anonymous>) at processTicksAndRejections (node:internal/process/task_queues:96:5) at Object.readEletricalMeasurementMultiplierDivisors (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/lib/reporting.js:25:5) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/devices/niko.js:19:13) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:115:13))
```

My lunch break is over, I'll dig a bit deeper after work.

**Comment by sjorge** [comment]
OK it was bugging me, I have a fix, let me polish it.
