### ISSUE TITLE
MG-AUWS01 Left/Right reversed

### ISSUE THREAD

**Issue by aidbish** [Koenkk/zigbee-herdsman-converters#4551]
i have a couple of MG-AUWS01 2 gang switches from Nue/3A with zigbee id FNB56-SKT1DHG1.4
Devices paired without issue, i can see them in Dashboard and in HA without problem
The problem i have is left toggle in dashboard/HA corresponds the to the right switch and right toggle in Dashboard/HA corresponds with the left socket on the device

Is there anyway to reverse this
Looking at models online with same model number and zigbee id, there could potentially be 2 types, 1 with the switches on the outside of the sockets and 1 with the switches to the inside of the sockets (if that makes sense)

**Comment by Koenkk** [comment]
Fixed!

Changes will be available in the dev branch in a few hours from now. (https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html)

**Comment by aidbish** [comment]
Excellent, will test it out

**Comment by aidbish** [comment]
@Koenkk 
I have attempted to use the latest-dev branch but it doesn't seem to start. Iff i go back to latest it starts without issue

i have enabled debug in herdman and output below

i seem to be having the same issue using the latest-dev image, using tag latest works without issue

enabled herdmen debug and recieved the following

Using '/app/data' as data directory
Zigbee2MQTT:info 2022-08-23 10:07:03: Logging to console and directory: '/app/data/log/2022-08-23.10-07-03' filename: log.txt
Zigbee2MQTT:info 2022-08-23 10:07:03: Starting Zigbee2MQTT version 1.27.0-dev (commit #9e6b408)
Zigbee2MQTT:info 2022-08-23 10:07:03: Starting zigbee-herdsman (0.14.48)
2022-08-23T00:07:04.241Z zigbee-herdsman:adapter Path '/dev/ttyUSB0' is valid for 'EZSPAdapter'
2022-08-23T00:07:04.241Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[24]},"serialPort":{"path":"/dev/ttyUSB0"},"databasePath":"/app/data/database.db","databaseBackupPath":"/app/data/database.db.backup","backupPath":"/app/data/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2022-08-23T00:07:04.242Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with /dev/ttyUSB0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2022-08-23T00:07:04.245Z zigbee-herdsman:adapter:ezsp:uart Serialport opened
2022-08-23T00:07:04.245Z zigbee-herdsman:adapter:ezsp:uart Uart reseting
2022-08-23T00:07:04.245Z zigbee-herdsman:adapter:ezsp:uart --> Write reset
2022-08-23T00:07:04.245Z zigbee-herdsman:adapter:ezsp:uart --> [1ac038bc7e]
Zigbee2MQTT:error 2022-08-23 10:07:15: Failed to call 'Frontend' 'stop' (TypeError: Cannot read properties of null (reading 'clients')
at Frontend.stop (/app/lib/extension/frontend.ts:59:39)
at Controller.callExtensions (/app/lib/controller.ts:315:40)
at Controller.stop (/app/lib/controller.ts:192:9)
at stop (/app/index.js:113:5)
at process.handleQuit (/app/index.js:119:9))
Zigbee2MQTT:error 2022-08-23 10:07:15: Not connected to MQTT server!
Zigbee2MQTT:error 2022-08-23 10:07:15: Cannot send message: topic: 'zigbee2mqtt/bridge/state', payload: '{"state":"offline"}
Zigbee2MQTT:info 2022-08-23 10:07:15: Disconnecting from MQTT server
TypeError: Cannot read properties of undefined (reading 'end')
at MQTT.disconnect (/app/lib/mqtt.ts:126:21)
at Controller.stop (/app/lib/controller.ts:197:9)
at stop (/app/index.js:113:5)
at process.handleQuit (/app/index.js:119:9)
Using '/app/data' as data directory
Zigbee2MQTT:info 2022-08-23 10:08:08: Logging to console and directory: '/app/data/log/2022-08-23.10-08-08' filename: log.txt
Zigbee2MQTT:info 2022-08-23 10:08:08: Starting Zigbee2MQTT version 1.27.0-dev (commit #9e6b408)
Zigbee2MQTT:info 2022-08-23 10:08:08: Starting zigbee-herdsman (0.14.48)
2022-08-23T00:08:08.753Z zigbee-herdsman:adapter Path '/dev/ttyUSB0' is valid for 'EZSPAdapter'
2022-08-23T00:08:08.753Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[24]},"serialPort":{"path":"/dev/ttyUSB0"},"databasePath":"/app/data/database.db","databaseBackupPath":"/app/data/database.db.backup","backupPath":"/app/data/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2022-08-23T00:08:08.754Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with /dev/ttyUSB0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2022-08-23T00:08:08.757Z zigbee-herdsman:adapter:ezsp:uart Serialport opened
2022-08-23T00:08:08.757Z zigbee-herdsman:adapter:ezsp:uart Uart reseting
2022-08-23T00:08:08.757Z zigbee-herdsman:adapter:ezsp:uart --> Write reset
2022-08-23T00:08:08.758Z zigbee-herdsman:adapter:ezsp:uart --> [1ac038bc7e]

**Comment by Koenkk** [comment]
@aidbish what setup or you using? Docker/ HA addon?
