### ISSUE TITLE
Last update broke Lixee OTA check, error: TypeError: releasesLIST.sort is not a function or its return value is not iterable)

### ISSUE THREAD

**Issue by JeanMars** [Koenkk/zigbee-herdsman-converters#5082]
Hi,

1.28.3 and 1.28.4 of zigbee2mqtt lead to the following error when an OTA check is performed (cf.log):
[log.txt](https://github.com/Koenkk/zigbee-herdsman-converters/files/10149388/log.txt)
Basically:
debug 2022-12-02 23:42:45: Received MQTT message on 'zigbee2mqtt/bridge/request/device/ota_update/check' with data '{"id":"0x00158d0006a400de","transaction":"itf4l-4"}'
info  2022-12-02 23:42:45: Checking if update available for '0x00158d0006a400de'
debug 2022-12-02 23:42:45: Check if update available for '0x00158d0006a400de' (ZLinky_TIC )
debug 2022-12-02 23:42:45: Using endpoint '1'
debug 2022-12-02 23:42:45: Received Zigbee message from '0x00158d0006a400de', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":12,"imageType":1,"manufacturerCode":4151}' from endpoint 1 with groupID 0
debug 2022-12-02 23:42:45: Got OTA request '{"fieldControl":0,"manufacturerCode":4151,"imageType":1,"fileVersion":12}'
info  2022-12-02 23:42:46: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"0x00158d0006a400de"},"error":"Failed to check if update available for '0x00158d0006a400de' (releasesLIST.sort is not a function or its return value is not iterable)","status":"error","transaction":"itf4l-4"}'
error 2022-12-02 23:42:46: Failed to check if update available for '0x00158d0006a400de' (releasesLIST.sort is not a function or its return value is not iterable)
debug 2022-12-02 23:42:46: TypeError: releasesLIST.sort is not a function or its return value is not iterable
    at getImageMeta (/app/node_modules/zigbee-herdsman-converters/lib/ota/lixee.js:18:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at isNewImageAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:265:18)
    at Object.isUpdateAvailable (/app/node_modules/zigbee-herdsman-converters/lib/ota/common.js:256:23)
    at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:192:39)

Cheers,
Jean

**Comment by Koenkk** [comment]
Let's continue in https://github.com/Koenkk/zigbee2mqtt/issues/15328
