### ISSUE TITLE
missing states in ioBroker for Lidl HG07834C

### ISSUE THREAD

**Issue by bruno4712** [Koenkk/zigbee-herdsman-converters#5826]
this Zigbee device can't used any further because I get now these errors in the ioBroker protokol: 

https://www.zigbee2mqtt.io/devices/HG07834C.html

zigbee-herdsman-converters V15.13.0

zigbee.0	2023-05-31 14:35:08.363	error	No state available for 'HG07834C' with key 'state'
zigbee.0	2023-05-31 14:33:06.091	error	No state available for 'HG07834C' with key 'color'
zigbee.0	2023-05-31 14:33:06.070	error	Device 0x9035eafffe5aef07 "HG07834C" not described in statesMapping.
zigbee.0	2023-05-31 14:32:30.488	info	Zigbee started
zigbee.0	2023-05-31 14:32:30.049	info	--> transmitPower : high
zigbee.0	2023-05-31 14:32:29.937	info	Unable to disable LED, unsupported function.
zigbee.0	2023-05-31 14:32:29.935	info	Disable LED
zigbee.0	2023-05-31 14:32:29.921	info	Coordinator firmware version: {"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20211115}}
zigbee.0	2023-05-31 14:32:29.092	info	Installed Version: iobroker.zigbee@1.8.10
zigbee.0	2023-05-31 14:32:24.828	info	Starting Zigbee npm ...
zigbee.0	2023-05-31 14:32:24.808	info	delete old Backup files. keep only last 10
zigbee.0	2023-05-31 14:32:23.988	info	starting. Version 1.8.10 in /opt/iobroker/node_modules/iobroker.zigbee, node: v16.20.0, js-controller: 4.0.24
zigbee.0	2023-05-31 14:31:20.842	info	Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
zigbee.0	2023-05-31 14:31:20.655	info	Got terminate signal TERMINATE_YOURSELF
zigbee.0	2023-05-31 14:31:20.601	info	Zigbee: disabling joining new devices.

The converter was update like this. It is written in my update made yesterday.
https://github.com/ioBroker/ioBroker.zigbee/issues/1735

**Comment by bruno4712** [comment]
This error is occurred again. Adapter will be terminated with "Cannot read properties of undefined (reading 'mapped') "

2023-06-21 16:07:29.050 - error: zigbee.0 (15132) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
--
2023-06-21 16:07:29.052 - error: zigbee.0 (15132) unhandled promise rejection: Cannot read properties of undefined (reading 'mapped')
2023-06-21 16:07:29.055 - error: zigbee.0 (15132) TypeError: Cannot read properties of undefined (reading 'mapped')
at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:571:36)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-06-21 16:07:29.056 - error: zigbee.0 (15132) Cannot read properties of undefined (reading 'mapped')
2023-06-21 16:07:29.070 - info: zigbee.0 (15132) cleaned everything up...
2023-06-21 16:07:29.160 - info: zigbee.0 (15132) Zigbee: disabling joining new devices.
2023-06-21 16:07:29.572 - info: zigbee.0 (15132) terminating
2023-06-21 16:07:29.574 - warn: zigbee.0 (15132) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-06-21 16:07:30.176 - error: host.iobrokertc Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
2023-06-21 16:07:30.177 - error: host.iobrokertc Caught by controller[1]: TypeError: Cannot read properties of undefined (reading 'mapped')
2023-06-21 16:07:30.177 - error: host.iobrokertc Caught by controller[1]: at Zigbee.publishFromState (/opt/iobroker/node_modules/iobroker.zigbee/main.js:571:36)
2023-06-21 16:07:30.178 - error: host.iobrokertc Caught by controller[1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-06-21 16:07:30.178 - error: host.iobrokertc instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

**Comment by Koenkk** [comment]
I think this has to be fixed in iobroker

**Comment by bruno4712** [comment]
Are the devices not declared in herdsman adapter? I am not so fit to understand the JS code.

**Comment by Koenkk** [comment]
I think this part is handled in iobroker

**Comment by bruno4712** [comment]
here are some other issues. https://github.com/ioBroker/ioBroker.zigbee/issues/1735 Must all devices be declared in iobroker?

**Comment by bruno4712** [comment]
will the devices not be declared in the herdsman adapter? I am not so fit to read the JS code.

**Comment by Koenkk** [comment]
Device is declared in herdsman, this will make the device be marked as supported (in your case it is detected as `HG07834C ` so its supported). I think the `No state available for` error has to be fixed in iobroker (please correct me if wrong @arteck )

**Comment by arteck** [comment]
> Device is declared in herdsman, this will make the device be marked as supported (in your case it is detected as `HG07834C ` so its supported). I think the `No state available for` error has to be fixed in iobroker (please correct me if wrong @arteck )

yes you are right...

**Comment by bruno4712** [comment]
Upgrade to Zigbee v1.8.16 will help to fix this now. I hope so. No dump occurs now.
