### ISSUE TITLE
Previous state in Tuya smart switch TS0004

### ISSUE THREAD

**Issue by ummarbhutta** [Koenkk/zigbee-herdsman-converters#6140]
Hi I have a Tuya smart switch module, which I am integrating with Zigbee2MQTT --> HA.

### Environment

- Docker based Zigbee2MQTT - v1.32.2
- RPi 4 - with 4Gb RAM
- Raspbian 64-bit OS

### Device Info
![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/5959561/f6d74a84-fd02-4a73-8f62-31dd8242221a)

### Good part

- Device detected successfully - Plug and Play
- All 4 switches can be controlled from Z2M frontend and HA

### Bad part

- Device memory state function is not working, although it is stated that it is a supported feature

![image](https://github.com/Koenkk/zigbee-herdsman-converters/assets/5959561/e3fa4588-3e86-4185-8247-c58d352b19a6)

When I try to set the `power_on_behavior`, I get exceptions on console with status `UNSUPPORTED_ATTRIBUTE`

Please see the Zigbee2MQTT debug logs and herdsman logs when setting `power_on_behavior` to `previous`

```
homeautomation-lc-zigbee2mqtt-1    | Zigbee2MQTT:debug 2023-09-05 11:48:56: Received MQTT message on 'homeassistant/0xaaaaaaaaaaaaaaaa/l1/set/power_on_behavior_l1' with data 'previous'
homeautomation-lc-zigbee2mqtt-1    | Zigbee2MQTT:debug 2023-09-05 11:48:56: Publishing 'set' 'power_on_behavior' to '0xaaaaaaaaaaaaaaaa'
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.826Z zigbee-herdsman:controller:endpoint Write 0xaaaaaaaaaaaaaaaa/1 manuSpecificTuya_3({"powerOnBehavior":2}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.827Z zigbee-herdsman:adapter:zStack:adapter sendZclFrameToEndpointInternal 0xaaaaaaaaaaaaaaaa:51005/1 (0,0,1)
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.828Z zigbee-herdsman:adapter:zStack:znp:SREQ --> AF - dataRequest - {"dstaddr":51005,"destendpoint":1,"srcendpoint":1,"clusterid":57345,"transid":57,"options":0,"radius":30,"len":7,"data":{"type":"Buffer","data":[16,32,2,16,208,48,2]}}
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.828Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,17,36,1,61,199,1,1,1,224,57,0,30,7,16,32,2,16,208,48,2,207]
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.836Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,100,1,0,100]
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.836Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,100,1,0,100]
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.836Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 4 - 1 - [0] - 100
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.836Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- AF - dataRequest - {"status":0}
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.837Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.839Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,68,128,0,1,57,255]
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.839Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,68,128,0,1,57,255]
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.839Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 2 - 4 - 128 - [0,1,57] - 255
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.839Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - dataConfirm - {"status":0,"endpoint":1,"transid":57}
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.840Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.849Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,26,68,129,0,0,1,224,61,199,1,1,0,171,0,43,130,138,0,0,6,24,32,4,134,16,208,61,199,29,215]
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.849Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,26,68,129,0,0,1,224,61,199,1,1,0,171,0,43,130,138,0,0,6,24,32,4,134,16,208,61,199,29,215]
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.849Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 26 - 2 - 4 - 129 - [0,0,1,224,61,199,1,1,0,171,0,43,130,138,0,0,6,24,32,4,134,16,208,61,199,29] - 215
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.850Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- AF - incomingMsg - {"groupid":0,"clusterid":57345,"srcaddr":51005,"srcendpoint":1,"dstendpoint":1,"wasbroadcast":0,"linkquality":171,"securityuse":0,"timestamp":9077291,"transseqnumber":0,"len":6,"data":{"type":"Buffer","data":[24,32,4,134,16,208]}}
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.852Z zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":32,"manufacturerCode":null,"commandIdentifier":4},"Payload":[{"status":134,"attrId":53264}],"Command":{"ID":4,"name":"writeRsp","parameters":[{"name":"status","type":32},{"name":"attrId","type":33,"conditions":[{"type":"statusNotEquals","value":0}]}]}},"address":51005,"endpoint":1,"linkquality":171,"groupID":0,"wasBroadcast":false,"destinationEndpoint":1}'
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.853Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
homeautomation-lc-zigbee2mqtt-1    | 2023-09-05T06:48:56.853Z zigbee-herdsman:controller:endpoint Write 0xaaaaaaaaaaaaaaaa/1 manuSpecificTuya_3({"powerOnBehavior":2}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
homeautomation-lc-zigbee2mqtt-1    | Zigbee2MQTT:error 2023-09-05 11:48:56: Publish 'set' 'power_on_behavior' to '0xaaaaaaaaaaaaaaaa' failed: 'Error: Write 0xaaaaaaaaaaaaaaaa/1 manuSpecificTuya_3({"powerOnBehavior":2}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')'
homeautomation-lc-zigbee2mqtt-1    | Zigbee2MQTT:debug 2023-09-05 11:48:56: Error: Write 0xaaaaaaaaaaaaaaaa/1 manuSpecificTuya_3({"powerOnBehavior":2}, {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
homeautomation-lc-zigbee2mqtt-1    |     at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:419:28)
homeautomation-lc-zigbee2mqtt-1    |     at Endpoint.write (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:488:22)
homeautomation-lc-zigbee2mqtt-1    |     at Object.convertSet (/app/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:723:13)
homeautomation-lc-zigbee2mqtt-1    |     at Publish.onMQTTMessage (/app/lib/extension/publish.ts:248:36)
```

Any help is appreciated to explain the issue what is happening here.

**Comment by emandtf** [comment]
It just seems that "power_on_behaviour" is not supported by your version/firmware.

**Comment by ummarbhutta** [comment]
Thanks for the update. But I tried the same device with ZHA and `power_on_behaviour` is working fine there.

**Comment by emandtf** [comment]
Maybe in your model/version/firmware the PowerOnBehaviour is not under "manuSpecificTuya_3" but maybe on a different Cluster that ZHA has instead well indexed. 
Don't know exactly, but someone that owns same device could help you more than me.
