### ISSUE TITLE
Xiaomi Aqara D1 3 gang not reporting state (QBKG26LM)

### ISSUE THREAD

**Issue by yayeetye** [Koenkk/zigbee-herdsman-converters#6477]
I have multiple Aqara D1 2gang and 3gang switches. with neutral.
all the 3gang switches (QBKG26LM) are not updating in z2m or in home assistant. I can press the switch on and off just fine and control them in home assistant fine.
but if I turn on the switch physically. it is not updating the state in z2m.

I believe its the same issue as https://github.com/Koenkk/zigbee2mqtt/issues/5106

**Comment by yayeetye** [comment]
I have tried to modify the external converters from https://github.com/Koenkk/zigbee2mqtt/issues/5106.
However, I am getting the error 
`/app/node_modules/zigbee-herdsman-converters/index.js:79
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:79:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)`
    in home assistant.
