### ISSUE TITLE
 Aqara ZNJLBL01LM (lumi.curtain.acn002) problem after latest dev updates

### ISSUE THREAD

**Issue by mamrai1** [Koenkk/zigbee-herdsman-converters#7440]
(Error: Device 0x54ef4410004a7065 has no input cluster manuSpecificLumi at getEndpointsWithCluster (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:29:15) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:65:55) at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:110:23) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:160:27) at Configure.configure (/app/lib/extension/configure.ts:121:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

The device works when selecting up/down/specific position
Zigbee2MQTT version
1.36.1-dev commit: df23240
Coordinator type
EZSP v13
Coordinator revision
7.4.2.0 build 0
Frontend version
0.6.163
19.27.0
0.43.0

**Comment by mamrai1** [comment]
debug:
[2024-04-25 18:52:44] info: 	z2m: Configuring 'Right Kitchen Blind'
[2024-04-25 18:52:44] debug: 	zh:controller:database: Writing database to '/app/data/database.db'
[2024-04-25 18:52:44] debug: 	zh:controller:endpoint: ZCL command 0x54ef4410004a59b5/1 manuSpecificLumi.read([1034], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false})
[2024-04-25 18:52:44] debug: 	zh:ezsp: sendZclFrameToEndpointInternal 0x54ef4410004a59b5:30967/1 (0,0,1), timeout=10000
[2024-04-25 18:52:44] debug: 	z2m: Received Zigbee message from 'Right Kitchen Blind', type 'commandQueryNextImageRequest', cluster 'genOta', data '{"fieldControl":0,"fileVersion":3870,"imageType":14976,"manufacturerCode":4447}' from endpoint 1 with groupID 0
[2024-04-25 18:52:44] debug: 	z2m: MQTT publish: topic 'zigbee2mqtt/Right Kitchen Blind', payload '{"battery":100,"charging_status":false,"device_temperature":26,"last_seen":"2024-04-25T18:52:44+03:00","linkquality":112,"motor_speed":"high","motor_state":"pause","position":0,"power_outage_count":0,"running":false,"state":"OFF","update":{"installed_version":3870,"latest_version":3870,"state":"idle"},"update_available":null}'
[2024-04-25 18:52:44] debug: 	zh:ezsp:ezsp: ==> sendUnicast: {"type":0,"indexOrDestination":30967,"apsFrame":{"profileId":260,"sequence":63,"clusterId":64704,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":256},"messageTag":64,"message":{"type":"Buffer","data":[20,95,17,22,0,10,4]}}
[2024-04-25 18:52:44] debug: 	zh:ezsp:ezsp: ==> {"_cls_":"sendUnicast","_id_":52,"_isRequest_":true,"type":0,"indexOrDestination":30967,"apsFrame":{"profileId":260,"sequence":63,"clusterId":64704,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":256},"messageTag":64,"message":{"type":"Buffer","data":[20,95,17,22,0,10,4]}}
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: --> DATA (3,5,0): 830001340000f7780401c0fc0101000100003f4007145f1116000a04
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: --> [35c121a9602a154521904be5565493499d4e2794adc973d4ecd06383f87d33597e]
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: -?- waiting (4)
[2024-04-25 18:52:44] debug: 	zhc:ota:common: Got request '{"fieldControl":0,"manufacturerCode":4447,"imageType":14976,"fileVersion":3870}'
[2024-04-25 18:52:44] debug: 	zhc:ota:common: Is new image available for '0x54ef4410004a59b5' (lumi.curtain.acn002), current '{"fieldControl":0,"manufacturerCode":4447,"imageType":14976,"fileVersion":3870}'
[2024-04-25 18:52:44] debug: 	zhc:ota: Getting image metadata for 'lumi.curtain.acn002'
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: <-- [54c1a1a9602a1546d1827e]
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: <-- DATA (5,4,0): 54c1a1a9602a1546d1827e
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: --> ACK  (6)
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: --> [8610be7e]
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: <-- ACK (4): 54c1a1a9602a1546d1827e
[2024-04-25 18:52:44] debug: 	zh:ezsp:ezsp: <== Frame: 838001340000f4
[2024-04-25 18:52:44] debug: 	zh:ezsp:ezsp: <== 0x34: {"_cls_":"sendUnicast","_id_":52,"_isRequest_":false,"status":0,"sequence":244}
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: -+- waiting (4) success
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: <-- [64c1b1a96b2a154521904be5565493499d4e275fadce6781767e]
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: <-- DATA (6,4,0): 64c1b1a96b2a154521904be5565493499d4e275fadce6781767e
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: --> ACK  (7)
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: --> [87009f7e]
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: <-- ACK (4): 64c1b1a96b2a154521904be5565493499d4e275fadce6781767e
[2024-04-25 18:52:44] debug: 	zh:ezsp:ezsp: <== Frame: 8390013f0000f7780401c0fc010100010000f4400000
[2024-04-25 18:52:44] debug: 	zh:ezsp:ezsp: <== 0x3f: {"_cls_":"messageSentHandler","_id_":63,"_isRequest_":false,"type":0,"indexOrDestination":30967,"apsFrame":{"profileId":260,"sequence":244,"clusterId":64704,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":256},"messageTag":64,"status":0,"message":{"type":"Buffer","data":[]}}
[2024-04-25 18:52:44] debug: 	zhc:ota: Downloaded main index
[2024-04-25 18:52:44] debug: 	zhc:ota:common: Is new image available for '0x54ef4410004a59b5' (lumi.curtain.acn002), latest meta '{"fileVersion":3870,"fileSize":296304,"url":"https://github.com/Koenkk/zigbee-OTA/raw/master/images/Lumi/20221009111923_OTA_lumi.curtain.acn002_0.0.0_1530_20221009_6C9C3D.ota","sha512":"2436508af75c9b0139d304f8b62ce5579ad721fffec74967db7256bb030f47f8172a2b2ef2003eede1c868410b007ac6c89b3936dd44dffd07fdff155bcb7451"}'
[2024-04-25 18:52:44] debug: 	zhc:ota:common: Update available for '0x54ef4410004a59b5' (lumi.curtain.acn002): NO
[2024-04-25 18:52:44] info: 	z2m: No update available for 'Right Kitchen Blind'
[2024-04-25 18:52:44] debug: 	z2m: MQTT publish: topic 'zigbee2mqtt/Right Kitchen Blind', payload '{"battery":100,"charging_status":false,"device_temperature":26,"last_seen":"2024-04-25T18:52:44+03:00","linkquality":112,"motor_speed":"high","motor_state":"pause","position":0,"power_outage_count":0,"running":false,"state":"OFF","update":{"installed_version":3870,"latest_version":3870,"state":"idle"},"update_available":null}'
[2024-04-25 18:52:44] debug: 	z2m: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/ota_update/check', payload '{"data":{"id":"Right Kitchen Blind","updateAvailable":false},"status":"ok","transaction":"34ov9-5"}'
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: <-- [74c1b1a97d312a15b65854b624ab5593499c7353127d3ab69874f7da3c98ea7f35a3ebedba6b0eab7e]
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: <-- DATA (7,4,0): 74c1b1a9112a15b65854b624ab5593499c7353121ab69874f7da3c98ea7f35a3ebedba6b0eab7e
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: --> ACK  (0)
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: --> [8070787e]
[2024-04-25 18:52:44] debug: 	zh:ezsp:uart: <-- ACK (4): 74c1b1a9112a15b65854b624ab5593499c7353121ab69874f7da3c98ea7f35a3ebedba6b0eab7e
[2024-04-25 18:52:44] debug: 	zh:ezsp:ezsp: <== Frame: 8390014500000401c0fc0101000100003d74b9f778ffff0a1c5f1116010a0400206404
[2024-04-25 18:52:44] debug: 	zh:ezsp:ezsp: <== 0x45: {"_cls_":"incomingMessageHandler","_id_":69,"_isRequest_":false,"type":0,"apsFrame":{"profileId":260,"sequence":61,"clusterId":64704,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":256},"lastHopLqi":116,"lastHopRssi":-71,"sender":30967,"bindingIndex":255,"addressIndex":255,"message":{"type":"Buffer","data":[28,95,17,22,1,10,4,0,32,100]}}
[2024-04-25 18:52:44] debug: 	zh:ezsp: processMessage: {"messageType":0,"apsFrame":{"profileId":260,"sequence":61,"clusterId":64704,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":256},"lqi":116,"rssi":-71,"sender":30967,"bindingIndex":255,"addressIndex":255,"message":{"type":"Buffer","data":[28,95,17,22,1,10,4,0,32,100]}}
[2024-04-25 18:52:44] debug: 	zh:controller: Received payload: clusterID=64704, address=30967, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=116, frame={"header":{"frameControl":{"frameType":0,"manufacturerSpecific":true,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"manufacturerCode":4447,"transactionSequenceNumber":22,"commandIdentifier":1},"payload":[{"attrId":1034,"status":0,"dataType":32,"attrData":100}],"command":{"ID":1,"name":"readRsp","parameters":[{"name":"attrId","type":33},{"name":"status","type":32},{"name":"dataType","type":32,"conditions":[{"type":"statusEquals","value":0}]},{"name":"attrData","type":1000,"conditions":[{"type":"statusEquals","value":0}]}]}}
[2024-04-25 18:52:44] debug: 	z2m: Received Zigbee message from 'Right Kitchen Blind', type 'readResponse', cluster 'manuSpecificLumi', data '{"1034":100}' from endpoint 1 with groupID 0
[2024-04-25 18:52:44] debug: 	zhc:lumi: ZNJLBL01LM: Processed data into payload {"battery":100}
[2024-04-25 18:52:44] debug: 	z2m: MQTT publish: topic 'zigbee2mqtt/Right Kitchen Blind', payload '{"battery":100,"charging_status":false,"device_temperature":26,"last_seen":"2024-04-25T18:52:44+03:00","linkquality":116,"motor_speed":"high","motor_state":"pause","position":0,"power_outage_count":0,"running":false,"state":"OFF","update":{"installed_version":3870,"latest_version":3870,"state":"idle"},"update_available":null}'
[2024-04-25 18:52:44] debug: 	zh:controller:database: Writing database to '/app/data/database.db'
[2024-04-25 18:52:44] error: 	z2m: Failed to configure 'Right Kitchen Blind', attempt 2 (Error: Device 0x54ef4410004a59b5 has no input cluster manuSpecificLumi
    at getEndpointsWithCluster (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:29:15)
    at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:65:55)
    at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:110:23)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:160:27)
    at Configure.configure (/app/lib/extension/configure.ts:121:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

**Comment by mamrai1** [comment]
tried also the new ember driver:
[2024-04-25 19:07:53] info: 	z2m: Configuring 'Left Kitchen Blind'
[2024-04-25 19:07:53] debug: 	zh:controller:database: Writing database to '/app/data/database.db'
[2024-04-25 19:07:53] debug: 	zh:controller:endpoint: ZCL command 0x54ef4410004a7065/1 manuSpecificLumi.read([1034], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4447,"transactionSequenceNumber":null,"writeUndiv":false})
[2024-04-25 19:07:53] debug: 	zh:ember:queue: Status queue=1 priorityQueue=0.
[2024-04-25 19:07:53] debug: 	z2m: MQTT publish: topic 'zigbee2mqtt/Left Kitchen Blind', payload '{"battery":100,"charging_status":false,"device_temperature":25,"last_seen":"2024-04-25T19:07:53+03:00","linkquality":112,"motor_speed":"high","motor_state":"pause","position":0,"power_outage_count":0,"running":false,"state":"OFF","update":{"installed_version":3870,"latest_version":3870,"state":"idle"},"update_available":null}'
[2024-04-25 19:07:53] debug: 	zh:ember: ~~~> [ZCL to=18049 apsFrame={"profileId":260,"clusterId":64704,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":0} header={"frameControl":{"reservedBits":0,"frameType":0,"direction":0,"disableDefaultResponse":true,"manufacturerSpecific":true},"manufacturerCode":4447,"transactionSequenceNumber":5,"commandIdentifier":0}]
[2024-04-25 19:07:53] debug: 	zh:ember:ezsp: ===> [FRAME: ID=52:"SEND_UNICAST" Seq=62 Len=28]
[2024-04-25 19:07:53] debug: 	zh:ember:uart:ash: ---> [FRAME type=DATA frmTx=6 frmRx=5]
[2024-04-25 19:07:53] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-04-25 19:07:53] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=7]
[2024-04-25 19:07:53] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=7 frmNum=5] Added to rxQueue
[2024-04-25 19:07:53] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=6]
[2024-04-25 19:07:53] debug: 	zh:ember:ezsp: <=== [FRAME: ID=52:"SEND_UNICAST" Seq=62 Len=7]
[2024-04-25 19:07:53] debug: 	zh:ember:ezsp: ~~~> [SENT type=DIRECT apsSequence=55 messageTag=11 status=SUCCESS]
[2024-04-25 19:07:54] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-04-25 19:07:54] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=7]
[2024-04-25 19:07:54] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=7 frmNum=6] Added to rxQueue
[2024-04-25 19:07:54] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=7]
[2024-04-25 19:07:54] debug: 	zh:ember:ezsp: <=== [FRAME: ID=69:"INCOMING_MESSAGE_HANDLER" Seq=62 Len=40]
[2024-04-25 19:07:54] debug: 	zh:ember:ezsp: ezspIncomingMessageHandler(): callback called with: [type=UNICAST], [apsFrame={"profileId":260,"clusterId":19,"sourceEndpoint":1,"destinationEndpoint":1,"options":256,"groupId":0,"sequence":104}], [lastHopLqi=112], [lastHopRssi=184], [sender=18049], [bindingIndex=255], [addressIndex=255], [messageContents=18600a550021010000f02304000007]
[2024-04-25 19:07:54] debug: 	zh:controller: Received payload: clusterID=19, address=18049, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=112, frame={"header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"manufacturerCode":null,"transactionSequenceNumber":96,"commandIdentifier":10},"payload":[{"attrId":85,"dataType":33,"attrData":1},{"attrId":61440,"dataType":35,"attrData":117440516}],"command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}}
[2024-04-25 19:07:54] debug: 	z2m: Received Zigbee message from 'Left Kitchen Blind', type 'attributeReport', cluster 'genMultistateOutput', data '{"61440":117440516,"presentValue":1}' from endpoint 1 with groupID 0
[2024-04-25 19:07:54] debug: 	z2m: MQTT publish: topic 'zigbee2mqtt/Left Kitchen Blind', payload '{"battery":100,"charging_status":false,"device_temperature":25,"last_seen":"2024-04-25T19:07:54+03:00","linkquality":112,"motor_speed":"high","motor_state":"rising","position":0,"power_outage_count":0,"running":true,"state":"OFF","update":{"installed_version":3870,"latest_version":3870,"state":"idle"},"update_available":null}'
[2024-04-25 19:07:54] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-04-25 19:07:54] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=7]
[2024-04-25 19:07:54] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=7 frmNum=7] Added to rxQueue
[2024-04-25 19:07:54] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=0]
[2024-04-25 19:07:54] debug: 	zh:ember:ezsp: <=== [FRAME: ID=63:"MESSAGE_SENT_HANDLER" Seq=62 Len=29]
[2024-04-25 19:07:54] debug: 	zh:ember:ezsp: ezspMessageSentHandler(): callback called with: [type=DIRECT], [indexOrDestination=18049], [apsFrame={"profileId":260,"clusterId":64704,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":55}], [messageTag=11], [status=SUCCESS], [messageContents=145f1105000a04]
[2024-04-25 19:07:54] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-04-25 19:07:54] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=7]
[2024-04-25 19:07:54] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=7 frmNum=0] Added to rxQueue
[2024-04-25 19:07:54] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=1]
[2024-04-25 19:07:54] debug: 	zh:ember:ezsp: <=== [FRAME: ID=69:"INCOMING_MESSAGE_HANDLER" Seq=62 Len=35]
[2024-04-25 19:07:54] debug: 	zh:ember:ezsp: ezspIncomingMessageHandler(): callback called with: [type=UNICAST], [apsFrame={"profileId":260,"clusterId":64704,"sourceEndpoint":1,"destinationEndpoint":1,"options":256,"groupId":0,"sequence":105}], [lastHopLqi=112], [lastHopRssi=184], [sender=18049], [bindingIndex=255], [addressIndex=255], [messageContents=1c5f1105010a04002064]
[2024-04-25 19:07:54] debug: 	zh:controller: Received payload: clusterID=64704, address=18049, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=112, frame={"header":{"frameControl":{"frameType":0,"manufacturerSpecific":true,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"manufacturerCode":4447,"transactionSequenceNumber":5,"commandIdentifier":1},"payload":[{"attrId":1034,"status":0,"dataType":32,"attrData":100}],"command":{"ID":1,"name":"readRsp","parameters":[{"name":"attrId","type":33},{"name":"status","type":32},{"name":"dataType","type":32,"conditions":[{"type":"statusEquals","value":0}]},{"name":"attrData","type":1000,"conditions":[{"type":"statusEquals","value":0}]}]}}
[2024-04-25 19:07:54] debug: 	z2m: Received Zigbee message from 'Left Kitchen Blind', type 'readResponse', cluster 'manuSpecificLumi', data '{"1034":100}' from endpoint 1 with groupID 0
[2024-04-25 19:07:54] debug: 	zhc:lumi: ZNJLBL01LM: Processed data into payload {"battery":100}
[2024-04-25 19:07:54] debug: 	z2m: MQTT publish: topic 'zigbee2mqtt/Left Kitchen Blind', payload '{"battery":100,"charging_status":false,"device_temperature":25,"last_seen":"2024-04-25T19:07:54+03:00","linkquality":112,"motor_speed":"high","motor_state":"rising","position":0,"power_outage_count":0,"running":true,"state":"OFF","update":{"installed_version":3870,"latest_version":3870,"state":"idle"},"update_available":null}'
[2024-04-25 19:07:54] debug: 	zh:controller:database: Writing database to '/app/data/database.db'
[2024-04-25 19:07:54] error: 	z2m: Failed to configure 'Left Kitchen Blind', attempt 1 (Error: Device 0x54ef4410004a7065 has no input cluster manuSpecificLumi
    at getEndpointsWithCluster (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:29:15)
    at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:65:55)
    at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:110:23)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:160:27)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Configure.configure (/app/lib/extension/configure.ts:121:13)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

**Comment by mamrai1** [comment]
Also the motor state_blocked is missing from mqtt  ("state_blocked": "blocked"),
{
  "availability": [
    {
      "topic": "zigbee2mqtt/bridge/state",
      "value_template": "{{ value_json.state }}"
    },
    {
      "topic": "zigbee2mqtt/Right Kitchen Blind/availability",
      "value_template": "{{ value_json.state }}"
    }
  ],
  "availability_mode": "all",
  "command_topic": "zigbee2mqtt/Right Kitchen Blind/set",
  "device": {
    "identifiers": [
      "zigbee2mqtt_0x54ef4410004a59b5"
    ],
    "manufacturer": "Aqara",
    "model": "Roller shade driver E1 (ZNJLBL01LM)",
    "name": "Right Kitchen Blind",
    "via_device": "zigbee2mqtt_bridge_0xe0798dfffe7d7366"
  },
  "name": null,
  "object_id": "right_kitchen_blind",
  "origin": {
    "name": "Zigbee2MQTT",
    "sw": "1.36.1-dev",
    "url": "https://www.zigbee2mqtt.io"
  },
  "position_template": "{{ value_json.position }}",
  "position_topic": "zigbee2mqtt/Right Kitchen Blind",
  "set_position_template": "{ \"position\": {{ position }} }",
  "set_position_topic": "zigbee2mqtt/Right Kitchen Blind/set",
  "state_closing": "declining",
  "state_opening": "rising",
  "state_stopped": "pause",
  "state_topic": "zigbee2mqtt/Right Kitchen Blind",
  "unique_id": "0x54ef4410004a59b5_cover_zigbee2mqtt",
  "value_template": "{% if \"motor_state\" in value_json and value_json.motor_state %} {{ value_json.motor_state }} {% else %} pause {% endif %}"
}

**Comment by zengateway** [comment]
i have the same problem 
(Error: Device 0x54ef4410004d05d0 has no input cluster manuSpecificLumi at getEndpointsWithCluster (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:30:15) at setupAttributes (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:67:55) at configure (/app/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:112:23) at Object.configure (/app/node_modules/zigbee-herdsman-converters/src/index.ts:160:27) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Configure.configure (/app/lib/extension/configure.ts:121:13) at Configure.onMQTTMessage (/app/lib/extension/configure.ts:55:21) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))

Zigbee2MQTT version
1.37.0
Coordinator type
zStack3x0
Coordinator revision
20230507
Frontend version
0.6.165
19.32.0
0.45.0
