### ISSUE TITLE
Supported Device has no input cluster genAnalogInput at getEndpointsWithCluster

### ISSUE THREAD

**Issue by joshuakoh7** [Koenkk/zigbee-herdsman-converters#7531]
Hi all,

Really perplexed by this situation. Trying to add a couple of new devices to an old network (running since 2020). Aqara WS-K01D and ZNQBKG45LM show as supported but trying to pair them throws error with zigbee-herdsman-converters. Z2M is on the latest commit 1.37.1 which means that zigbee-herdsman-converters is on 19.37.2 according to package.json.

```
Info 2024-05-18 19:20:14Interview for '0x54ef441000c24d43' started
Info 2024-05-18 19:20:14Device '0x54ef441000c24d43' joined
Info 2024-05-18 19:20:14Starting interview of '0x54ef441000c24d43'
Info 2024-05-18 19:20:15Succesfully interviewed '0x54ef441000c24d43'
Info 2024-05-18 19:20:15Successfully interviewed '0x54ef441000c24d43', device has successfully been paired
Info 2024-05-18 19:20:15Device '0x54ef441000c24d43' is supported, identified as: Aqara Smart wall switch H1 20A (with neutral, single rocker) (WS-K01D)
Info 2024-05-18 19:20:16Configuring '0x54ef441000c24d43'
Error 2024-05-18 19:20:16Failed to configure '0x54ef441000c24d43', attempt 1 (Error: Device 0x54ef441000c24d43 has no input cluster genAnalogInput at getEndpointsWithCluster (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:30:15) at setupAttributes (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:67:55) at configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:112:23) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/index.ts:172:27) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:121:13) at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17))
Info 2024-05-18 19:21:38Configuring '0x54ef441000c24d43'
Warning 2024-05-18 19:21:38Images currently unavailable for device 'lumi.switch.acn061', hardwareVersion '1', manufacturerName LUMI, {"fieldControl":0,"manufacturerCode":4447,"imageType":5548,"fileVersion":5396}'
Error 2024-05-18 19:21:38Failed to configure '0x54ef441000c24d43', attempt 2 (Error: Device 0x54ef441000c24d43 has no input cluster genAnalogInput at getEndpointsWithCluster (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:30:15) at setupAttributes (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:67:55) at configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:112:23) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/index.ts:172:27) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:121:13) at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17))
Info 2024-05-18 19:23:52Configuring '0x54ef441000c24d43'
Error 2024-05-18 19:23:52Failed to configure '0x54ef441000c24d43', attempt 3 (Error: Device 0x54ef441000c24d43 has no input cluster genAnalogInput at getEndpointsWithCluster (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:30:15) at setupAttributes (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:67:55) at configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:112:23) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/index.ts:172:27) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:121:13) at EventEmitter.wrappedCallback (/opt/zigbee2mqtt/lib/eventBus.ts:174:17))
```

I see entries for the models in https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/lumi.ts

Only thing that I can think of is the coordinator firmware is from 2021. Using zzh stick.

```
Coordinator type
zStack3x0
Coordinator revision
20210708
```

Hate flashing firmware so trying to upgrading the stick unless necessary.

**Comment by ficusdragoneta** [comment]
I am having this issue and running on the same firmware as you. Did you ever get it fixed?

**Comment by qin-guan** [comment]
I am experiencing this issue as well

**Comment by ficusdragoneta** [comment]
Fixed it by upgrading the my stick firmware.
