### ISSUE TITLE
Add support for Smart Code 10 (lock)

### ISSUE THREAD

**Issue by gcormier** [Koenkk/zigbee-herdsman-converters#799]
Added to devices.js
````
{
    zigbeeModel: ['SMARTCODE_DEADBOLT_10'],
    model: '9GED18000-009',
    vendor: 'Weiser',
    description: 'Weiser Smart Lock',
    supports: 'lock and status',
    fromZigbee: [],
    toZigbee: [],
},
````

Output now, even after toggling lock a few times... is this thing dumb?
````
zigbee2mqtt:warn  2019-12-04T21:32:29: Device '0x002446fffd00c2df' left the network
zigbee2mqtt:info  2019-12-04T21:32:29: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed","message":"left_network","meta":{"friendly_name":"0x002446fffd00c2df"}}'
zigbee2mqtt:info  2019-12-04T21:32:52: Device '0x002446fffd00c2df' joined
zigbee2mqtt:info  2019-12-04T21:32:52: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x002446fffd00c2df"}}'
zigbee2mqtt:info  2019-12-04T21:32:52: Starting interview of '0x002446fffd00c2df'
zigbee2mqtt:info  2019-12-04T21:32:52: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x002446fffd00c2df"}}'
zigbee2mqtt:debug 2019-12-04T21:32:53: Device '0x002446fffd00c2df' announced itself
zigbee2mqtt:debug 2019-12-04T21:32:53: Received Zigbee message from '0x002446fffd00c2df', type 'readResponse', cluster 'genBasic', data '{"modelId":"SMARTCODE_DEADBOLT_10","manufacturerName":"Kwikset","powerSource":3}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2019-12-04T21:32:53: No converter available for '9GED18000-009' with cluster 'genBasic' and type 'readResponse' and data '{"modelId":"SMARTCODE_DEADBOLT_10","manufacturerName":"Kwikset","powerSource":3}'
zigbee2mqtt:debug 2019-12-04T21:32:53: Received Zigbee message from '0x002446fffd00c2df', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1,"appVersion":28,"stackVersion":2}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2019-12-04T21:32:53: No converter available for '9GED18000-009' with cluster 'genBasic' and type 'readResponse' and data '{"zclVersion":1,"appVersion":28,"stackVersion":2}'
zigbee2mqtt:debug 2019-12-04T21:32:53: Received Zigbee message from '0x002446fffd00c2df', type 'readResponse', cluster 'genBasic', data '{"hwVersion":3}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2019-12-04T21:32:53: No converter available for '9GED18000-009' with cluster 'genBasic' and type 'readResponse' and data '{"hwVersion":3}'
zigbee2mqtt:info  2019-12-04T21:32:53: Successfully interviewed '0x002446fffd00c2df', device has successfully been paired
zigbee2mqtt:info  2019-12-04T21:32:53: Device '0x002446fffd00c2df' is supported, identified as: Weiser Weiser Smart Lock (9GED18000-009)
zigbee2mqtt:info  2019-12-04T21:32:53: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x002446fffd00c2df","model":"9GED18000-009","vendor":"Weiser","description":"Weiser Smart Lock","supported":true}}'
````

**Comment by sjorge** [comment]
You need some more things to get this to work
- fromZigbee converters for reading the properties
- toZigbee converts for setting properties
- attReporting... for automatic reporting of changes.

You can try and copy those from an existing lock. e.g. a Yale lock has these for from/to converts. (Note: these may not work for this device)

```
        fromZigbee: [fz.lock],
        toZigbee: [tz.generic_lock],
```

**Comment by gcormier** [comment]
Excellent I'll give it a shot. I thought the debug log would spit out more information prior to adding those converters.

**Comment by sjorge** [comment]
I think by default it only will try to read genBasic which has some device info but nothing more. In this case

"modelId":"SMARTCODE_DEADBOLT_10"
"manufacturerName":"Kwikset"

But looks like this is a total new manufacturer as there aren o devices of Kwikset in the repo, which is a shame because if there were those would be a good starting point.

**Comment by gcormier** [comment]
Ok. Kwikset (USA) and Weiser (Canada) are the same products. Unsure why the different company name.

**Comment by gcormier** [comment]
No luck using those converters. I edited the file, and did a `docker restart` of the zigbee2mqtt container (using hass.io). Also left the network and re-joined.

````
zigbee2mqtt:warn  2019-12-04T23:35:31: Device '0x002446fffd00c2df' left the network
zigbee2mqtt:info  2019-12-04T23:35:31: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed","message":"left_network","meta":{"friendly_name":"0x002446fffd00c2df"}}'
zigbee2mqtt:info  2019-12-04T23:35:37: Device '0x002446fffd00c2df' joined
zigbee2mqtt:info  2019-12-04T23:35:37: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x002446fffd00c2df"}}'
zigbee2mqtt:info  2019-12-04T23:35:37: Starting interview of '0x002446fffd00c2df'
zigbee2mqtt:info  2019-12-04T23:35:37: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x002446fffd00c2df"}}'
zigbee2mqtt:debug 2019-12-04T23:35:37: Device '0x002446fffd00c2df' announced itself
zigbee2mqtt:debug 2019-12-04T23:35:37: Received Zigbee message from '0x002446fffd00c2df', type 'readResponse', cluster 'genBasic', data '{"modelId":"SMARTCODE_DEADBOLT_10","manufacturerName":"Kwikset","powerSource":3}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2019-12-04T23:35:37: No converter available for '9GED18000-009' with cluster 'genBasic' and type 'readResponse' and data '{"modelId":"SMARTCODE_DEADBOLT_10","manufacturerName":"Kwikset","powerSource":3}'
zigbee2mqtt:debug 2019-12-04T23:35:37: Received Zigbee message from '0x002446fffd00c2df', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1,"appVersion":28,"stackVersion":2}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2019-12-04T23:35:37: No converter available for '9GED18000-009' with cluster 'genBasic' and type 'readResponse' and data '{"zclVersion":1,"appVersion":28,"stackVersion":2}'
zigbee2mqtt:debug 2019-12-04T23:35:37: Received Zigbee message from '0x002446fffd00c2df', type 'readResponse', cluster 'genBasic', data '{"hwVersion":3}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2019-12-04T23:35:37: No converter available for '9GED18000-009' with cluster 'genBasic' and type 'readResponse' and data '{"hwVersion":3}'
zigbee2mqtt:info  2019-12-04T23:35:37: Successfully interviewed '0x002446fffd00c2df', device has successfully been paired
zigbee2mqtt:info  2019-12-04T23:35:37: Device '0x002446fffd00c2df' is supported, identified as: Weiser Weiser Smart Lock (9GED18000-009)
zigbee2mqtt:info  2019-12-04T23:35:37: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x002446fffd00c2df","model":"9GED18000-009","vendor":"Weiser","description":"Weiser Smart Lock","supported":true}}'
````

This lock must be transmitting lock status occasionally - is there a way to sniff these packets even if we don't have a converter yet to handle it?

**Comment by sjorge** [comment]
If you have a 2nd usb stick you can sniff the traffic with wire shark, there is a page on the website about how to do it.

~ sjorge

**Comment by gcormier** [comment]
Only the single CC2652 unfortunately :( I guess I can't use it since the lock will want an active hub before to send out the packets?

**Comment by sjorge** [comment]
Yes. Unless you have the gateway from Weiser  that you can pair the lock with I guess.

**Comment by gcormier** [comment]
I guess a functional hub would be needed as well to figure out commands that can be sent to the lock? A sniffer would only help decode status?

I could go with a cheap 2nd Zigbee stick to sniff, but if I want to get 2-way functionality via HA, I'd ultimately need to sniff what's being sent out as well. Looks like my options are

- "Works with Amazon Alexa via Samsung SmartThings and/or Wink. Compatible with Echo Plus."

If I pick one of those up, is there sniffing firmware for the newer CC2652 I could flash temporarily?

**Comment by sjorge** [comment]
You can probably start with just an extra stick, you can sniff what the lock is sending to your current coordinator and that will hopefully be enough to figure out what is needed.

**Comment by gcormier** [comment]
@Koenkk Any thoughts on this one?

**Comment by Koenkk** [comment]
With the following configuration, can you control the lock by sending to `zigbee2mqtt/[FRIENDLY_NAME]/set` payload: `LOCK` or `UNLOCK`?

```js
{
    zigbeeModel: ['SMARTCODE_DEADBOLT_10'],
    model: '9GED18000-009',
    vendor: 'Weiser',
    description: 'Weiser Smart Lock',
    supports: 'lock and status',
    fromZigbee: [fz.lock, fz.lock_operation_event, fz.battery_200],
    toZigbee: [tz.generic_lock],
},
```

**Comment by luckypants123** [comment]
Not OP but i'm also having the same issue.

Koenkk - I added this to devices.js and published lock and unlock.

Got this on startup:
`zigbee2mqtt:info  2019-12-13 21:22:21: back_door_lock (0x002446fffd01e4f3): Not supported (EndDevice)`

And this on lock/unlock publish:
`zigbee2mqtt:warn  2019-12-13 21:22:49: Device with modelID 'SMARTCODE_DEADBOLT_10T' is not supported.
zigbee2mqtt:warn  2019-12-13 21:22:49: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html
zigbee2mqtt:warn  2019-12-13 21:22:59: Device with modelID 'SMARTCODE_DEADBOLT_10T' is not supported.
zigbee2mqtt:warn  2019-12-13 21:22:59: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html`

**Comment by Koenkk** [comment]
Does it work correctly with:

```js
{
    zigbeeModel: ['SMARTCODE_DEADBOLT_10'],
    model: '9GED18000-009',
    vendor: 'Weiser',
    description: 'Weiser Smart Lock',
    supports: 'lock/unlock, battery',
    fromZigbee: [fz.lock, fz.lock_operation_event, fz.battery_200],
    toZigbee: [tz.generic_lock],
    meta: {options: {disableDefaultResponse: true}, configureKey: 1},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(1);
        await configureReporting.lockState(endpoint);
        await configureReporting.batteryPercentageRemaining(endpoint);
    },
},
```

**Comment by luckypants123** [comment]
Tried it out - it posts an error in the log:

```
zigbee2mqtt:info  2019-12-15 11:19:59: Configuring 'back_door_lock'
zigbee2mqtt:error 2019-12-15 11:19:59: Failed to configure 'back_door_lock', attempt 1 (TypeError: Cannot read property 'configureReporting' of undefined
    at Object.lockState (/app/node_modules/zigbee-herdsman-converters/devices.js:74:24)
    at Object.configure (/app/node_modules/zigbee-herdsman-converters/devices.js:4656:29)
    at DeviceConfigure.configure (/app/lib/extension/deviceConfigure.js:92:32)
    at DeviceConfigure.onZigbeeStarted (/app/lib/extension/deviceConfigure.js:61:28)
    at Controller.callExtensionMethod (/app/lib/controller.js:322:44))
```

**Comment by Koenkk** [comment]
First make sure you are on zigbee2mqtt 1.8.0 with an untouched `devices.js`, after that add this section..

**Comment by luckypants123** [comment]
Ok - i am on edge right now. I may have misunderstood some previous posts as I thought only the edge imported a custom devices.js.

**Comment by Koenkk** [comment]
@luckypants123 1.7.1 should also be fine. Can you post your complete `devices.js`? (on pastebin.com and link it here).

**Comment by luckypants123** [comment]
Yes of course:
https://pastebin.com/a2vyNjQX

**Comment by Koenkk** [comment]
Ok it seems that we are using the wrong endpoint can you share `database.db`?

**Comment by luckypants123** [comment]
Absolutely:
```
{"id":1,"type":"Coordinator","ieeeAddr":"0x00124b00194adbb1","nwkAddr":0,"manufId":0,"epList":[110,11,8,6,5,4,3,2,1],"endpoints":{"1":{"profId":260,"epId":1,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"2":{"profId":257,"epId":2,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"3":{"profId":261,"epId":3,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"4":{"profId":263,"epId":4,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"5":{"profId":264,"epId":5,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"6":{"profId":265,"epId":6,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"8":{"profId":260,"epId":8,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]},"11":{"profId":260,"epId":11,"devId":1024,"inClusterList":[],"outClusterList":[1280],"clusters":{},"binds":[]},"110":{"profId":260,"epId":110,"devId":5,"inClusterList":[],"outClusterList":[],"clusters":{},"binds":[]}},"interviewCompleted":false,"meta":{}}
{"id":2,"type":"EndDevice","ieeeAddr":"0x000d6f000e74248b","nwkAddr":18161,"manufId":4113,"manufName":"Visonic","powerSource":"Battery","modelId":"MP-841","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,32,1026,1280,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"MP-841","manufacturerName":"Visonic","powerSource":3,"zclVersion":1,"appVersion":0,"stackVersion":0,"hwVersion":1}}},"binds":[]}},"appVersion":0,"stackVersion":0,"hwVersion":1,"zclVersion":1,"interviewCompleted":false,"meta":{}}
{"id":3,"type":"EndDevice","ieeeAddr":"0x000d6f000e75f028","nwkAddr":53030,"manufId":4113,"manufName":"Visonic","powerSource":"Battery","modelId":"MP-841","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,32,1026,1280,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"MP-841","manufacturerName":"Visonic","powerSource":3,"zclVersion":1,"appVersion":0,"stackVersion":0,"hwVersion":1}}},"binds":[]}},"appVersion":0,"stackVersion":0,"hwVersion":1,"zclVersion":1,"interviewCompleted":false,"meta":{}}
{"id":4,"type":"EndDevice","ieeeAddr":"0x002446fffd01e4f3","nwkAddr":35582,"manufId":4242,"manufName":"Kwikset","powerSource":"Battery","modelId":"SMARTCODE_DEADBOLT_10T","epList":[2],"endpoints":{"2":{"profId":260,"epId":2,"devId":10,"inClusterList":[0,1,3,4,5,9,32,257,1026,2821,64957],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"SMARTCODE_DEADBOLT_10T","manufacturerName":"Kwikset","powerSource":3,"zclVersion":1,"appVersion":52,"stackVersion":2,"hwVersion":99}},"closuresDoorLock":{"attributes":{"lockState":1}}},"binds":[]}},"appVersion":52,"stackVersion":2,"hwVersion":99,"zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":5,"type":"EndDevice","ieeeAddr":"0x002446fffd0608a6","nwkAddr":51017,"manufId":4242,"manufName":"Kwikset","powerSource":"Battery","modelId":"SMARTCODE_DEADBOLT_10T","epList":[2],"endpoints":{"2":{"profId":260,"epId":2,"devId":10,"inClusterList":[0,1,3,4,5,9,32,257,1026,2821,64957],"outClusterList":[10,25],"clusters":{"genBasic":{"attributes":{"modelId":"SMARTCODE_DEADBOLT_10T","manufacturerName":"Kwikset","powerSource":3,"zclVersion":1,"appVersion":52,"stackVersion":2,"hwVersion":101}},"closuresDoorLock":{"attributes":{"lockState":1}}},"binds":[]}},"appVersion":52,"stackVersion":2,"hwVersion":101,"zclVersion":1,"interviewCompleted":true,"meta":{}}
{"id":6,"type":"EndDevice","ieeeAddr":"0x000d6f000cbf70b5","nwkAddr":57843,"manufId":4113,"manufName":"Visonic","powerSource":"Battery","modelId":"MCT-370 SMA","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,32,1026,1280,2821],"outClusterList":[25],"clusters":{"genBasic":{"attributes":{"modelId":"MCT-370 SMA","manufacturerName":"Visonic","powerSource":3,"zclVersion":1,"appVersion":1,"stackVersion":0,"hwVersion":1}}},"binds":[]}},"appVersion":1,"stackVersion":0,"hwVersion":1,"zclVersion":1,"interviewCompleted":false,"meta":{}}
{"id":7,"type":"EndDevice","ieeeAddr":"0x000d6f000fdb0453","nwkAddr":90,"manufId":4401,"manufName":"Sercomm Corp.","powerSource":"Battery","modelId":"SZ-DWS04","epList":[1],"endpoints":{"1":{"profId":260,"epId":1,"devId":1026,"inClusterList":[0,1,3,1026,1280,32,2821],"outClusterList":[3,25],"clusters":{"genBasic":{"attributes":{"modelId":"SZ-DWS04","manufacturerName":"Sercomm Corp.","powerSource":3,"zclVersion":1,"appVersion":35,"stackVersion":81,"hwVersion":18,"dateCode":"20161216","swBuildId":""}},"msTemperatureMeasurement":{"attributes":{"measuredValue":0}}},"binds":[{"cluster":1026,"type":"endpoint","deviceIeeeAddress":"0x00124b00194adbb1","endpointID":1},{"cluster":1,"type":"endpoint","deviceIeeeAddress":"0x00124b00194adbb1","endpointID":1}]}},"appVersion":35,"stackVersion":81,"hwVersion":18,"dateCode":"20161216","swBuildId":"","zclVersion":1,"interviewCompleted":true,"meta":{"configured":1}}
```

**Comment by Koenkk** [comment]
Does it work correctly with:

```js
{
    zigbeeModel: ['SMARTCODE_DEADBOLT_10'],
    model: '9GED18000-009',
    vendor: 'Weiser',
    description: 'Weiser Smart Lock',
    supports: 'lock/unlock, battery',
    fromZigbee: [fz.lock, fz.lock_operation_event, fz.battery_200],
    toZigbee: [tz.generic_lock],
    meta: {options: {disableDefaultResponse: true}, configureKey: 2},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(2);
        await configureReporting.lockState(endpoint);
        await configureReporting.batteryPercentageRemaining(endpoint);
    },
},
```

**Comment by luckypants123** [comment]
Looks Good!

I have in the log:
```
zigbee2mqtt:info  2019-12-17 00:24:52: back_door_lock (0x002446fffd01e4f3): 9GED18000-009 - Weiser Weiser Smart Lock (EndDevice)
```
then
```
zigbee2mqtt:info  2019-12-17 00:24:52: Configuring 'back_door_lock'
zigbee2mqtt:info  2019-12-17 00:24:55: Succesfully configured 'back_door_lock'
```
then
```
zigbee2mqtt:info  2019-12-17 00:24:56: MQTT publish: topic 'zigbee2mqtt/back_door_lock', payload '{"state":"LOCK","linkquality":89}'
```
then commanding a lock and then unlock:
```
zigbee2mqtt:info  2019-12-17 00:28:57: MQTT publish: topic 'zigbee2mqtt/back_door_lock', payload '{"state":"LOCK","linkquality":89}'
zigbee2mqtt:info  2019-12-17 00:29:05: MQTT publish: topic 'zigbee2mqtt/back_door_lock', payload '{"state":"LOCK","linkquality":81}'
zigbee2mqtt:info  2019-12-17 00:29:40: MQTT publish: topic 'zigbee2mqtt/back_door_lock', payload '{"state":"UNLOCK","linkquality":81}'
zigbee2mqtt:info  2019-12-17 00:29:44: MQTT publish: topic 'zigbee2mqtt/back_door_lock', payload '{"state":"UNLOCK","linkquality":81}'
```

Works beautifully! I don't know why each lock/unlock event has 2 entries, but i'm not complaining!

**Comment by luckypants123** [comment]
The only thing required to change is the device name. 
You have it listed as:
`
zigbeeModel: ['SMARTCODE_DEADBOLT_10'],
`

But it needs a “T” at the end:
`
zigbeeModel: ['SMARTCODE_DEADBOLT_10T'],
`

Would you like me to do the PR?

**Comment by Koenkk** [comment]
@luckypants123 yes, please make a PR!

**Comment by gcormier** [comment]
Nice work @luckypants123  and @Koenkk , sorry I wasn't much help I was travelling abroad!

I suspect many of their deadbolts to behave the same. The T must be the touch model, but the circuits would be the same.

**Comment by luckypants123** [comment]
@gcormier  Just want to verify that it works for you also. If so I will add your model as well as mine to the PR.

**Comment by gcormier** [comment]
After adding

```
{
    zigbeeModel: ['SMARTCODE_DEADBOLT_10'],
    model: '9GED18000-009',
    vendor: 'Weiser',
    description: 'Weiser Smart Lock',
    supports: 'lock/unlock, battery',
    fromZigbee: [fz.lock, fz.lock_operation_event, fz.battery_200],
    toZigbee: [tz.generic_lock],
    meta: {options: {disableDefaultResponse: true}, configureKey: 2},
    configure: async (device, coordinatorEndpoint) => {
        const endpoint = device.getEndpoint(2);
        await configureReporting.lockState(endpoint);
        await configureReporting.batteryPercentageRemaining(endpoint);
    },
},
````

And restarting, I get this when pairing.

````
zigbee2mqtt:info  2019-12-17 17:32:56: Device '0x002446fffd00c2df' joined
zigbee2mqtt:info  2019-12-17 17:32:56: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_connected","message":{"friendly_name":"0x002446fffd00c2df"}}'
zigbee2mqtt:info  2019-12-17 17:32:56: Starting interview of '0x002446fffd00c2df'
zigbee2mqtt:info  2019-12-17 17:32:56: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_started","meta":{"friendly_name":"0x002446fffd00c2df"}}'
zigbee2mqtt:debug 2019-12-17 17:32:57: Device '0x002446fffd00c2df' announced itself
zigbee2mqtt:debug 2019-12-17 17:32:57: Received Zigbee message from '0x002446fffd00c2df', type 'readResponse', cluster 'genBasic', data '{"modelId":"SMARTCODE_DEADBOLT_10","manufacturerName":"Kwikset","powerSource":3}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2019-12-17 17:32:57: No converter available for '9GED18000-009' with cluster 'genBasic' and type 'readResponse' and data '{"modelId":"SMARTCODE_DEADBOLT_10","manufacturerName":"Kwikset","powerSource":3}'
zigbee2mqtt:debug 2019-12-17 17:32:57: Received Zigbee message from '0x002446fffd00c2df', type 'readResponse', cluster 'genBasic', data '{"zclVersion":1,"appVersion":28,"stackVersion":2}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2019-12-17 17:32:57: No converter available for '9GED18000-009' with cluster 'genBasic' and type 'readResponse' and data '{"zclVersion":1,"appVersion":28,"stackVersion":2}'
zigbee2mqtt:debug 2019-12-17 17:32:57: Received Zigbee message from '0x002446fffd00c2df', type 'readResponse', cluster 'genBasic', data '{"hwVersion":3}' from endpoint 2 with groupID 0
zigbee2mqtt:debug 2019-12-17 17:32:57: No converter available for '9GED18000-009' with cluster 'genBasic' and type 'readResponse' and data '{"hwVersion":3}'
zigbee2mqtt:info  2019-12-17 17:32:57: Successfully interviewed '0x002446fffd00c2df', device has successfully been paired
zigbee2mqtt:info  2019-12-17 17:32:57: Device '0x002446fffd00c2df' is supported, identified as: Weiser Weiser Smart Lock (9GED18000-009)
zigbee2mqtt:info  2019-12-17 17:32:57: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"pairing","message":"interview_successful","meta":{"friendly_name":"0x002446fffd00c2df","model":"9GED18000-009","vendor":"Weiser","description":"Weiser Smart Lock","supported":true}}'
zigbee2mqtt:info  2019-12-17 17:32:57: Configuring '0x002446fffd00c2df'
zigbee2mqtt:info  2019-12-17 17:32:57: Succesfully configured '0x002446fffd00c2df'
````

I'm not sure how to inject the test messages, but locking/unlocking the door does not produce any log output.

**Comment by Koenkk** [comment]
This device is now supported in the latest dev branch.
