### ISSUE TITLE
Legrand 067696 module to open garage doors and gates

### ISSUE THREAD

**Issue by dsigmoun** [Koenkk/zigbee-herdsman-converters#8035]
Hello,

I use the Legrand 067696 module to open my garage doors and gates. In Z2M, the module is indicated unmanaged command. 
The Open, close, stop commands work correctly, but the state is not well managed.

![image](https://github.com/user-attachments/assets/599bf270-9284-4627-ac33-101ab50a8b19)
![image](https://github.com/user-attachments/assets/7120d7f9-6b6a-4862-aeb8-40d9c8ba0345)
![image](https://github.com/user-attachments/assets/904f1f6c-3edc-44ff-93b3-c3846b9613e8)

I followed this procedure and created a file 067696.js
https://www.zigbee2mqtt.io/advanced/support-new-devices/01_support_new_devices.html#_2-creating-the-external-definition

```
`const {windowCovering, binary, commandsWindowCovering} = require('zigbee-herdsman-converters/lib/modernExtend');

const definition = {
    zigbeeModel: [' NLJ - Garage door'],
    model: ' NLJ - Garage door',
    vendor: ' Legrand',
    description: 'Automatically generated definition',
    extend: [windowCovering({"controls":["lift","tilt"]}), binary({"name":"binary_input_1","cluster":"genBinaryInput","attribute":"presentValue","reporting":{"attribute":"presentValue","min":"MIN","max":"MAX","change":1},"valueOn":["ON",1],"valueOff":["OFF",0],"description":"binary_input_1","access":"STATE_GET","endpointName":"1"}), commandsWindowCovering()],
    meta: {},
};

module.exports = definition;`
```

The status information seems better handled, but I'm not sure what to do next.

`{
    "linkquality": 255,
    "position": 0,
    "state": "CLOSE",
    "device": {
        "applicationVersion": 0,
        "dateCode": " \u000020240117\u0000\u0000\u0000\u0000\u0000",
        "friendlyName": "0x0004740000280f20",
        "hardwareVersion": 1,
        "ieeeAddr": "0x0004740000280f20",
        "manufacturerID": 4129,
        "manufacturerName": " Legrand",
        "model": " NLJ - Garage door\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
        "networkAddress": 56364,
        "powerSource": "Mains (single phase)",
        "softwareBuildID": "000b",
        "stackVersion": 69,
        "type": "Router",
        "zclVersion": 8
    }
}`

**Comment by dsigmoun** [comment]
And here is an error in the logs when trying to update the module

`2024-09-27 21:12:53z2m: Failed to configure '0x0004740000280f20', attempt 5 (Error: ZCL command 0x0004740000280f20/1 closuresWindowCovering.configReport([{"minimumReportInterval":1,"maximumReportInterval":65000,"reportableChange":1,"attribute":"currentPositionLiftPercentage"}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (no response received (99) waiting for response TIMEOUT) at DeconzAdapter.sendZclFrameToEndpoint (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:931:19) at runNextTicks (node:internal/process/task_queues:60:5) at processTimers (node:internal/timers:516:9) at Request.send (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:82:20) at Endpoint.zclCommand (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:911:28) at Endpoint.configureReporting (/opt/zigbee2mqtt/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:648:9) at setupAttributes (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:110:13) at configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/lib/modernExtend.ts:155:17) at Object.configure (/opt/zigbee2mqtt/node_modules/zigbee-herdsman-converters/src/index.ts:193:21) at Configure.configure (/opt/zigbee2mqtt/lib/extension/configure.ts:125:13))`
