### ISSUE TITLE
SNZB-03P  Zigbee2mqtt frontend   battery level power is a "?" 

### ISSUE THREAD

**Issue by xdmore70** [Koenkk/zigbee-herdsman-converters#8098]
In the Zigbee2mqtt  1.40.2 frontend release the device Sonoff SNZB-03P  battery level power is show like "?"
![Screenshot 2024-10-08 162219](https://github.com/user-attachments/assets/531d361f-96cf-4130-9b2b-ecbe497b3613)

I found some other posts  that reported this issue,  but i don't find the solution

**Comment by Great-Chart** [comment]
Not sure on this particular device but noticed some fixes in recent Z2M releases tackling this issue. I resolved a few similar issues via waking up device and pressing the configure (orange icon) button - see your screenshot.

**Comment by xdmore70** [comment]
Thanks for  tips, but if i press the configure i received error:

info 2024-10-09 21:34:38z2m: Configuring 'sonoff-infrarosso-garage'
error 2024-10-09 21:34:54z2m: Failed to configure 'sonoff-infrarosso-garage', attempt 1 (Error: Bind 0x842712fffe735ed5/1 genPowerCfg from '0xb43522fffec19b2e/1' failed ({"target":24651,"apsFrame":{"profileId":0,"clusterId":33,"sourceEndpoint":0,"destinationEndpoint":0,"options":4416,"groupId":0,"sequence":247},"zdoResponseClusterId":32801} timed out after 15000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/oneWaitress.ts:195:23) at EmberOneWaitress.startWaitingFor (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/oneWaitress.ts:219:50) at /app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1915:51 at processTicksAndRejections (node:internal/process/task_queues:95:5) at runNextTicks (node:internal/process/task_queues:64:3) at processImmediate (node:internal/timers:447:9) at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20) at EmberAdapter.sendZdo (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1842:16) at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:563:30) at Object.bind (/app/node_modules/zigbee-herdsman-converters/src/lib/reporting.ts:42:9))
info 2024-10-09 21:34:54z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/response/device/configure', payload '{"data":{"id":"sonoff-infrarosso-garage"},"error":"Failed to configure (Bind 0x842712fffe735ed5/1 genPowerCfg from '0xb43522fffec19b2e/1' failed ({\"target\":24651,\"apsFrame\":{\"profileId\":0,\"clusterId\":33,\"sourceEndpoint\":0,\"destinationEndpoint\":0,\"options\":4416,\"groupId\":0,\"sequence\":247},\"zdoResponseClusterId\":32801} timed out after 15000ms))","status":"error","transaction":"khh9g-9"}'

**Comment by Great-Chart** [comment]
I do have a Sonoff SNZB-03 (non P version) and it acts similarly to yours.
The fixes I referenced are detailed in https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.40.2
![image](https://github.com/user-attachments/assets/09970e57-409f-472d-8893-31798d4d3c39)

The https://github.com/Koenkk/zigbee2mqtt/issues/24007battery related one may have some clues about a restart of Z2M (which of course you may have applied already)!

**Comment by xdmore70** [comment]
thank you so much for your reply
For me not fix 
I opened a comment https://github.com/Koenkk/zigbee2mqtt/issues/24007#issuecomment-2404519935
let's see if there are any developments

**Comment by alexsotoaguilera** [comment]
For me fix another devices but not for this.

**Comment by fibu-freak** [comment]
see my post here:
[https://github.com/Koenkk/zigbee2mqtt/issues/24007](url)

**Comment by pezzy-o** [comment]
Fixed on Sonoff SNZB-03P after I upgraded from 1.40.2 to 1.42.0 and then followed the instruction here:
https://github.com/Koenkk/zigbee2mqtt/issues/24007#issuecomment-2489447823 

I didn’t need to reboot - the battery displayed immediately after (physically) waking the device and refreshing.

<img width="1366" alt="image" src="https://github.com/user-attachments/assets/882e0806-e644-4340-ae0a-f501bc440454" />
