### ISSUE TITLE
EWAY CASA Smart Vertical Blinds Vertical Slats Tuya Zigbee Motor issue

### ISSUE THREAD

**Issue by Mrsash2020** [Koenkk/zigbee-herdsman-converters#8260]
Hi

I have just purchased 3 of these motors and paired them. https://www.aliexpress.com/item/1005006902297209.html

I tried getting to the Dev console on one since they said originally that they are unsupported but when I navigated again to Dev console I got this. Clicking on step 2 link to save the file does not yield any downloads etc.

![image](https://github.com/user-attachments/assets/8e492702-bcaf-445f-b00d-c03df05ccdea)

TypeError
Cannot read properties of undefined (reading 'clusters')
TypeError: Cannot read properties of undefined (reading 'clusters')
    at zs.render (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/ConnectedDevicePage-792280da.js:1:31105)
    at ab (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:6186)
    at yD (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:5982)
    at r3 (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:44865)
    at e3 (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:39756)
    at ISe (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:39682)
    at ap (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:39534)
    at cb (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:35900)
    at CD (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:43:36704)
    at Gn (http://homeassistant.local:8123/api/hassio_ingress/1d39maaHKvuu-UNIpzFdI1jf0My4sfjmzraVT_lMzpQ/assets/index-74e84a13.js:41:3283)

**Comment by Koenkk** [comment]
Please create issues related to the frontend in this repository: https://github.com/nurikk/zigbee2mqtt-frontend
