### ISSUE TITLE
Sonoff Basic Zigbee - Failed to setup reporting

### ISSUE THREAD

**Issue by Erelen-Laiquendi** [Koenkk/zigbee-herdsman-converters#902]
With `"report": true` error on every z2m start:
```
zigbee2mqtt:error 2020-01-14 02:51:29: Failed to setup reporting for '0x00<...>' - Error: Timeout - 15180 - 1 - 2 - 6 - 7 after 10000ms
    at Timeout.object.timer.setTimeout [as _onTimeout] (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:44:24)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
```
On current edge - too.

If device doesn't support it - can it be turned off in converters?

**Comment by Koenkk** [comment]
Closing this one in favor of https://github.com/Koenkk/zigbee2mqtt/issues/2740 (because it's a zigbee2mqtt issue).
