### ISSUE TITLE
Adding support for HEIMAN CO sensor (CO_V16)

### ISSUE THREAD

**Issue by pbochenski** [Koenkk/zigbee-herdsman-converters#980]
Hi, 
I'm trying to add support for my co sensor. I saw that there already is support for CO_V15, but adding new model for old configuration does not work. it fails with:

```
zigbee2mqtt:error 2020-02-12 13:30:18: Failed to configure '0x005043c9e721243b', attempt 1 (Error: Bind 0x005043c9e721243b/1 genPowerCfg from '0x00124b0018ed1823/1' failed (Error: AREQ - ZDO - bindRsp after 10000ms)
    at Endpoint.<anonymous> (/zigbee2mqtt-1.10.0/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:235:23)
    at Generator.throw (<anonymous>)
    at rejected (/zigbee2mqtt-1.10.0/node_modules/zigbee-herdsman/dist/controller/model/endpoint.js:6:65))
```

my `database.db` entry for it is:
```
{
  "id": 6,
  "type": "EndDevice",
  "ieeeAddr": "0x005043c9e721243b",
  "nwkAddr": 50587,
  "manufId": 48042,
  "manufName": "Heiman",
  "powerSource": "Battery",
  "modelId": "CO_V16",
  "epList": [
    1
  ],
  "endpoints": {
    "1": {
      "profId": 260,
      "epId": 1,
      "devId": 1026,
      "inClusterList": [
        0,
        3,
        1280,
        1,
        9
      ],
      "outClusterList": [
        25
      ],
      "clusters": {
        "genBasic": {
          "attributes": {
            "modelId": "CO_V16",
            "manufacturerName": "Heiman",
            "powerSource": 3,
            "zclVersion": 1,
            "appVersion": 3,
            "stackVersion": 2,
            "hwVersion": 1,
            "dateCode": "20150330"
          }
        },
        "ssIasZone": {
          "attributes": {
            "iasCieAddr": "0x00124b0018ed1823",
            "zoneState": 1
          }
        }
      },
      "binds": []
    }
  },
  "appVersion": 3,
  "stackVersion": 2,
  "hwVersion": 1,
  "dateCode": "20150330",
  "zclVersion": 1,
  "interviewCompleted": true,
  "meta": {},
  "lastSeen": 1581505199174
}
```
I guess there is no `genPowerCfg` at all. how can I configure it?

**Comment by Koenkk** [comment]
It has `genPowerCfg`, but the device is probably sleeping while the configure is being executed. 

Repairing your device should fix it (or try to wake up the device manually by pressing a button on it when configuring).
